### ISSUE TITLE
Active directory yaml and global matrix authorization getting an errors

### ISSUE THREAD

**Issue by Rahaman148** [jenkinsci/configuration-as-code-plugin#1032]
@ewelinawilkosz 

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x ] Plugin version

- [x ] OS

### Description
jenkins 2.17
matrix authorization strategy 2.42
casc plugin 1.25, 1.23
OS windows 10
Ubuntu 16.04

I am trying to apply active directory yaml in my jenkins.yaml file but before adding I tested code and got an error. I saw that some issue related with that where mentioned permission issue. If I used `grantedPermissions` or `permissions` as the same error please tell me how can I solve that 
here is my code in two ways I tried
```
jenkins:
  SecurityRealm:
    activeDirectory:
      domain: abcd.com
      groupLookupStrategy: RECURSIVE
      startTls: true
      site: USA
      server: xyz.com
      bindName: "CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com"
      bindPassword: $dotnet_password
      domains:
        - name: "adcd.com"
          servers: "xyz.com"
          site: Nashville-UPO
          tlsConfiguration: YK_TRUSTSTORE
          bindName: CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com
          bindPassword: $dotnet_password
  authorizationStrategy:
    globalMatrix:
      permissions:      #or grantedPermissions: 
        - "Job/Read:as56027"
        - "Overall/Administer:AD51D1234EE_FUNS Tools_Salary"
        - "Overall/Administer:AD51D1234EE_FUNS Tools_Other"
        - "Overall/Administer:$user_id"
        - "Overall/Read:as56027"
        - "View/Read:as56027"

```
```
jenkins:
  SecurityRealm:
    activeDirectory:
      domain: abcd.com
      groupLookupStrategy: RECURSIVE
      startTls: true
      site: USA
      server: xyz.com
      bindName: "CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com"
      bindPassword: $dotnet_password
      domains:
        - name: "adcd.com"
          servers: "xyz.com"
          site: Nashville-UPO
          tlsConfiguration: YK_TRUSTSTORE
          bindName: CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com
          bindPassword: $dotnet_password
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Jenkins/Read:as56027"
        - "Jenkins/Administer:AD51D1234EE_FUNS Tools_Salary"
        - "Jenkins/Administer:AD51D1234EE_FUNS Tools_Other"
        - "Jenkins/Administer:$user_id"
        - "Jenkins/Item:as56027"
        - "Jenkins/View:as56027"

```

erros 
```
string: Failed to set attribute permissions(class: class java.lang.String, multiple: true)
java.lang.IllegalArgumentException: Permission can not be null for sid:as56027
	at hudson.security.GlobalMatrixAuthorizationStrategy.add(GlobalMatrixAuthorizationStrategy.java:94)
	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.lambda$setPermissions$3(MatrixAuthorizationStrategyConfigurator.java:65)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.setPermissions(MatrixAuthorizationStrategyConfigurator.java:62)
	at io.jenkins.plugins.casc.Attribute.setValue(Attribute.java:208)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:359)
Caused: io.jenkins.plugins.casc.ConfiguratorException: string: Failed to set attribute permissions(class: class java.lang.String, multiple: true)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:361)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:277)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:278)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:278)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$2(HeteroDescribableConfigurator.java:86)
	at io.vavr.control.Option.map(Option.java:373)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:86)
	at io.vavr.Tuple2.apply(Tuple2.java:239)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:702)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:664)
Caused: io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:670)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:702)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:597)
	at io.jenkins.plugins.casc.ConfigurationAsCode.collectIssues(ConfigurationAsCode.java:233)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doCheckNewSource(ConfigurationAsCode.java:215)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:537)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:458)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
Is it just a typo? One of the yaml lines you have is overall/read rather than Overall/Read

It’s saying it couldn’t find the permission, normally this is because of a missing plugin but in this case I think there’s a typo or a wrong permission.
Others ways to fix it would be to configure it in the ui and export it, or remove permissions one by one / remove all and add one by one

The error message should likely be improved but that’s for the matrix-auth plugin

**Comment by Rahaman148** [comment]
@timja 
I typed wrong when I did modification but my code is ok in my system `"Overall/Read"`. I applied second one as well getting as the same errors.
I did in UI but getting same errors. I don't know how to fix that

**Comment by timja** [comment]
Try reduce the permissions down then,

**Comment by Rahaman148** [comment]
@timja 
It works like charm if I delete some permission at the end and I tried in UI, again whatever permission I deleted and I added again , now it's work fine means all are working. Thanks for your help

**Comment by Rahaman148** [comment]
@timja 
So I have to use `"Overall/Administer:.."` instead of `"Jenkins/Administer:..."` because Jenkins/Administer doesn't work.

it worked both way `permissions` or `grantedPermissions`

```
jenkins:
  SecurityRealm:
    activeDirectory:
      domain: abcd.com
      groupLookupStrategy: RECURSIVE
      startTls: true
      site: USA
      server: xyz.com
      bindName: "CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com"
      bindPassword: $dotnet_password
      domains:
        - name: "adcd.com"
          servers: "xyz.com"
          site: Nashville-UPO
          tlsConfiguration: YK_TRUSTSTORE
          bindName: CN=$dotnet_user,OU=ServiceAccounts,OU=JDUsers,DC=dotnet,DC=dodges,DC=com
          bindPassword: $dotnet_password
  authorizationStrategy:
    globalMatrix:
      permissions:      #or grantedPermissions: 
        - "Job/Read:as56027"
        - "Overall/Administer:AD51D1234EE_FUNS Tools_Salary"
        - "Overall/Administer:AD51D1234EE_FUNS Tools_Other"
        - "Overall/Administer:$user_id"
        - "Overall/Read:as56027"
        - "View/Read:as56027"
```

**Comment by casz** [comment]
These permissions name needs to be like that as they map to a Permission group and a permission name.

**Comment by Rahaman148** [comment]
@casz 

active directory 2.16
When I configured active directory always locked me out! I am not able login jenkins. I applied manually and it says configuration can be applied , when I clicked `apply new configuration` after that I can't login back. I used my credentials and it says `Invalid Username and Password`. 

I don't know is this plugins related or permissions?
