### ISSUE TITLE
wants to apply configuration as code yaml file through groovy

### ISSUE THREAD

**Issue by Rahaman148** [jenkinsci/configuration-as-code-plugin#1067]
@ewelinawilkosz 
 

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [2.194 ] Jenkins version

- [1.30 ] Plugin version

- [ windows 10] OS

### Description

I am just checking is this issue resolved "https://issues.jenkins-ci.org/browse/JENKINS-58453?filter=10244"? Because I need to follow to same step to apply configuration as code yaml file through groovy.

I was looking for how to apply that but I found something on above link.

Any help please

**Comment by timja** [comment]
Is this what you're looking for?
https://github.com/jenkinsci/configuration-as-code-groovy-plugin

**Comment by Rahaman148** [comment]
@timja 
No, I want to use function (groovy) to call configuration as code plugin which is going to do configuration instead of doing from the BootSource.
 I am looking for something like this - "https://issues.jenkins-ci.org/browse/JENKINS-58453?filter=10244"
"We have a groovy script that calls the plugin directly to apply the configuration after build completion, so that we can keep the CasC settings in source control to apply to our Jenkins servers. We've noticed that the server will eventually run out of file handles and tracked it down to the CasC configuration file. The file handle leak makes this unusable."
 
right now everything is configured but I am not able to do that how to use or call that configuration as code plugin yaml file using groovy function.
here is the code which I found and looking for like this -
```
def casc = new GroovyClassLoader(context.class.getClassLoader()).loadClass("io.jenkins.plugins.casc.ConfigurationAsCode")
def configFile = new File(configPath)
if (casc && configFile.exists()) {
     context.echo("Now loading config file: ${configFile./var/lib/jenkins/casc_configs/openstack.yaml}")
     casc.get().configure(configFile./var/lib/jenkins/casc_configs/openstack.yaml)        
}
```
But I don't want to loadClass because I already used `import io.jenkins....` from the beginning.

**Comment by timja** [comment]
ConfigurationAsCode.get().connfigure()

**Comment by Rahaman148** [comment]
@timja 

do I need to use in this way please correct me - 

```
def casc = new GroovyClassLoader(context.class.getClassLoader()).ConfigurationAsCode.get().configure()
def configFile = new File(configPath)
if (casc && configFile.exists()) {
     context.echo("Now loading config file: ${configFile./var/lib/jenkins/casc_configs/openstack.yaml}")
     casc.get().configure(configFile./var/lib/jenkins/casc_configs/openstack.yaml)        
}
```
what it does `GroovyClassLoader(context.class.getClassLoader())`?

**Comment by timja** [comment]
something like:
```
def configFile = new File(configPath)
if (configFile.exists()) {
  ConfigurationAsCode.get().configure(configFile)        
}
```

or, if  you just want  to reload:

```
ConfigurationAsCode.get().configure(configFile)        
```

**Comment by Rahaman148** [comment]
@timja 
```
def configFile = new File($CASC_JENKINS_CONFIG)
if (configFile.exists()) {
  ConfigurationAsCode.get().configure(configFile)        
}
```
It's complaining illegal argument exception  -

```
GitHub has been notified of this commit’s build result

java.lang.IllegalArgumentException: /var/lib/jenkins/casc_configs
	at org.jenkinsci.plugins.workflow.steps.EnvStep.<init>(EnvStep.java:52)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor383.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:330)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:269)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor653.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: java.lang.IllegalArgumentException: Could not instantiate {overrides=[/var/lib/jenkins/casc_configs]} for org.jenkinsci.plugins.workflow.steps.EnvStep
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:269)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor653.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:132)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:187)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by Rahaman148** [comment]
@timja 
when I used scripts like this it said AccessDenied but permission are there 755, I can't make that 777 because this is main server.

```
env.CASC_JENKINS_CONFIG='/var/lib/jenkins/casc_configs'
...................................................
.........................................................
...........................................................
withEnv(["$CASC_JENKINS_CONFIG=/var/lib/jenkins/casc_configs"]) {

		properties([
			parameters([
				booleanParam(name: 'jobsDsl', description: 'execute *.dsl job setup actions from automation-templates'),
				extendedChoice(name: 'cloud', type: 'PT_CHECKBOX', description: 'openstack cloud to build packer images on',
					value: "openstack-cloud", descriptionPropertyValue: "openstack-cloud.com", multiSelectDelimiter: ',', defaultValue: "openstack-cloud", visibleItemCount: -1),
			] + slave_label_choices)
		])

	}

writeFile file:"$CASC_JENKINS_CONFIG/openstack-cloud.yaml", text:yamlToString(yamlData)
def configFileLocation = ConfigurationAsCode.get().getSources()

ConfigurationAsCode.get().configure()

stage('Archive Artifact'){
    
    // Archive the build output artifacts.
    dir("$CASC_JENKINS_CONFIG")
    {
    archiveArtifacts artifacts: 'openstack-cloud.yaml', excludes: '$CASC_JENKINS_CONFIG/*.md'
    }
	}
}
}

def configFile = new File('$CASC_JENKINS_CONFIG/openstack-cloud.yaml')
if (configFile.exists()) {
  ConfigurationAsCode.get().configure(configFile)        
}
```
I don't know where I made mistake, here are the errors 
```
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to dynamic-packer-1521
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1071)
		at hudson.FilePath.act(FilePath.java:1060)
		at hudson.FilePath.write(FilePath.java:2088)
		at org.jenkinsci.plugins.workflow.steps.WriteFileStep$Execution.run(WriteFileStep.java:114)
		at org.jenkinsci.plugins.workflow.steps.WriteFileStep$Execution.run(WriteFileStep.java:98)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.nio.file.AccessDeniedException: /var/lib/jenkins
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
```

**Comment by timja** [comment]
it looks like you're trying to access a file on the master from an agent?

**Comment by Rahaman148** [comment]
@timja 

how can I make that happen? Any idea please

**Comment by timja** [comment]
can't you just publish it to a url that jenkins can retrieve it from and then trigger a reload?

**Comment by Rahaman148** [comment]
@timja 
I changed scripts please see below and it's keep complaining  -
```
		writeFile file:"openstack-cloud.yaml", text:yamlToString(yamlData)
	        archiveArtifacts artifacts: 'openstack-cloud.yaml'

		ConfigurationAsCode.get().configureWith(YamlSource.of(Paths.get(WORKSPACE,"openstack-cloud.yaml")))
```
It's keep complaining 

```
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml  in /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml, line 5, column 19:
      slaveAgentPort: 1024
                      ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:97)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:83)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:83)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:40)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:107)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:585)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:580)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:44)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:107)
```

**Comment by Rahaman148** [comment]
@timja 

Any suggestions please!

**Comment by Rahaman148** [comment]
@timja @ewelinawilkosz 
I used two approaches but none of them helped - 
1st Option with errors:
```
import io.jenkins.plugins.casc.ConfigurationAsCode
import io.jenkins.plugins.casc.yaml.YamlSource
import java.nio.file.Paths
import io.jenkins.plugins.casc.yaml.YamlUtils

WORKSPACE="/var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/"
def sources = []
new File("${WORKSPACE}/openstack-cloud.yaml").withReader { reader ->
  while ((line = reader.readLine()) != null) {
    sources.add(YamlSource.of(line));
    println "${line}"
  }
}

ConfigurationAsCode.get().configureWith(YamlSource.of(Paths.get(WORKSPACE,"openstack-cloud.yaml")))
```
errors -
```
io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml  in /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml, line 5, column 19:
      slaveAgentPort: 1024
                      ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:97)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:83)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:83)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:40)
Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/openstack-cloud.yaml
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:44)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:107)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:585)
```
2nd option with errors -
```
import io.jenkins.plugins.casc.ConfigurationAsCode
import io.jenkins.plugins.casc.yaml.YamlSource
import java.nio.file.Paths
import io.jenkins.plugins.casc.yaml.YamlUtils

WORKSPACE="/var/lib/jenkins/workspace/OCUS_automation-templates_PR-290/"
def sources = []
new File("${WORKSPACE}/openstack-cloud.yaml").withReader { reader ->
  while ((line = reader.readLine()) != null) {
    sources.add(YamlSource.of(line));
    println "${line}"
  }
}

//ConfigurationAsCode.get().configureWith(YamlSource.of(Paths.get(WORKSPACE,"openstack-cloud.yaml")));
ConfigurationAsCode.get().configureWith(YamlUtils.loadFrom(sources))
```
errors -
```
java.net.URISyntaxException: Expected scheme-specific part at index 8: jenkins:
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parse(URI.java:3057)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
Caused: java.lang.IllegalArgumentException: Expected scheme-specific part at index 8: jenkins:
	at java.net.URI.create(URI.java:852)
	at io.jenkins.plugins.casc.yaml.YamlSource.lambda$static$0(YamlSource.java:22)
	at io.jenkins.plugins.casc.yaml.YamlSource.read(YamlSource.java:65)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:32)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:107)
	at io.jenkins.plugins.casc.yaml.YamlUtils$loadFrom.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
```
really don't know what exactly happen and how to fix that? Any help will be highly appreciated thanks

**Comment by timja** [comment]
You didn’t answer this
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1067#issuecomment-532358147
