### ISSUE TITLE
How to configure sonarqube plugin?

### ISSUE THREAD

**Issue by marcelaraujo** [jenkinsci/configuration-as-code-plugin#1159]
### Your checklist for this issue

- [X] Jenkins 1.299
- [X] Plugin 1.32
- [X] OS Linux

### Description

Jenkins stop running after update Jasc plugin from 1.30 to 1.32

```
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.890+0000 [id=19] SEVERE  hudson.util.BootFailure#publish: Failed to initialize Jenkins
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: io.jenkins.plugins.casc.ConfiguratorException: home is required to configure class hudson.plugins.sonar.SonarRunnerInstallation
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:133)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:267)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:344)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:716)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:666)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: Caused: io.jenkins.plugins.casc.ConfiguratorException: tool: error configuring 'tool' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:672)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:716)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:701)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:592)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:281)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:273)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: Caused: java.lang.reflect.InvocationTargetException
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at java.lang.reflect.Method.invoke(Method.java:498)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: Caused: java.lang.Error
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at jenkins.model.Jenkins$5.runTask(Jenkins.java:1124)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at java.lang.Thread.run(Thread.java:748)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: Caused: org.jvnet.hudson.reactor.ReactorException
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at jenkins.model.Jenkins.executeReactor(Jenkins.java:1158)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at jenkins.model.Jenkins.<init>(Jenkins.java:965)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.model.Hudson.<init>(Hudson.java:85)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.model.Hudson.<init>(Hudson.java:81)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.WebAppMain$3.run(WebAppMain.java:233)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: Caused: hudson.util.HudsonFailedToLoad
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]:      at hudson.WebAppMain$3.run(WebAppMain.java:250)
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.901+0000 [id=19] INFO    jenkins.model.Jenkins#cleanUp: Stopping Jenkins
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.955+0000 [id=19] INFO    jenkins.model.Jenkins$18#onAttained: Started termination
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.973+0000 [id=19] INFO    jenkins.model.Jenkins$18#onAttained: Completed termination
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.973+0000 [id=19] INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.981+0000 [id=19] INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:27.990+0000 [id=19] INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:28.015+0000 [id=19] INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
jenkins/jenkins-5ccbd694d7-rr5jd[jenkins]: 2019-10-12 14:56:28.019+0000 [id=19] INFO    jenkins.model.Jenkins#cleanUp: Jenkins stopped
```

Where should I put `home` property? 

My Sonar Installation block is this

```
sonar-runner: |
        tool:
          sonarRunnerInstallation:
            installations:
            - name: "sonar-scanner-default"
              properties:
              - installSource:
                  installers:
                  - sonarRunnerInstaller:
                      id: "4.2.0.1873" # Version got from Maven Central
```

Thanks guys

**Comment by timja** [comment]
I believe it's this:
```
          sonarRunnerInstallation:
            installations:
            - name: "sonar-scanner-default"
              home: ""
              properties:
              - installSource:
                  installers:
                  - sonarRunnerInstaller:
                      id: "4.2.0.1873" # Version got from Maven Central
```

There's a PR to fix it here though:
https://github.com/SonarSource/sonar-scanner-jenkins/pull/124
