### ISSUE TITLE
Credential get's FAILED TO EXPORT error when creating a new jenkins container

### ISSUE THREAD

**Issue by DavidRodHub** [jenkinsci/configuration-as-code-plugin#1267]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version:  2.204.2
- [x] Plugin version    1.35
- [x] OS:  Ubuntu 18.04

### Description

Please describe your issue here:

Credential get's FAILED TO EXPORT error when creating a new jenkins container with configuration-as-code plugin and jenkins.yaml file.  After Reloading the  existing configuration,  the credentials displays correctly

Reproduce.
1. Create jenkins docker container with plugin and jenkins.yaml file
2. Go tor https://jenkins-upgrade.mycom-osi.com/configuration-as-code/
3. Select Action : View Configuration

Get the following for error for 'Credentials"
```
credentials:
  system:
    domainCredentials:
    - credentials: |-
        **FAILED TO EXPORT
        com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials: java.lang.IllegalArgumentException: argument type mismatch**
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:299)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:283)
          at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:283)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
          at io.vavr.control.Option.map(Option.java:392)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
          at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:320)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:249)
          at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:307)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:320)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:249)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)
          at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)
          at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:320)
          at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:256)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)
          at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)
```

4. Reload the existing configuration.  The credentials displays correctly.

```
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "Private key credentials for Jenkins GitLab user"
          id: "gitlab-key"
          privateKeySource:
            directEntry:
              privateKey: "{ABAAAAAw7bNBhaX0+UAlXmam/iH2NZX3klyr4hMFwMIXEeZqJbqd7YRXf2i8V3wmA==}"
          scope: GLOBAL
          username: "jenkins"
```

**Comment by casz** [comment]
Which credentials do you have configured?
What version of credential plugin?
Again this is most likely a plugin issue.

**Comment by casz** [comment]
This is already reported as: [JENKINS-58249](https://issues.jenkins-ci.org/browse/JENKINS-58249)

**Comment by casz** [comment]
@p4paul

**Comment by DavidRodHub** [comment]
Hi casz.   Thanks for your quick support.  I figured out my problem.... Me :)   In the credential example given below  it says "Load from Environment Variable". It means what it says.  My environment variable wasn't set correctly.  After I fixed that, it worked flawlessly..... Thanks!

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "basic-SSH"
              username: "ssh-username"
              passphrase: "" #Doable, but not recommended
              description: "SSH Credentials for ssh-username"
              privateKeySource:
                directEntry:
                  **privateKey: ${SSH_PRIVATE_KEY} #Load from Environment Variable**
