### ISSUE TITLE
[JENKINS-56774] not able to set per project based settings in authorize-project-plugin

### ISSUE THREAD

**Issue by choeffer** [jenkinsci/configuration-as-code-plugin#1278]
[jenkins-jira]: https://issues.jenkins-ci.org/browse/JENKINS-56774
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [x] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [x] Link to [Jenkins JIRA issue][jenkins-jira]

- [x] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to plugin's GitHub repository
https://github.com/jenkinsci/authorize-project-plugin

### Description

Defining

```
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
```

in jenkins.yaml enables to configure

![image](https://user-images.githubusercontent.com/33625292/74912280-a6781280-53be-11ea-9faa-5cc2263f5918.png)

But it is not possible to configure project based settings

![image](https://user-images.githubusercontent.com/33625292/74913034-22bf2580-53c0-11ea-8841-b3012e74967e.png)

via this pseudocode

```
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: "triggeringUsersAuthorizationStrategy"
    - project:
        strategyEnabledMap:
        - string: SpecificUsersAuthorizationStrategy
          boolean: true
        - string: TriggeringUsersAuthorizationStrategy
          boolean: true
        - string: SystemAuthorizationStrategy
          boolean: false
        - string: AnonymousAuthorizationStrategy
          boolean: true
```

The following error is thrown when Jenkins starts

```
java.lang.IllegalStateException: No configurator implementation to manage class org.jenkinsci.plugins.authorizeproject.ProjectQueueItemAuthenticator
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$forceLookupConfigurator$8(HeteroDescribableConfigurator.java:137)
	at io.vavr.control.Option.getOrElseThrow(Option.java:351)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.forceLookupConfigurator(HeteroDescribableConfigurator.java:137)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$1(HeteroDescribableConfigurator.java:85)
	at io.vavr.control.Option.map(Option.java:392)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:85)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:344)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:746)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:696)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:746)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:731)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:611)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:292)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:284)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
```

JCasC is aware of `project` and `global`

![image](https://user-images.githubusercontent.com/33625292/74913385-cad4ee80-53c0-11ea-80b2-6df6eb94f54b.png)

The generated xml contains

```
cat /var/jenkins_home/jenkins.security.QueueItemAuthenticatorConfiguration.xml 
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.security.QueueItemAuthenticatorConfiguration>
  <authenticators>
    <org.jenkinsci.plugins.authorizeproject.GlobalQueueItemAuthenticator plugin="authorize-project@1.3.0">
      <strategy class="org.jenkinsci.plugins.authorizeproject.strategy.TriggeringUsersAuthorizationStrategy"/>
    </org.jenkinsci.plugins.authorizeproject.GlobalQueueItemAuthenticator>
    <org.jenkinsci.plugins.authorizeproject.ProjectQueueItemAuthenticator plugin="authorize-project@1.3.0">
      <strategyEnabledMap>
        <entry>
          <string>org.jenkinsci.plugins.authorizeproject.strategy.SpecificUsersAuthorizationStrategy</string>
          <boolean>true</boolean>
        </entry>
        <entry>
          <string>org.jenkinsci.plugins.authorizeproject.strategy.TriggeringUsersAuthorizationStrategy</string>
          <boolean>true</boolean>
        </entry>
        <entry>
          <string>org.jenkinsci.plugins.authorizeproject.strategy.SystemAuthorizationStrategy</string>
          <boolean>false</boolean>
        </entry>
        <entry>
          <string>org.jenkinsci.plugins.authorizeproject.strategy.AnonymousAuthorizationStrategy</string>
          <boolean>true</boolean>
        </entry>
      </strategyEnabledMap>
    </org.jenkinsci.plugins.authorizeproject.ProjectQueueItemAuthenticator>
  </authenticators>
</jenkins.security.QueueItemAuthenticatorConfiguration>
```

Any ideas for a workaround which is better than copying over a .xml file? 

Can this be solved here or has the plugin itself to be updated?

I think a fix/workaround for this is important, because a fresh installed jenkins is showing a warning and suggests to install this plugin.

![image](https://user-images.githubusercontent.com/33625292/74914961-acbcbd80-53c3-11ea-8040-0a00c8aac17c.png)

**Comment by choeffer** [comment]
still persists with Jenkins ver. 2.222.3 and Configuration as Code Plugin ver. 1.40.

**Comment by timja** [comment]
This is an issue with the authorize-project plugin and not JCasC, see https://github.com/jenkinsci/authorize-project-plugin/pull/44
