### ISSUE TITLE
Failure to download schema on CloudBees Core distribution

### ISSUE THREAD

**Issue by jmMeessen** [jenkinsci/configuration-as-code-plugin#1320]
Hello,

I am trying to use the plugin with a CloudBees Core for Traditional  Platforms Master and have no success.
The version is 2.204.1.3
Note: the download works with an OSS Jenkins.

The schema download fails. On the console I get the attached errors. At first sight, the problem is not coming from proprietary code.

/- Jmm
[JCasC bug.txt](https://github.com/jenkinsci/jcasc-vscode-extension/files/4330741/JCasC.bug.txt)

**Comment by timja** [comment]
The vscode plugin just downloads the schema, moved to main repo,

cc @oleg-nenashev

**Comment by oleg-nenashev** [comment]
@jmMeessen Hi. Could you please follow the issue template and provide a version of JCasC you are using? 

Error from the provided log, there is an NPE during schema generation. From what I see, it is an edge case in https://github.com/jenkinsci/configuration-as-code-plugin/commit/6ab460cb5a0aed7c495e50b69eae0ac80876f59e which was my fix for another NPE issue.

```
	at org.apache.commons.jelly.XMLOutput.flush(XMLOutput.java:127)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	... 64 more
Also:   java.lang.NullPointerException
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
		at jenkins.model.Jenkins.getDescriptorList(Jenkins.java:2670)
		at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.getDescriptors(HeteroDescribableConfigurator.java:171)
		at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.getImplementors(HeteroDescribableConfigurator.java:122)
		at io.jenkins.plugins.casc.SchemaGeneration.generateHeteroDescribableConfigObject(SchemaGeneration.java:86)
		at io.jenkins.plugins.casc.SchemaGeneration.generateSchema(SchemaGeneration.java:73)
		at io.jenkins.plugins.casc.SchemaGeneration.writeJSONSchema(SchemaGeneration.java:81)
		at io.jenkins.plugins.casc.ConfigurationAsCode.doSchema(ConfigurationAsCode.java:433)
		at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
		at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
		at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
		at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
		at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
```

**Comment by oleg-nenashev** [comment]
@jmMeessen Hi. Are you still interested?

**Comment by umlublin** [comment]
Same error in Jenkins 2.222.3, CasC plugin 1.40

**Comment by umlublin** [comment]
in HeteroDescribableConfigurator.getDescriptors()
![image](https://user-images.githubusercontent.com/23502341/82043618-31119a80-96ac-11ea-8fe9-ffbf28029001.png)
target.getSuperclass() is null because target is an interface
i added '&& effectiveTarget != null' to while condition and just works good :)

**Comment by timja** [comment]
can you send a PR with that please?

**Comment by umlublin** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1387
