### ISSUE TITLE
Can't create Seed Jobs

### ISSUE THREAD

**Issue by benkeil** [jenkinsci/configuration-as-code-plugin#134]
I tried your example and got the following exception:

```
Mar 05, 2018 9:03:14 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:47)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1099)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1065)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: java.lang.IllegalArgumentException: Invalid configuration elements for type class hudson.model.Hudson : jobs
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:173)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:33)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:16)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:47)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:35)
	... 13 more
```

**Comment by ewelinawilkosz** [comment]
can you provide your yaml Ben?

**Comment by MadsNielsen** [comment]
@benkeil Okay i tried the example from the readme: 

```
jobs:
  - >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
```
This works fine, did you remember to add it as a root element in the .yaml?

IE:
```
jenkins: 
 [...]
jobs:
  - >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }
```

**Comment by benkeil** [comment]
jenkins.yaml:

`jenkins:
  globalLibraries:
    libraries:
      - name: "deployment"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "git@git.xxx/jenkins-deploy-library.git"
  mailer:
    adminAddress: jenkins@xxx
    replyToAddress: tech-team@xxx
    smtpHost: blackhole.xxx
    smtpPort: 25
  location:
    url: http://jenkins.xxx
  clouds:
    - kubernetes:
        name: kubernetes
        skipTlsVerify: 
        containerCapStr: 100
        jenkinsUrl: http://jenkins.xxx
  jobs:
    - >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }`

**Comment by MadsNielsen** [comment]
@benkeil Yo'll need to fix the indentiation in your example :-)

**Comment by benkeil** [comment]
one moment, there went something wrong ^^

**Comment by casz** [comment]
you have to use triple backticks 👍 you are only using single backticks

**Comment by MadsNielsen** [comment]
@benkeil Your `jobs:` section is not indented correctly, it's a root element like jenkins.

**Comment by benkeil** [comment]
the build was to old, it works...
