### ISSUE TITLE
enabling managehooks settings through DSL CasC does not work

### ISSUE THREAD

**Issue by dsakilesh** [jenkinsci/configuration-as-code-plugin#1440]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ x ] Jenkins version -- Jenkins 2.235.1

- [ x ] Plugin version -- Bitbucket Branch source 2.8.0

- [ x ] OS -- Linux

### Description

We have jenkins.yaml where we have all the jenkins global configurations. When we enable the manageHooks settings by making it "true" the same is not getting applied in JenkinsGUI. We are getting the below error, when we restart the jenkins instance.

```
java.lang.IllegalArgumentException: No enum constant com.cloudbees.jenkins.plugins.bitbucket.server.BitbucketServerWebhookImplementation.Plugin
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.kohsuke.stapler.Stapler$6.convert(Stapler.java:1144)
	at io.jenkins.plugins.casc.impl.configurators.PrimitiveConfigurator.configure(PrimitiveConfigurator.java:45)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:276)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:277)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:277)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$2(HeteroDescribableConfigurator.java:86)
	at io.vavr.control.Option.map(Option.java:392)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:86)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:344)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1164)
	at jenkins.model.Jenkins.<init>(Jenkins.java:964)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:262)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:279)
```

We are using Atlassian Bitbucket v5.8.2

Let me know if you need more details.

Kindly help us fix the issue. Thanks in advance!

Regards,
Akilesh D S

**Comment by jetersen** [comment]
This not a JCasC problem. Rather it is a bitbucket branch source plugin problem.
Though sharing your config will be helpful. To understand the problem.

**Comment by dsakilesh** [comment]
Hi @jetersen 

Please find below the jenkins.yaml configuration.

```
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketServerEndpoint:
          displayName: "xxx.com"
          manageHooks: true
          serverUrl: "https://xxx.com/bitbucket"
          webhookImplementation: NATIVE
```

We are not facing this issue when we enable it via Jenkins WebGUI. We are getting this error only when changing the value of manageHooks from false to  true and restarting the Jenkins.

Thanks in advance!

Regards,
Akilesh D S

**Comment by jetersen** [comment]
if you configure through you and export it how does it show?

**Comment by dsakilesh** [comment]
It shows true in CasC with viewExport when i makes changes via UI.

unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketServerEndpoint:
          credentialsId: "XXXXXXXXX"
          displayName: "xxx.com"
          manageHooks: true
          serverUrl: "https://xxx.com/bitbucket"

Thanks!

Regards,
Akilesh D S

**Comment by jetersen** [comment]
Hmm I'll explore why it fails to export and configure correctly.

**Comment by bitwiseman** [comment]
@jetersen  "Plugin" is the display name, "PLUGIN" is the enum value.   Could that be the problem?

**Comment by bitwiseman** [comment]
@jetersen  
I have not been able to reproduce this issue using `mvn hpi:run`. 
Configurations:
* Jenkins 2.138.4 with JCasC 1.30 
* Jenkins 2.222.3 with JCasC 1.41

@dsakilesh 
Could you describe in more details how you are getting this error.  Please go step by step.

**Comment by jetersen** [comment]
@bitwiseman he wants to `NATIVE` option and not the `PLUGIN` option

**Comment by jetersen** [comment]
Seeing some deserialize errors though it definitely seems like JCasC is able to consume the enum. Though I suggest adding a native and plugin endpoint to the [`should_support_configuration_as_code`](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/ce0030a21a16fab9979bf76d4d9ebd1f0d32c8c7/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java#L645) in bitbucket branch source

```
3.665 [id=25]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class com.cloudbees.jenkins.plugins.bitbucket.server.BitbucketServerWebhookImplementation$1 in file:/C:/git/code/bitbucket.branch.source.plugin/target/classes/; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
3.665 [id=25]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class com.cloudbees.jenkins.plugins.bitbucket.server.BitbucketServerWebhookImplementation$2 in file:/C:/git/code/bitbucket.branch.source.plugin/target/classes/; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```

**Comment by jetersen** [comment]
@bitwiseman could be hpi:run class loading tricking you.

but ya I am not able to recreate it. Would have to wait for feedback before digging deeper.

**Comment by bitwiseman** [comment]
@jetersen 
#332 now also includes a fix for the `anonymous class` warning above.

**Comment by dsakilesh** [comment]
@jetersen and @bitwiseman 

I have tried with **webhookImplementation: Plugin** option also.

Should i use **PLUGIN** instead of **Plugin** in the above line?

When i checked in the GUI **Plugin** was in lower case

Thanks in advance!

Regards,
Akilesh

**Comment by dsakilesh** [comment]
@jetersen @bitwiseman 

Thanks for the investigation

the below code worked without any issues. Culprit was the lowercase. my bad:(

```
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketServerEndpoint:
          credentialsId: "XXXXXX"
          displayName: "xxx.com"
          manageHooks: true
          serverUrl: "https://xxx.com/bitbucket"
          webhookImplementation: PLUGIN
```
It did not even require restart of Jenkins. 

Just one question what would be the traits configuration for the trigger build by commit functionality in DSL groovy?

```
...
traits << 'jenkins.plugins.git.traits.LocalBranchTrait' {
            extension(class: 'hudson.plugins.git.extensions.impl.LocalBranch') {
                LocalBranchTrait()
            }
       
        it / 'triggers' << 'com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger'{
            spec '* * * * *'
            interval "60000"
        }
```
The above one is periodic buid but we need similar configuration for trigger by bitbucket commit.

Thanks in advance!

Regards,
Akilesh D S

**Comment by bitwiseman** [comment]
@dsakilesh  Yeah, capitalization matters. 
I don't understand your secondary question, but it would probably be better asked on gitter.im. 

This issue can be closed.
