### ISSUE TITLE
Found conflicting configuration at YamlSource

### ISSUE THREAD

**Issue by nightspotlight** [jenkinsci/configuration-as-code-plugin#1479]
- [x] Jenkins version: 2.249.1

- [x] Plugin version: 1.43

- [x] OS: Red Hat Enterprise Linux Server 7.8 (Maipo)

### Description

The plugin seems to fail to merge duplicate keys.

```
16:18:07 FATAL: Failed to read YamlSource: /var/lib/jenkins/jcasc/config-80-plugin_prefs.yml
16:18:07 io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/lib/jenkins/jcasc/config-80-plugin_prefs.yml  in /var/lib/jenkins/jcasc/config-80-plugin_prefs.yml, line 4, column 20:
16:18:07         logBuildCause: True
16:18:07                        ^
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:139)
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:125)
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:52)
16:18:07 Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/lib/jenkins/jcasc/config-80-plugin_prefs.yml
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:56)
16:18:07 	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:150)
16:18:07 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
16:18:07 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
16:18:07 	at io.jenkins.plugins.casc.ConfigurationAsCode$configure$0.call(Unknown Source)
16:18:07 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
16:18:07 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
16:18:07 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
16:18:07 	at Script1.run(Script1.groovy:1)
16:18:07 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
16:18:07 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
16:18:07 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
16:18:07 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:377)
16:18:07 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:314)
16:18:07 	at hudson.plugins.groovy.SystemGroovy.run(SystemGroovy.java:95)
16:18:07 	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:59)
16:18:07 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:18:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
16:18:07 	at hudson.model.Build$BuildExecution.build(Build.java:206)
16:18:07 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
16:18:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
16:18:07 	at hudson.model.Run.execute(Run.java:1894)
16:18:07 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:18:07 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:18:07 	at hudson.model.Executor.run(Executor.java:428)
16:18:07 Finished: FAILURE
```

There is the same key in two different files:

```
$ sudo grep -ir -- 'logBuildCause:' /var/lib/jenkins/jcasc/
/var/lib/jenkins/jcasc/01-jenkins.yml:    logBuildCause: true
/var/lib/jenkins/jcasc/config-80-plugin_prefs.yml:    logBuildCause: True
```

I was expecting the plugin to merge the key if it encountered multiple instances of it, judging by the name of the method (YamlUtils.merge)

The method to apply the config is `systemGroovyCommand ("io.jenkins.plugins.casc.ConfigurationAsCode.get().configure()")`

**Comment by nightspotlight** [comment]
possibly related to #653

**Comment by jetersen** [comment]
JCasC does not perform deep merge.

**Comment by nightspotlight** [comment]
wrote a script to merge the configs into a single YAML file before feeding it to Jcasc. now it applies without a hitch

**Comment by UkonnRa** [comment]
I get the same issue when using the Jenkins Helm Chart. There are several kinds of JCasC Config files, some from the template self (default configs), some from users (custom configs). So if one field is referred in the default configs, the others referred the same field will be conflict
