### ISSUE TITLE
Fix the Dockerfile on the repo root

### ISSUE THREAD

**Issue by batmat** [jenkinsci/configuration-as-code-plugin#149]
Hello, 
I just tried `mvn clean package && docker build -t casc && docker run -p 8080:8080 casc`, and I hit the following error:

```
Mar 14, 2018 2:35:41 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 14, 2018 2:35:41 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Configuration as Code Plugin v0.2-alpha-SNAPSHOT (private-80c95e46-tiste) (configuration-as-code)
java.io.IOException: Configuration as Code Plugin v0.2-alpha-SNAPSHOT (private-80c95e46-tiste) failed to load.
 - workflow-multibranch v2.9.2 is missing. To fix, install v2.9.2 or later.
 - job-dsl v1.66 is missing. To fix, install v1.66 or later.
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:513)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Mar 14, 2018 2:35:43 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 14, 2018 2:35:43 PM jenkins.InitReactorRunner$1 onAttained
```

I guess the `Dockerfile` should either be fixed, or removed?

Maybe it relates or is a dupe for #3 but I was not totally sure.

Thanks!

**Comment by batmat** [comment]
cc @ndeloof as you authored those for milestone1.

**Comment by ndeloof** [comment]
We'd like to have job-dsl as an optional dependency: https://github.com/jenkinsci/configuration-as-code-plugin/issues/144
