### ISSUE TITLE
Be able to set "Workspace Root Directory" and "Build Record Root Directory"

### ISSUE THREAD

**Issue by batmat** [jenkinsci/configuration-as-code-plugin#151]
I would like to set the two advanced attributes (usually found under `/configure):

![image](https://user-images.githubusercontent.com/223853/37566440-7bde2490-2ab9-11e8-9d88-2e0e0ad20c08.png)

I have tried the following:

```yaml
jenkins:
  rawBuildsDir: "${JENKINS_HOME}/var/${ITEM_FULL_NAME}/builds"
```

But with this I get the following error and stack trace:

```
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Invalid configuration elements for type class hudson.model.Hudson : rawBuildsDir
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:185)
        at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:47)
        at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:129)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:109)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:95)
        ... 13 more

Mar 18, 2018 12:50:11 PM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
        at jenkins.model.Jenkins.executeReactor(Jenkins.java:1098)
        at jenkins.model.Jenkins.<init>(Jenkins.java:900)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Invalid configuration elements for type class hudson.model.Hudson : rawBuildsDir
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:185)
        at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:47)
        at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:129)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:109)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:95)
        ... 13 more

Mar 18, 2018 12:50:11 PM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
```

I was initially surprised by `rawBuildsDir`, and thought it could be the cause, because this attribute is indeed defined only in `Jenkins` (which `Hudson` now inherits from). But I guess no, since this is the same for `numExecutors` and this works...

Any idea if this is a bug, or that I'm misusing the plugin?

Thanks!

**Comment by ewelinawilkosz** [comment]
you're not misusing for sure, seems to be a bug
there is no entry in the documentation, at the same time there are entries for numExecutors or systemMessage so there must be something special about those two fields... I wonder if the fact they are under "Advanced" make any difference, probably shouldn't :/

**Comment by daniel-beck** [comment]
This should only be supported as long as there's no way casc plugin would change the value at runtime. While it's a UI option, it's not actually safe to use.

**Comment by batmat** [comment]
I think this is working as designed. https://github.com/jenkinsci/configuration-as-code-plugin/blob/7b8c80b68f6486d3ea51f401c29380e6fc2bd61c/src/main/java/org/jenkinsci/plugins/casc/BaseConfigurator.java#L45

I think we need to add more loggers though, so that it's debuggable if needed. Going to file a PR for this.

**Comment by MadsNielsen** [comment]
@batmat Yeah you're right, the setter for rawBuildsDir is `@Restricted` in source so this is working as designed. I can follow @daniel-beck comments on the multitude of things that could go wrong if this is changed while jobs are running. 

So, we either close it as: `Won't fix` or come up with a way to support this usecase. 

We could introduce an `experimental` or `insecure` option that would skip this check in casc, or we add a workaround in the core itself. I'm mostly for closing it as `Won't fix` because it sounds like @daniel-beck strongly discourages the use of this functionality even through the UI.

**Comment by ndeloof** [comment]
@batmat the CasC design is based on building a data model for live jenkins instance, so to `describe` each component and attributes then `process` the incoming YAML to `configure` Jenkins.
The fact `@Restricted` attribute isn't logged is expected, those are excluded from the model description. I agree the diagnostic capability is pretty poor so far and need to be improved.

**Comment by ndeloof** [comment]
considering this specific issue, `rawBuildsDir` setter should not have been marked `@Restricted` as it is exposed to data-binding, so actually exposed as a configurable attribute.
https://github.com/jenkinsci/jenkins/commit/7f4014c74047d96b1557eae09d06853fd841beb4

CasC happens to be a very efficient design weakness detector

**Comment by oleg-nenashev** [comment]
We've been discussing an option support **opt-in** "ignore-Restricted" behavior. And anyway, this case will require some better diagnostics. It's closely related to #233 

@ndeloof  If you do not mind, I will reopen it for now and assign to myself to come up with a design

**Comment by ndeloof** [comment]
I tend to disagree with options that allow Jenkins to go on with design issues.
Anyway not being alone onboard feel free to work on this issue if you think it would make sense.

**Comment by ndeloof** [comment]
We got an important feedback from @daniel-beck :

> This should only be supported as long as there's no way casc plugin would change the value at runtime. While it's a UI option, it's not actually safe to use.

CasC is designed to set value any time configuration is applied, there's no such thing like an "_only once_" attribute to be set. But on the other side there's nothing in Jenkins to prevent this to happen by submitting from web UI, what would happen then ? Lost or corrupted build data ?

**Comment by batmat** [comment]
Well though I understand @daniel-beck's point, and agree we shouldn't encourage people to change this value every mornings, *anyway* people can still change the sysprop and change it. 

Anyway again, I agree this feature cannot be supported right now by CasC alone. I have a way in mind since some time to make this more feasible, but it has to land into the core before. So that then CasC can set it.

**Comment by batmat** [comment]
Closing for now for the previous reason.

**Comment by ashb** [comment]
For anyone finding this issue and wondering how to do this: You need to set a system property of `jenkins.model.Jenkins.workspacesDir`. 

The easiest way of doing this is to set this on the command line:

```
java -Djenkins.model.Jenkins.workspacesDir='/mnt/large/jenkins-workspace/${ITEM_FULL_NAME}' -jar /usr/share/jenkins/jenkins.war
```

Most ways of running Jenkins (rpm/deb package, docker container etc) have a way of setting JAVA_OPTS so (look in /etc/default or /etc/sysconfig, or an env var to the docker container) depending on which platform you are running on.

(I'm not using CasC directly but was looking to configure from goovy init scripts, which is how I found this issue)

**Comment by ndeloof** [comment]
@ashb you can configure such attribute with JCasC is you enable access to restricted elements:
```yaml
configuration-as-code:
   restricted: warn
```

but you indeed can also use system properties in few places where some additional configuration option has been included by developers.

**Comment by tjanson** [comment]
@ndeloof I’m quite surprised that that indeed works for `rawBuildsDir`. I was unaware of the `restricted` attribute. It does not work for `workspacesDir` nor `rawWorkspaceDir`.

I’m curious how this works under the hood: my first guess is that `rawBuildsDir` is capitalized and appended to `set`, then `setRawBuildsDir` of `jenkins.model.Jenkins` is looked up and called?
(The actual property is called `buildsDir` not `rawBuildsDir`.)

Any idea how I can set the workspaces dir via CasC?

**Comment by casz** [comment]
@tjanson there is no setter for workspaceDir, there is a getter for called: `getRawWorkspaceDir`

You have to use: `-Djenkins.model.Jenkins.workspacesDir` as noted by code here
https://github.com/jenkinsci/jenkins/blob/17d45ff1ae22a961dedb0b914ffd7ecdfadff005/core/src/main/java/jenkins/model/Jenkins.java#L3090

**Comment by tjanson** [comment]
@casz Thanks. So just out of curiosity, was my hunch correct that CasC uses reflection to look up setters, or something to that effect?

More concretely: How can I find out what other properties can be set in the same way as `rawBuildsDir`? They don’t show up in the generated CasC reference page. Can I just look at the classes in the `jenkins.model` package and look for setters with the `@Restricted` annotation?
