### ISSUE TITLE
Not able to configure OpsGenie Plugin with JCasC

### ISSUE THREAD

**Issue by mhubig** [jenkinsci/configuration-as-code-plugin#1545]
[jenkins-jira]: https://issues.jenkins-ci.org
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [ ] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against
**Sorry I have no Account there, so I'm not able to create an issue on [issues.jenkins-ci.org][jenkins-jira].**

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]
**It seems there is no existing Issue for the OpsGenie Plugin.**

- [ ] Link to [Jenkins JIRA issue][jenkins-jira]
**Sorry I have no Account at [issues.jenkins-ci.org][jenkins-jira].**

- [ ] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`
**Sorry I have no Account at [issues.jenkins-ci.org][jenkins-jira].**

- [ ] Link to plugin's GitHub repository
https://github.com/jenkinsci/opsgenie-plugin

### Description

Im using
* Jenkins 2.263.1
* configuration-as-code:1.46
* opsgenie:1.9

I can't configure the OpsGenie Plugin with JCasC. I tried this so far:

```yaml
unclassified:
  opsGenieNotifier:
    apiUrl: https://api.opsgenie.com
    apiKey: "${JENKINS_OPSGENIE_API_KEY}"
    teams: MyTeam
    tags: jenkins
```

Which failed with this error:

```java
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class com.opsgenie.integration.jenkins.OpsGenieNotifier$DescriptorImpl : apiUrl,apiKey,teams,tags.
Available attributes : 
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:376)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:365)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:697)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1164)
	at jenkins.model.Jenkins.<init>(Jenkins.java:964)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:295)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:312)
```

**Comment by jetersen** [comment]
I tried to make a fix for opsgenie but ran into a security issue that is still awaits a fix.

**Comment by mhubig** [comment]
Is there anything I can help with? Unfortunately I'm not able to file an issue within the opsgenie plugin repo directly ... At the moment opsgenie is the only manual configuration I have in my jenkins server, everything else is handled by JCasc!

**Comment by jetersen** [comment]
Jenkins Security have tried to reach out to OpsGenie maintainers but no response.

**Comment by mhubig** [comment]
Just for reference, I found an easy workaround by storing the opsgenie apiKey as a secret credential and then passing it as an parameter directly to the `opsgenie()` call like this:

```yaml
credentials:
  system:
    domainCredentials:
      - domain:
          name: myDomain
        credentials:
        - string:
            scope: GLOBAL
            id: opsgenie-api-key
            secret: "${JENKINS_OPSGENIE_API_KEY}"
            description: OpsGenie API Access Key
```

```groovy
pipeline {
  agent any
  stages {
    stage('Test') {
      steps {
        sh 'exit 0'
      }
    }
  }
  post {
    always {
      withCredentials([string(credentialsId: 'opsgenie-api-key', variable: 'apiKey')]) {
        opsgenie(apiUrl: 'https://api.opsgenie.com', apiKey: apiKey, teams: 'myTeam', tags: 'jenkins')
      }
    }
  }
}
```
