### ISSUE TITLE
LDAP configuration not working

### ISSUE THREAD

**Issue by gerry-christiansen** [jenkinsci/configuration-as-code-plugin#1552]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version
- 2.275

- [ X] Plugin version
  LDAP 2.3

- [ X] OS
 Linux 

### Description

Please describe your issue here.

So if I use the CasC plugin to configure my LDAP security realm, I get the following during login/test of ldap setup.

```
2021-01-15 20:20:03.602+0000 [id=15]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 5d691b8f-cb02-4044-aaf1-1e6c4bee82d5
org.springframework.security.authentication.DisabledException: The user "null" is administratively disabled.
	at hudson.security.UserAttributesHelper.checkIfUserEnabled(UserAttributesHelper.java:97)
	at hudson.security.LDAPSecurityRealm$LDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1314)
	at hudson.security.LDAPSecurityRealm$DelegateLDAPUserDetailsService.loadUserByUsername(LDAPSecurityRealm.java:1227)
	at hudson.security.LDAPSecurityRealm.loadUserByUsername2(LDAPSecurityRealm.java:762)
	at jenkins.security.UserDetailsCache$Retriever.call(UserDetailsCache.java:165)
	at jenkins.security.UserDetailsCache$Retriever.call(UserDetailsCache.java:154)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
Caused: com.google.common.util.concurrent.UncheckedExecutionException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2234)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
	at jenkins.security.UserDetailsCache.loadUserByUsername(UserDetailsCache.java:122)
	at hudson.model.User$UserIDCanonicalIdResolver.resolveCanonicalId(User.java:1241)
	at hudson.model.User$CanonicalIdResolver.resolve(User.java:1182)
	at hudson.model.User.get(User.java:516)
	at hudson.model.User.getOrCreateByIdOrFullName(User.java:579)
	at hudson.model.User.get(User.java:560)
	at hudson.security.LDAPSecurityRealm.updateUserDetails(LDAPSecurityRealm.java:778)
	at hudson.security.LDAPSecurityRealm.updateUserDetails(LDAPSecurityRealm.java:772)
	at hudson.security.LDAPSecurityRealm.updateUserDetails(LDAPSecurityRealm.java:766)
	at hudson.security.LDAPSecurityRealm$LDAPAuthenticationManager.authenticate(LDAPSecurityRealm.java:994)
	at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:85)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:222)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

If I make a change in the UI and save the new change to the ldap configuration, then the LDAP login starts working...

**Comment by jetersen** [comment]
Can you share your config. Seems like a config error and not a bug.

**Comment by timja** [comment]
> DisabledException: The user "null" is administratively disabled

seems like your user isn't be passed through

**Comment by gerry-christiansen** [comment]
Joeseph,

Thank you for responding and work on this plugin.  It is an awesome project!  It’s not a configuration error as the exact same configuration file is used in Jenkins LTS version (2.263.2) and it works fine.  Seems to be specific to the latest version 2.275

Below is a redacted copy of my config yaml file.

unclassified:
  location:
    url: "http://myhost.mydomain.com:8080/"
    adminAddress: "admin@mydomain.com"
jenkins:
  proxy:
    name: "http.proxy.mydomain.com"
    port: 8000
    noProxyHost: "*.mydomain.com"
    testUrl: "http://google.com"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Agent/Build:ADGroupA"
        - "Credentials/Create:ADGroupA"
        - "Credentials/Update:ADGroupA"
        - "Credentials/View:authenticated"
        - "Job/Build:ADGroupA"
        - "Job/Cancel:ADGroupA"
        - "Job/Configure:ADGroupA"
        - "Job/Create:ADGroupA"
        - "Job/Read:authenticated"
        - "Job/Read:ADGroupA"
        - "Job/Workspace:ADGroupA"
        - "Lockable Resources/View:authenticated"
        - "Overall/Administer:ADGroupA"
        - "Overall/Read:authenticated"
        - "Overall/Read:ADGroupA"
        - "Run/Update:ADGroupA"
        - "SCM/Tag:ADGroupA"
        - "View/Configure:ADGroupA"
        - "View/Create:ADGroupA"
        - "View/Read:authenticated"
  securityRealm:
    ldap:
      configurations:
        - groupMembershipStrategy:
            fromUserRecord:
              attributeName: "memberOf"
          groupSearchBase: "ou=XXRedactedXX"
          groupSearchFilter: "cn={0}"
          inhibitInferRootDN: false
          rootDN: "dc=mydomain,dc=com"
          server: "ldaps://myadserver.mydomain.com:5555"
          userSearchBase: "ou=XXRedactedXX"
      disableMailAddressResolver: false
      disableRolePrefixing: true
      groupIdStrategy: "caseInsensitive"
      userIdStrategy: "caseInsensitive"

**Comment by jetersen** [comment]
Than this seems like a bug in ldap plugin based on stack trace you provided and the code below:

https://github.com/jenkinsci/ldap-plugin/blob/d90afa218716ddd99942380c1a98ce841cf9eec7/src/main/java/hudson/security/LDAPSecurityRealm.java#L1294-L1314
```java
                    Attributes v = ldapUser.getAttributes();
                    synchronized (attributesCache) {
                        Attributes vv = (Attributes)attributesCache.get(v);
                        if (vv == null) {
                            attributesCache.put(v, v);
                        } else {
                            v = vv;
                        }
                    }


                    Collection<? extends GrantedAuthority> extraAuthorities = groupMembershipStrategy == null
                            ? authoritiesPopulator.getGrantedAuthorities(ldapUser, username)
                            : groupMembershipStrategy.getGrantedAuthorities(ldapUser, username);
                    for (GrantedAuthority extraAuthority : extraAuthorities) {
                        if (FORCE_GROUPNAME_LOWERCASE) {
                            user.addAuthority(new SimpleGrantedAuthority(extraAuthority.getAuthority().toLowerCase()));
                        } else {
                            user.addAuthority(extraAuthority);
                        }
                    }
                UserAttributesHelper.checkIfUserEnabled(v);
```

Seens `Attributes v = ldapUser.getAttributes();` `v` is null when passed to `UserAttributesHelper.checkIfUserEnabled(v)`

**Comment by timja** [comment]
cc @jvz ^^ I think you were working on that

**Comment by jvz** [comment]
Why would the user return null attributes? That sounds like the user doesn't exist or the LDAP filters are incorrect?

**Comment by jetersen** [comment]
Most likely a config error. After digging into it I could not provoke the error.

**Comment by jvz** [comment]
I'd imagine some sort of error log message would be useful here to indicate no user was found rather than an NPE. Not sure where it would go, though.

**Comment by gerry-christiansen** [comment]
Just to provide some context here.  The user is valid.  Please read the bug entry.  When saving the same configuration manually, it will then work.  Also, if I run the same casc.yml file using the LTS version, then everything works fine.

**Comment by jvz** [comment]
This might be a logical error in the plugin, then, about where that variable is allowed to be null. I'd agree that a null check would likely be appropriate here. The NPE seems to get swallowed into the `DisabledException` anyways.

**Comment by l3ender** [comment]
We are seeing the same error on freestyle builds since updating to Jenkins 2.274. I thought it was related to the email notification plugin, as we see the same error and then the following in build console:

{code}
ERROR: Build step failed with exception
org.springframework.security.authentication.DisabledException: The user "null" is administratively disabled.
...
Build step 'E-mail Notification' marked build as failure
Finished: FAILURE
{code}

As a result, I opened [JENKINS-64629](https://issues.jenkins.io/browse/JENKINS-64629). I'm not sure exactly where the issue is, but we haven't made any configuration changes to LDAP or email notification.

All the build steps complete but then the build fails at the end due to this issue.
