### ISSUE TITLE
jenkins-cli apply-configuration not working

### ISSUE THREAD

**Issue by g1ps** [jenkinsci/configuration-as-code-plugin#1563]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Jenkins version

- [X] Plugin version

- [X] OS

### Description

- Jenkins 2.263.3
- JCASC 1.46
- RHEL8

apply-configuration hangs and never completes. When aborted, it throws 
```
java.io.InterruptedIOException
	at java.io.PipedInputStream.read(PipedInputStream.java:328)
	at java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
Caused: org.yaml.snakeyaml.error.YAMLException
...
```
in the log. I'm initially driving the CLI from Ansible but I checked that it also happens when run manually. The docs to explain where the config is coming from are missing. If it's supposed to be as described under Getting Started, via env. var.s etc, this doesn't work either. If I don't set the env. var.s I see log errors about empty config (no longer available, I'm afraid). If I do set the env. var.s, I can see that the file is found but the config. isn't applied and the process never ends.

See also: #653

### Expectation
* The docs for `apply-configuration` should point to the details
* `apply-configuration` should accept an argument for passing a configuration file or passing the path to it. This is the most basic and obvious use case.
* The command should throw a useful error on failures.

This is a critical facility for automation and needs to work properly if we are to be able to fully automate Jenkins installations and apply config. as part of the process.

### Workaround
The `reload-jcasc-configuration` command does work so you can replace `jenkins.yaml` and call that to load configuration.

Thanks.

**Comment by g1ps** [comment]
Not stale.
