### ISSUE TITLE
java.lang.IllegalStateException: An attempt to save the global configuration was made before it was loaded

### ISSUE THREAD

**Issue by ukreddy-erwin** [jenkinsci/configuration-as-code-plugin#1635]
I started a jenkins server using the docker command below from aws linux 2.

docker run -d --name=buildjobs -p 8081:8080 -p 51001:51001 --env JAVA_OPTS="-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true -Dmail.smtp.starttls.enable=true -Dhudson.tasks.MailSender.SEND_TO_UNKNOWN_USERS=true -Djava.util.logging.config.file=/var/jenkins_home/log.properties -Dhudson.model.DirectoryBrowserSupport.CSP='' -Dhudson.model.DownloadService.noSignatureCheck=true" --env JENKINS_OPTS="--requestHeaderSize=16384" --mount type=bind,src=/home/ec2-user/data,dst=/var/jenkins_home jenkins/jenkins:lts-jdk11

Images tried:
jenkins/jenkins
jenkins/jenkins:lts
jenkins/jenkins:lts-jdk11

But getting below error while connecting:

 Error
java.lang.IllegalStateException: An attempt to save the global configuration was made before it was loaded
	at jenkins.model.Jenkins.save(Jenkins.java:3386)
	at jenkins.model.Jenkins.saveQuietly(Jenkins.java:3405)
	at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2643)
	at jenkins.model.Jenkins$15.run(Jenkins.java:3349)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1162)
	at jenkins.model.Jenkins.<init>(Jenkins.java:960)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:295)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:312)

How to fix this?

**Comment by pavani534** [comment]
I'm trying to upgrade version 2.107.3 Jenkins to 2.289.2 version using docker run command. I am getting the same error. @ukreddy-erwin  kindly share if you get any fix for this?

**Comment by timja** [comment]
Please add a full plugins list, and a reproducing case, i.e. is any configuration required or can you reproduce by just starting the controller.

https://www.jenkins.io/participate/report-issue/#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
