### ISSUE TITLE
security->remotingCLI->true breaks Jenkins?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#177]
Toying with this plugin to simplify tons of customizations, I've hit this issue.

Jenkins version: 2.117
Configuration-as-code plugin version: 0.4-alpha

Inserting the `security`-section into my jenkins.yaml, my Jenkins breaks instantly:
```
jenkins:
  numExecutors: 4
  scmCheckoutRetryCount: 2
  mode: NORMAL
  security:
    remotingCLI:
      enabled: true
[...]
```
The Stack Trace
```
org.jenkinsci.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.model.Hudson : security
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:200)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:46)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:223)
Caused: org.jenkinsci.plugins.casc.ConfiguratorException: jenkins: error configuring <jenkins> with <jenkins> configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:227)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode._configureWithPaths(ConfigurationAsCode.java:165)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:127)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.doReload(ConfigurationAsCode.java:96)
[...]
```

**Comment by ewelinawilkosz** [comment]
from the top of my head - try to move 'security' out of 'jenkins' root element, so it is a root element too, e.g.

```
security:
  remotingCLI:
    enabled: true

jenkins:
  numExecutors: 4
  scmCheckoutRetryCount: 2
  mode: NORMAL
  
[...]
```

and if it doesn't help I will try to have a look - just let me know

**Comment by jonbrohauge** [comment]
Bingo, Thanks.

I'll make a PR to update the example

**Comment by casz** [comment]
until #174 is merged you mostly want it to be set to false 😀 to enable Agent -> Master security
