### ISSUE TITLE
Failed to configure globalMatrix authorization strategy

### ISSUE THREAD

**Issue by sshepel** [jenkinsci/configuration-as-code-plugin#192]
**Jenkins version**: `2.113`
**Plugin version**: `0.5-alpha`

Looks like smth with  [findDescribableBySymbol](https://github.com/jenkinsci/configuration-as-code-plugin/blob/bc7b54e0bf57b32c5509e2cfc4ce4c695240b64a/src/main/java/org/jenkinsci/plugins/casc/HeteroDescribableConfigurator.java#L77) method.

Exception:
----------------------------
```
java.lang.IllegalArgumentException: No hudson.security.AuthorizationStrategy implementation found for globalMatrix
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:95)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:71)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:30)
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:188)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:49)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:27)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:223)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode._configureWithPaths(ConfigurationAsCode.java:165)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:127)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:110)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1098)
	at jenkins.model.Jenkins.<init>(Jenkins.java:900)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```
jenkins.yml
--------------------
```
jenkins:
    authorizationStrategy:
     globalMatrix:
      grantedPermissions:
        - group:
            name: "anonymous"
            permissions:
              - "Job/Discover"
              - "Job/ViewStatus"
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Read"
```

**Comment by casz** [comment]
Could you share your YAML?

**Comment by sshepel** [comment]
> Could you share your YAML?

Sorry, just did that :)

**Comment by casz** [comment]
@sshepel did you install the matrix-auth plugin? :)

**Comment by sshepel** [comment]
OMG, looks like missed it in plugins list :( good catch @casz and thanks for help.

**Comment by casz** [comment]
@sshepel however does it not feel good to finally get it into code 😄

**Comment by sshepel** [comment]
@casz yeap, but I didn't dig too deep :flushed:
