### ISSUE TITLE
new Initializer Milestone?

### ISSUE THREAD

**Issue by casz** [jenkinsci/configuration-as-code-plugin#199]
I think we need a new initializer milestone so plugin can do their thing after configuration as code has configured plugins. I have seen the issue with a few plugins being unable to initalize because of missing credentials or missing global configuration for that plugin which is only configured afterwards.

Is there a way we can ensure plugins are only initialzed after configuration as code plugin at this moment?

I have seen the issue with GitLab Branch source plugin which is using after JOBS_LOADED:
```java
    @Initializer(after = InitMilestone.JOB_LOADED)
    public static void initialize() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                ACL.impersonate(ACL.SYSTEM, new ListenerInitializerTask(GitLabSCMWebHook.get()));
            }
        }).start();
    }
```
[Source](https://github.com/Argelbargel/gitlab-branch-source-plugin/blob/ae36f32cc2835ee37ae3e01fb533c378c683bf8c/src/main/java/argelbargel/jenkins/plugins/gitlab_branch_source/hooks/GitLabSCMWebHook.java#L50-L58)

See #202

**Comment by casz** [comment]
```
jenkins    | May 13, 2018 10:52:41 AM argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager$ListenerState acquire
jenkins    | INFO: acquiring listener for devops...
jenkins    | May 13, 2018 10:52:41 AM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
jenkins    | SEVERE: A thread (Thread-13/47) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
jenkins    | java.util.NoSuchElementException: unknown gitlab-connection: git.3shape.local
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabHelper.gitLabConnection(GitLabHelper.java:38)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.GitLabHelper.gitLabAPI(GitLabHelper.java:27)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager.registerHook(HookManager.java:54)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.HookManager.addListener(HookManager.java:27)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.GitLabSCMWebHook.addListener(GitLabSCMWebHook.java:69)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.GitLabSCMWebHook$ListenerInitializerTask.handle(GitLabSCMWebHook.java:175)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.GitLabSCMWebHook$ListenerInitializerTask.run(GitLabSCMWebHook.java:153)
jenkins    |    at hudson.security.ACL.impersonate(ACL.java:273)
jenkins    |    at argelbargel.jenkins.plugins.gitlab_branch_source.hooks.GitLabSCMWebHook$1.run(GitLabSCMWebHook.java:55)
jenkins    |    at java.lang.Thread.run(Thread.java:748)
```

Since the XML is not properly saved yet: #176 this will always be an issue.
It is also a problem that the configuration as code is run after the gitlab branch source plugin with Initializer of `Milestone.JOB_LOADED`
```
jenkins    | May 13, 2018 10:52:46 AM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
jenkins    | INFO: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.name = git.3shape.local
jenkins    | May 13, 2018 10:52:46 AM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
jenkins    | INFO: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.url = https://git.3shape.local
jenkins    | May 13, 2018 10:52:46 AM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
jenkins    | INFO: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.apiTokenId = gitlab_token
jenkins    | May 13, 2018 10:52:46 AM org.jenkinsci.plugins.casc.DataBoundConfigurator configure
jenkins    | INFO: Setting class com.dabsquared.gitlabjenkins.connection.GitLabConnection.clientBuilderId = v4
jenkins    | May 13, 2018 10:52:46 AM org.jenkinsci.plugins.casc.Attribute lambda$static$0
jenkins    | INFO: Setting com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig#connections = [com.dabsquared.gitlabjenkins.connection.GitLabConnection@32aada2e]
```

**Comment by oleg-nenashev** [comment]
> Is there a way we can ensure plugins are only initialzed after configuration as code plugin at this moment?

No, there is no way to do so. IIRC we had a discussion about that with @ewelinawilkosz and @ndeloof a while ago. Having a new milestone in the core would help. In the case of the referenced plugin the initialization should just run *before* the jobs are loaded. It's totally reasonable, because the plugin may init/update jobs itself.

**Comment by casz** [comment]
The after JOB_LOADED should be after EXTENSIONS_AUGMENTED yet GitLab gets to load before JCasC gets to configure any plugins.

Perhaps we should change JCasC Initializer to include before JOB_LOADED?
`@Initializer(after = InitMilestone.EXTENSIONS_AUGMENTED, before = InitMilestone.JOB_LOADED)`

**Comment by oleg-nenashev** [comment]
Yes, it would make sense

**Comment by ndeloof** [comment]
closing until we get some fresh new init milestone to rely on for a more robust setup
