### ISSUE TITLE
Kubernetes plugin- Not able to set the podTemplate EnvVars

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#204]
- name: "k8s-dind"
            label: "k8s-dind"
            containers:
            envVars:
              - key: "Test"
                value: "Test"
                - name: "docker"
                  image: "dind:latest"
                  ttyEnabled: true
                  alwaysPullImage: true
                  workingDir: "/home/jenkins"
                  command: "/usr/local/bin/dockerd-entrypoint.sh "
                  args: ""
                - name: "jnlp"
                  image: "jnlpagent:updated"
                  ttyEnabled: true
                  alwaysPullImage: true
                  workingDir: "/home/jenkins"
                  command: "/usr/local/bin/jenkins-slave"
                  args: ""

Not sure where the envVars can be set. I tried in all the possible ways by going through the xml structure of confif.xml. Getting error.

            envVars:
              - key: "Test"
                value: "Test"

The  config.xml structure is 

          <envVars>
            <org.csanchez.jenkins.plugins.kubernetes.model.KeyValueEnvVar>
              <key>DOCKER_HOST</key>
              <value>tcp://127.0.0.1:2375</value>
            </org.csanchez.jenkins.plugins.kubernetes.model.KeyValueEnvVar>
          </envVars>

**Comment by ndeloof** [comment]
envVars attribute is a List of PodEnvVars (abstract class) so you need intermediate definition of the concrete implementaiton (KeyValueEnvVar)

```yaml
envVars:
  - KeyValueEnvVar:
      key: "Test"
      value: "Test"
```

**Comment by gogskrish** [comment]
Am getting this exception.

This is my yaml structure.

          - name: "k8s-dind-proxy"
            label: "k8s-dind-proxy"
            inheritFrom: "k8s-build"
            containers:
                - name: "docker"
                  image: "dind_proxy:proxy"
                  ttyEnabled: true
                  alwaysPullImage: true
                  workingDir: "/home/jenkins"
                  privileged: true
                  command: "/usr/local/bin/dockerd-entrypoint.sh "
                  args: ""
            envVars:
              - KeyValueEnvVar:
                  key: "DOCKER_HOST"
                  value: "tcp://127.0.0.1:2375"

java.lang.IllegalArgumentException: No org.csanchez.jenkins.plugins.kubernetes.model.TemplateEnvVar implementation found for KeyValueEnvVar
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:95)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:71)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:30)
	at org.jenkinsci.plugins.casc.DataBoundConfigurator.configure(DataBoundConfigurator.java:123)
	at org.jenkinsci.plugins.casc.DataBoundConfigurator.configure(DataBoundConfigurator.java:123)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:74)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:30)
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:183)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:46)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:223)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode._configureWithPaths(ConfigurationAsCode.java:165)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:127)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:110)

**Comment by ndeloof** [comment]
indeed, KeyValueEnvVar declares a Symbol "[envVar](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/model/KeyValueEnvVar.java#L94)", so you need to use:
```yaml
envVars:
  - envVar:
      key: "Test"
      value: "Test"
```

Did you checked the generated documentation for your installation ?

**Comment by ndeloof** [comment]
your jenkins instance with configuration-as-code plugin do include a dedicated page with links to dynamically generated documentation. see http://JENKINS/configuration-as-code
