### ISSUE TITLE
Error while serving <JENKINS_URL>/configuration-as-code/viewExport

### ISSUE THREAD

**Issue by felipenferri** [jenkinsci/configuration-as-code-plugin#2503]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.452.1
OS: Linux - 5.10.213-201.855.amzn2.x86_64
---
BlazeMeterJenkinsPlugin:4.23
Office-365-Connector:4.21.1
ace-editor:1.1
allure-jenkins-plugin:2.31.1
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-1.0
artifactory:4.0.6
asm-api:9.7-33.v4d23ef79fcc8
audit-trail:361.v82cde86c784e
authentication-tokens:1.113.v81215a_241826
authorize-project:1.7.1
aws-credentials:231.v08a_59f17d742
aws-java-sdk:1.12.730-457.v3403b_37d2170
aws-java-sdk-api-gateway:1.12.730-457.v3403b_37d2170
aws-java-sdk-autoscaling:1.12.730-457.v3403b_37d2170
aws-java-sdk-cloudformation:1.12.730-457.v3403b_37d2170
aws-java-sdk-cloudfront:1.12.730-457.v3403b_37d2170
aws-java-sdk-codebuild:1.12.730-457.v3403b_37d2170
aws-java-sdk-codedeploy:1.12.730-457.v3403b_37d2170
aws-java-sdk-ec2:1.12.730-457.v3403b_37d2170
aws-java-sdk-ecr:1.12.730-457.v3403b_37d2170
aws-java-sdk-ecs:1.12.730-457.v3403b_37d2170
aws-java-sdk-efs:1.12.730-457.v3403b_37d2170
aws-java-sdk-elasticbeanstalk:1.12.730-457.v3403b_37d2170
aws-java-sdk-elasticloadbalancingv2:1.12.730-457.v3403b_37d2170
aws-java-sdk-iam:1.12.730-457.v3403b_37d2170
aws-java-sdk-kinesis:1.12.730-457.v3403b_37d2170
aws-java-sdk-lambda:1.12.730-457.v3403b_37d2170
aws-java-sdk-logs:1.12.730-457.v3403b_37d2170
aws-java-sdk-minimal:1.12.730-457.v3403b_37d2170
aws-java-sdk-organizations:1.12.730-457.v3403b_37d2170
aws-java-sdk-secretsmanager:1.12.730-457.v3403b_37d2170
aws-java-sdk-sns:1.12.730-457.v3403b_37d2170
aws-java-sdk-sqs:1.12.730-457.v3403b_37d2170
aws-java-sdk-ssm:1.12.730-457.v3403b_37d2170
aws-secrets-manager-credentials-provider:1.214.va_0a_d8268d068
awseb-deployment-plugin:0.3.21
azure-app-service:1.0.2
azure-commons:1.1.3
azure-credentials:312.v0f3973cd1e59
azure-function:0.3.3
azure-sdk:157.v855da_0b_eb_dc2
badge:1.12
blueocean:1.27.12
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.12
blueocean-commons:1.27.12
blueocean-config:1.27.12
blueocean-core-js:1.27.12
blueocean-dashboard:1.27.12
blueocean-display-url:2.4.2
blueocean-events:1.27.12
blueocean-executor-info:1.27.12
blueocean-git-pipeline:1.27.12
blueocean-github-pipeline:1.27.12
blueocean-i18n:1.27.12
blueocean-jira:1.27.12
blueocean-jwt:1.27.12
blueocean-personalization:1.27.12
blueocean-pipeline-api-impl:1.27.12
blueocean-pipeline-editor:1.27.12
blueocean-pipeline-scm-api:1.27.12
blueocean-rest:1.27.12
blueocean-rest-impl:1.27.12
blueocean-web:1.27.12
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-233.vfdcdeb_0a_08a_a_
branch-api:2.1169.va_f810c56e895
build-timeout:1.32
build-user-vars-plugin:166.v52976843b_435
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
cloudbees-bitbucket-branch-source:886.v44cf5e4ecec5
cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
cloudbees-folder:6.928.v7c780211d66e
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-109.vfe16c66636eb_
conditional-buildstep:1.4.3
config-file-provider:973.vb_a_80ecb_9a_4d0
configuration-as-code:1810.v9b_c30a_249a_4c
confluence-publisher:163.vf906edb_73cce
copyartifact:722.v0662a_9b_e22a_c
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:677.vdc9d38cb_254d
data-tables-api:2.0.7-1
delivery-pipeline-plugin:1.4.2
display-url-api:2.204.vf6fddd8a_8b_e9
dmm-deployment-metric-plugin:1.0.9
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.6-90.ve7c5c7535ddd
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1814.v404722f34263
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
favorite:2.208.v91d65b_7792a_c
file-parameters:339.v4b_cc83e11455
font-awesome-api:6.5.2-1
generic-webhook-trigger:2.2.1
git:5.2.2
git-client:4.7.0
git-parameter:0.9.19
git-server:126.v0d945d8d2b_39
github:1.39.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1789.v5b_0c0cea_18c3
global-build-stats:293.vd7b_d6e361475
google-oauth-plugin:1.330.vf5e86021cb_ec
gradle:2.12
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.11.0-41.v019fcf6125dc
h2-api:11.1.4.199-30.v1c64e772f3a_c
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
hipchat:2.2.1
htmlpublisher:1.34
hudson-wsclean-plugin:1.0.8
influxdb:3.6.1
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.12
jenkins-multijob-plugin:627.v7c23cef20a_6a
jersey2-api:2.42-147.va_28a_44603b_d5
jira:3.13
jira-steps:2.0.165.v8846cf59f3db
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
job-dsl:1.87
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1265.v65b_14fa_f12f0
kubernetes:4238.v41b_3ef14a_5d8
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:174.va_36e093562d9
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:1255.vf48745da_35d0
logstash:2.5.0218.v0a_ff8fefc12b_
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.2
matrix-project:831.v084e85a_b_4ea_d
maven-metadata-plugin:2.2
maven-plugin:3.23
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.12.1-101.v85b_e08b_780dd
mina-sshd-api-core:2.12.1-101.v85b_e08b_780dd
momentjs:1.1.1
monitoring:1.99.0
nested-view:1.33
nodejs:1.6.1
oauth-credentials:0.653.v14cf2088e950
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.11
parameterized-scheduler:277.v61a_4b_a_49a_c5c
parameterized-trigger:806.vf6fff3e28c3e
performance:960.v701db_0d66e1b_
pipeline-aws:1.45
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:710.v4b_94b_077a_808
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2198.v41dd8ef6dd56
pipeline-model-definition:2.2198.v41dd8ef6dd56
pipeline-model-extensions:2.2198.v41dd8ef6dd56
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2198.v41dd8ef6dd56
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:182.v468b_97b_9dcb_8
plugin-usage-plugin:4.4
plugin-util-api:4.1.0
prism-api:1.29.0-15
prometheus:770.ve5e758db_606e
pubsub-light:1.18
purge-build-queue-plugin:88.v23b_97b_f2c7a_d
rebuild:332.va_1ee476d8f6d
release-helper:1.3.3
resource-disposer:0.23
role-strategy:727.vd344b_eec783d
run-condition:1.7
s3:466.vf5b_3db_8e3eb_2
saml:4.464.vea_cb_75d7f5e0
scm-api:690.vfc8b_54395023
script-security:1341.va_2819b_414686
slack:715.v1cfed1b_9c63c
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.17.2
sse-gateway:1.26
ssh-agent:367.vf9076cd4ee21
ssh-credentials:337.v395d2403ccd4
sshd:3.322.v159e91f6a_550
stashNotifier:1.486.v515d092fa_74a_
strict-crumb-issuer:2.1.1
structs:337.v1b_04ea_4df7c8
subversion:1256.vee91953217b_6
testng-plugin:835.v51ed3da_fcc35
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.3
validating-string-parameter:183.v3748e79b_9737
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1316.v33eb_726c50b_a_
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3894.vd0f0248b_a_fc4
workflow-durable-task-step:1353.v1891a_b_01da_18
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:783.va_6eb_ef636fb_d
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:907.v6713a_ed8a_573
ws-cleanup:0.46
xvfb:1.2

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: 2.452.1
OS: Linux - 5.10.213-201.855.amzn2.x86_64
---
BlazeMeterJenkinsPlugin:4.23
Office-365-Connector:4.21.1
ace-editor:1.1
allure-jenkins-plugin:2.31.1
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-1.0
artifactory:4.0.6
asm-api:9.7-33.v4d23ef79fcc8
audit-trail:361.v82cde86c784e
authentication-tokens:1.113.v81215a_241826
authorize-project:1.7.1
aws-credentials:231.v08a_59f17d742
aws-java-sdk:1.12.730-457.v3403b_37d2170
aws-java-sdk-api-gateway:1.12.730-457.v3403b_37d2170
aws-java-sdk-autoscaling:1.12.730-457.v3403b_37d2170
aws-java-sdk-cloudformation:1.12.730-457.v3403b_37d2170
aws-java-sdk-cloudfront:1.12.730-457.v3403b_37d2170
aws-java-sdk-codebuild:1.12.730-457.v3403b_37d2170
aws-java-sdk-codedeploy:1.12.730-457.v3403b_37d2170
aws-java-sdk-ec2:1.12.730-457.v3403b_37d2170
aws-java-sdk-ecr:1.12.730-457.v3403b_37d2170
aws-java-sdk-ecs:1.12.730-457.v3403b_37d2170
aws-java-sdk-efs:1.12.730-457.v3403b_37d2170
aws-java-sdk-elasticbeanstalk:1.12.730-457.v3403b_37d2170
aws-java-sdk-elasticloadbalancingv2:1.12.730-457.v3403b_37d2170
aws-java-sdk-iam:1.12.730-457.v3403b_37d2170
aws-java-sdk-kinesis:1.12.730-457.v3403b_37d2170
aws-java-sdk-lambda:1.12.730-457.v3403b_37d2170
aws-java-sdk-logs:1.12.730-457.v3403b_37d2170
aws-java-sdk-minimal:1.12.730-457.v3403b_37d2170
aws-java-sdk-organizations:1.12.730-457.v3403b_37d2170
aws-java-sdk-secretsmanager:1.12.730-457.v3403b_37d2170
aws-java-sdk-sns:1.12.730-457.v3403b_37d2170
aws-java-sdk-sqs:1.12.730-457.v3403b_37d2170
aws-java-sdk-ssm:1.12.730-457.v3403b_37d2170
aws-secrets-manager-credentials-provider:1.214.va_0a_d8268d068
awseb-deployment-plugin:0.3.21
azure-app-service:1.0.2
azure-commons:1.1.3
azure-credentials:312.v0f3973cd1e59
azure-function:0.3.3
azure-sdk:157.v855da_0b_eb_dc2
badge:1.12
blueocean:1.27.12
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.12
blueocean-commons:1.27.12
blueocean-config:1.27.12
blueocean-core-js:1.27.12
blueocean-dashboard:1.27.12
blueocean-display-url:2.4.2
blueocean-events:1.27.12
blueocean-executor-info:1.27.12
blueocean-git-pipeline:1.27.12
blueocean-github-pipeline:1.27.12
blueocean-i18n:1.27.12
blueocean-jira:1.27.12
blueocean-jwt:1.27.12
blueocean-personalization:1.27.12
blueocean-pipeline-api-impl:1.27.12
blueocean-pipeline-editor:1.27.12
blueocean-pipeline-scm-api:1.27.12
blueocean-rest:1.27.12
blueocean-rest-impl:1.27.12
blueocean-web:1.27.12
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-233.vfdcdeb_0a_08a_a_
branch-api:2.1169.va_f810c56e895
build-timeout:1.32
build-user-vars-plugin:166.v52976843b_435
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
cloudbees-bitbucket-branch-source:886.v44cf5e4ecec5
cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
cloudbees-folder:6.928.v7c780211d66e
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-109.vfe16c66636eb_
conditional-buildstep:1.4.3
config-file-provider:973.vb_a_80ecb_9a_4d0
configuration-as-code:1810.v9b_c30a_249a_4c
confluence-publisher:163.vf906edb_73cce
copyartifact:722.v0662a_9b_e22a_c
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:677.vdc9d38cb_254d
data-tables-api:2.0.7-1
delivery-pipeline-plugin:1.4.2
display-url-api:2.204.vf6fddd8a_8b_e9
dmm-deployment-metric-plugin:1.0.9
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.6-90.ve7c5c7535ddd
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1814.v404722f34263
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
favorite:2.208.v91d65b_7792a_c
file-parameters:339.v4b_cc83e11455
font-awesome-api:6.5.2-1
generic-webhook-trigger:2.2.1
git:5.2.2
git-client:4.7.0
git-parameter:0.9.19
git-server:126.v0d945d8d2b_39
github:1.39.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1789.v5b_0c0cea_18c3
global-build-stats:293.vd7b_d6e361475
google-oauth-plugin:1.330.vf5e86021cb_ec
gradle:2.12
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.11.0-41.v019fcf6125dc
h2-api:11.1.4.199-30.v1c64e772f3a_c
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
hipchat:2.2.1
htmlpublisher:1.34
hudson-wsclean-plugin:1.0.8
influxdb:3.6.1
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.12
jenkins-multijob-plugin:627.v7c23cef20a_6a
jersey2-api:2.42-147.va_28a_44603b_d5
jira:3.13
jira-steps:2.0.165.v8846cf59f3db
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
job-dsl:1.87
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1265.v65b_14fa_f12f0
kubernetes:4238.v41b_3ef14a_5d8
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:174.va_36e093562d9
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:1255.vf48745da_35d0
logstash:2.5.0218.v0a_ff8fefc12b_
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.2
matrix-project:831.v084e85a_b_4ea_d
maven-metadata-plugin:2.2
maven-plugin:3.23
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.12.1-101.v85b_e08b_780dd
mina-sshd-api-core:2.12.1-101.v85b_e08b_780dd
momentjs:1.1.1
monitoring:1.99.0
nested-view:1.33
nodejs:1.6.1
oauth-credentials:0.653.v14cf2088e950
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.11
parameterized-scheduler:277.v61a_4b_a_49a_c5c
parameterized-trigger:806.vf6fff3e28c3e
performance:960.v701db_0d66e1b_
pipeline-aws:1.45
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:710.v4b_94b_077a_808
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2198.v41dd8ef6dd56
pipeline-model-definition:2.2198.v41dd8ef6dd56
pipeline-model-extensions:2.2198.v41dd8ef6dd56
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2198.v41dd8ef6dd56
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:182.v468b_97b_9dcb_8
plugin-usage-plugin:4.4
plugin-util-api:4.1.0
prism-api:1.29.0-15
prometheus:770.ve5e758db_606e
pubsub-light:1.18
purge-build-queue-plugin:88.v23b_97b_f2c7a_d
rebuild:332.va_1ee476d8f6d
release-helper:1.3.3
resource-disposer:0.23
role-strategy:727.vd344b_eec783d
run-condition:1.7
s3:466.vf5b_3db_8e3eb_2
saml:4.464.vea_cb_75d7f5e0
scm-api:690.vfc8b_54395023
script-security:1341.va_2819b_414686
slack:715.v1cfed1b_9c63c
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.17.2
sse-gateway:1.26
ssh-agent:367.vf9076cd4ee21
ssh-credentials:337.v395d2403ccd4
sshd:3.322.v159e91f6a_550
stashNotifier:1.486.v515d092fa_74a_
strict-crumb-issuer:2.1.1
structs:337.v1b_04ea_4df7c8
subversion:1256.vee91953217b_6
testng-plugin:835.v51ed3da_fcc35
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.3
validating-string-parameter:183.v3748e79b_9737
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1316.v33eb_726c50b_a_
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3894.vd0f0248b_a_fc4
workflow-durable-task-step:1353.v1891a_b_01da_18
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:783.va_6eb_ef636fb_d
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:907.v6713a_ed8a_573
ws-cleanup:0.46
xvfb:1.2

### Reproduction steps

go to <JENKINS_URL>/configuration-as-code/viewExport and return fail
<img width="1705" alt="Screenshot 2024-06-06 at 12 01 15" src="https://github.com/jenkinsci/configuration-as-code-plugin/assets/114502554/39bff9d9-1efc-4ffd-8641-e34a01a34757">

### Expected Results

Configuration as Code report

### Actual Results

2024-06-06 10:54:47.730+0000 [id=9653]	WARNING	hudson.util.Secret#toString: Use of toString() on hudson.util.Secret from hudson.util.Secret$2.convert(Secret.java:337). Prefer getPlainText() or getEncryptedValue() depending your needs. see https://www.jenkins.io/redirect/hudson.util.Secret/
2024-06-06 10:54:50.023+0000 [id=9653]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving https://eps-misc.dev-pmidce.com/manage/configuration-as-code/viewExport
java.lang.StackOverflowError
	at java.base/java.util.TimSort.binarySort(Unknown Source)
	at java.base/java.util.TimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.base/java.util.ArrayList.sort(Unknown Source)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.jenkins.plugins.casc.Configurator.getAttributes(Configurator.java:143)
	at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:182)
	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:330)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:264)
	at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:183)
	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:330)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:264)
	at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:183)
	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:330)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:264)
	at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:183)
	at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:330)

**Comment by somiljain2006** [comment]
@timja I think this issue should be closed as viewExport is working fine.
