### ISSUE TITLE
Plugin based credentials

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/configuration-as-code-plugin#2504]
### What feature do you want to see added?

We should be able to add plugin based credentials from configuration as code config. For example, we use snyk security plugin in our project. Ref: https://plugins.jenkins.io/snyk-security-scanner/#plugin-content-3-configure-a-snyk-api-token-credential

How can we setup snyk api token from configuration as code file?

I added manually from the jenkins portal and credentials.xml file looks like below. But, we don't know how to replicate this from configuration as code?

        <io.snyk.jenkins.credentials.DefaultSnykApiToken plugin="snyk-security-scanner@4.0.3">
          <scope>GLOBAL</scope>
          <id>snyk-api-token</id>
          <description></description>
          <token>{xxxxx==}</token>
        </io.snyk.jenkins.credentials.DefaultSnykApiToken>

**Comment by timja** [comment]
Click the view export button and search the ID `snyk-api-token` you should see what you need to do

**Comment by rnkhouse** [comment]
It's as below:

    - defaultSnykApiToken:
          id: "snyk-api-token"
          scope: GLOBAL
          token: "{xxxxx==}"

But, when I use this config while installing new jenkins instance. It's giving me error:

	2024-06-07 21:53:30.716+0000 [id=20]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving http://10.2.0.36:8080/login
	java.lang.NullPointerException: Cannot invoke "javax.servlet.RequestDispatcher.forward(javax.servlet.ServletRequest, javax.servlet.ServletResponse)" because the return value of "org.kohsuke.stapler.StaplerRequest.getView(java.lang.Class, String)" is null
		at io.jenkins.plugins.casc.ConfigurationAsCode.handleExceptionOnReloading(ConfigurationAsCode.java:207)
		at io.jenkins.plugins.casc.ConfigurationAsCodeBootFailure.doDynamic(ConfigurationAsCodeBootFailure.java:17)
		at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	Caused: java.lang.reflect.InvocationTargetException
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:401)
		at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
		at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
		at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
		at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:501)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
		at org.kohsuke.stapler.Stapler.service(Stapler.java:248)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
		at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
		at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:118)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
		at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
		at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
		at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.Server.handle(Server.java:563)
		at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
		at java.base/java.lang.Thread.run(Unknown Source)
	2024-06-07 21:53:30.717+0000 [id=20]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 10c6c08f-6842-4a3c-a258-e598bb0a0d63
	java.lang.NullPointerException: Cannot invoke "javax.servlet.RequestDispatcher.forward(javax.servlet.ServletRequest, javax.servlet.ServletResponse)" because the return value of "org.kohsuke.stapler.StaplerRequest.getView(java.lang.Class, String)" is null
		at io.jenkins.plugins.casc.ConfigurationAsCode.handleExceptionOnReloading(ConfigurationAsCode.java:207)
		at io.jenkins.plugins.casc.ConfigurationAsCodeBootFailure.doDynamic(ConfigurationAsCodeBootFailure.java:17)
		at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
		at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
		at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
		at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
		at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:501)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
	Caused: javax.servlet.ServletException
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:818)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
		at org.kohsuke.stapler.Stapler.service(Stapler.java:248)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
		at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
		at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:118)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
		at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
		at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
		at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
		at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.Server.handle(Server.java:563)
		at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
		at java.base/java.lang.Thread.run(Unknown Source)
	2024-06-07 21:53:30.717+0000 [id=20]	WARNING	o.e.jetty.server.HttpChannel#handleException: /login
	java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
		at jenkins.model.Jenkins.get(Jenkins.java:824)
		at org.jenkinsci.plugins.matrixauth.AuthorizationContainer.hasPermission(AuthorizationContainer.java:305)
		at hudson.security.GlobalMatrixAuthorizationStrategy$AclImpl.hasPermission(GlobalMatrixAuthorizationStrategy.java:120)
		at hudson.security.SidACL._hasPermission(SidACL.java:73)
		at hudson.security.SidACL.hasPermission2(SidACL.java:54)
		at hudson.security.ACL.checkPermission(ACL.java:76)
		at hudson.security.AccessControlled.checkPermission(AccessControlled.java:52)
		at jenkins.model.Jenkins.getTarget(Jenkins.java:5211)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:725)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
		at hudson.init.impl.InstallUncaughtExceptionHandler.handleException(InstallUncaughtExceptionHandler.java:59)
		at hudson.init.impl.InstallUncaughtExceptionHandler.lambda$init$0(InstallUncaughtExceptionHandler.java:33)
		at org.kohsuke.stapler.compression.CompressionFilter.reportException(CompressionFilter.java:72)
		at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:56)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.Server.handle(Server.java:563)
		at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
		at java.base/java.lang.Thread.run(Unknown Source)
	2024-06-07 21:53:30.718+0000 [id=20]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving http://10.2.0.36:8080/oops
	java.lang.NullPointerException: Cannot invoke "javax.servlet.RequestDispatcher.forward(javax.servlet.ServletRequest, javax.servlet.ServletResponse)" because the return value of "org.kohsuke.stapler.StaplerRequest.getView(java.lang.Class, String)" is null
		at io.jenkins.plugins.casc.ConfigurationAsCode.handleExceptionOnReloading(ConfigurationAsCode.java:207)
		at io.jenkins.plugins.casc.ConfigurationAsCodeBootFailure.doDynamic(ConfigurationAsCodeBootFailure.java:17)
		at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	Caused: java.lang.reflect.InvocationTargetException
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:401)
		at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
		at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
		at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
		at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:501)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
		at org.kohsuke.stapler.Stapler.service(Stapler.java:248)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
		at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:616)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
		at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:215)
		at org.eclipse.jetty.server.Dispatcher.error(Dispatcher.java:75)
		at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:107)
		at org.eclipse.jetty.server.HttpChannel$ErrorDispatchable.dispatch(HttpChannel.java:1623)
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:547)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
		at java.base/java.lang.Thread.run(Unknown Source)
	2024-06-07 21:53:30.728+0000 [id=26]	INFO	winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
	2024-06-07 21:53:30.728+0000 [id=26]	INFO	org.eclipse.jetty.server.Server#doStop: Stopped Server@1ae67cad{STOPPING}[10.0.20,sto=0]
	2024-06-07 21:53:30.730+0000 [id=26]	INFO	o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@5e8ac0e1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
	2024-06-07 21:53:30.733+0000 [id=26]	INFO	o.e.j.s.handler.ContextHandler#doStop: Stopped w.@6fd12c5{Jenkins v2.456,/,null,STOPPED}{/var/jenkins_cache/war}

**Comment by timja** [comment]
Try remove the config file and after starting Jenkins add the file and click reload in the UI, you might get a better error message, that one isn't very useful. (not sure how that is being caused)

**Comment by rnkhouse** [comment]
It's working now. Plugin was getting installed as I have this config `controller.initializeOnce=true`. Thanks for quick response.
