### ISSUE TITLE
Jenkins Build Failure 

### ISSUE THREAD

**Issue by jaderowl** [jenkinsci/configuration-as-code-plugin#2512]
Jenkins version: 2.426.1

 Plugin version: workflow-job 2.37

 OS: Ubuntu 20.04

I have a Jenkins job that has been running smoothly for months, but recently it started failing consistently. The error message in the console output

`java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/job/WorkflowJob
    at MyPipelineScript.run(MyPipelineScript:10)
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.workflow.job.WorkflowJob
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 1 more
Build step 'Execute shell' marked build as failure
Finished: FAILURE
`

**Comment by raghadmta** [comment]
it seems that you have an issue with the plugin version. try updating it (if it gets complicated remove it and install the new version)and if the issue persists can you please show us more logs?
