### ISSUE TITLE
CASC fails if a 'sh """' bloc is used (with double quotes) but works with a "sh '''" bloc (single quotes) - Declarative Pipelines

### ISSUE THREAD

**Issue by archmangler** [jenkinsci/configuration-as-code-plugin#2536]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.401.1
OS: Linux - 6.6.30-0-virt
---
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
azure-ad:457.vf85d61f83b_26
azure-sdk:174.va_89c1df897d2
bootstrap5-api:5.3.2-3
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1128.v717130d4f816
build-timeout:1.31
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-folder:6.858.v898218f3609d
commons-lang3-api:3.14.0-76.vda_5591261cfe
commons-text-api:1.11.0-94.v3e1f4a_926e49
configuration-as-code:1700.v6f448841296e
credentials:1319.v7eb_51b_3a_c97b_
credentials-binding:642.v737c34dea_6c2
display-url-api:2.204.vf6fddd8a_8b_e9
durable-task:555.v6802fe0f0b_82
echarts-api:5.4.0-7
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
font-awesome-api:6.5.1-2
git:5.2.1
git-client:4.6.0
github:1.37.3.1
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1771.v59b_6a_fa_1b_89e
github-oauth:597.ve0c3480fcb_d0
gradle:2.12
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.15.3-363.v82c51b_de9f60
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-8
jaxb:2.3.9-1
jdk-tool:63.v62d2fd4b_4793
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
job-dsl:1.87
jquery3-api:3.7.1-1
junit:1265.v65b_14fa_f12f0
mailer:470.vc91f60c5d8e2
matrix-auth:3.2.2
matrix-project:818.v7eb_e657db_924
mina-sshd-api-common:2.12.1-101.v85b_e08b_780dd
mina-sshd-api-core:2.12.1-101.v85b_e08b_780dd
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.11
permissive-script-security:0.7
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2150.v4cfd8916915c
pipeline-model-definition:2.2150.v4cfd8916915c
pipeline-model-extensions:2.2150.v4cfd8916915c
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2150.v4cfd8916915c
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.0
plain-credentials:182.v468b_97b_9dcb_8
plugin-util-api:3.8.0
resource-disposer:0.23
scm-api:676.v886669a_199a_a_
script-security:1341.va_2819b_414686
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:337.v395d2403ccd4
ssh-slaves:2.948.vb_8050d697fec
sshd:3.249.v2dc2ea_416e33
structs:325.vcb_307d2a_2782
timestamper:1.27
token-macro:384.vf35b_f26814ec
trilead-api:2.84.86.vf9c960e9b_458
variant:60.v7290fc0eb_b_cd
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3837.v305192405b_c0
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1326.ve643e00e9220
workflow-multibranch:770.v1a_d0708dd1f6
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:907.v6713a_ed8a_573
ws-cleanup:0.46
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu docker container running on Rancher Desktop Kubernetes on MacOS X.

### Reproduction steps

1.  Create a Jenkins declarative pipeline definition in code. use the `sh """ ... """` multiline bloc to issue some example bash commands 
2. Create a Jenkins casc definition file embedding this pipeline.
3. Build the Jenkins master deployer container using docker.
4. Deploy the container on Rancher Kubernetes

### Expected Results

The jenkins docker container should be running successfully and pipelines should be executable following login to the master instance.

### Actual Results

The jenkins casc-defined docker container will fail to load and the following errors will be displayed upon connecting to the jenkins port via browser:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script: 182: unexpected char: '#' @ line 182, column 23.
                   sh """#!/bin/bash
                         ^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:149)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:119)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:131)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:349)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:220)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:191)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:233)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:189)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:966)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:677)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:689)
	at groovy.lang.GroovyShell$parse.call(Unknown Source)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.parseScript(AbstractDslScriptLoader.groovy:134)
	at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:101)
Caused: javaposse.jobdsl.dsl.DslException: startup failed:
script: 182: unexpected char: '#' @ line 182, column 23.
                   sh """#!/bin/bash
                         ^
1 error
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:258)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:112)
	at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$_runScripts_closure1.doCall(AbstractDslScriptLoader.groovy:61)
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.call(Closure.java:436)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader$runScripts.callCurrent(Unknown Source)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:87)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.lambda$generateFromScript$2ca3044d$1(SeedJobConfigurator.java:120)
	at io.vavr.control.Try.of(Try.java:75)
	at io.vavr.API.Try(API.java:917)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.lambda$generateFromScript$2ca3044d$2(SeedJobConfigurator.java:120)
Caused: io.jenkins.plugins.casc.ConfiguratorException: jobs: Failed to execute script with hash -1839784082
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.lambda$generateFromScript$7(SeedJobConfigurator.java:122)
	at io.vavr.control.Try.getOrElseThrow(Try.java:748)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.lambda$generateFromScript$2ca3044d$2(SeedJobConfigurator.java:121)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.generateFromScript(SeedJobConfigurator.java:123)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.lambda$configure$3(SeedJobConfigurator.java:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.configure(SeedJobConfigurator.java:70)
	at javaposse.jobdsl.plugin.casc.SeedJobConfigurator.configure(SeedJobConfigurator.java:30)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$7(ConfigurationAsCode.java:790)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:731)
Caused: io.jenkins.plugins.casc.ConfiguratorException: jobs: error configuring 'jobs' with class javaposse.jobdsl.plugin.casc.SeedJobConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:737)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:790)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:652)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:314)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:306)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:290)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1199)
	at jenkins.model.Jenkins.<init>(Jenkins.java:987)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:247)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:264)
```

### Anything else?

If we instead use the following `sh` syntax in the pipeline-as-code groovy, the casc-defined jenkins container works. however , we need to use `sh """` to interpolate pipeline variables correctly:

```
                sh '''#!/bin/bash
                set -ex
                echo "Updating  keyvault access for Azure Firewall ..."
                pwd
                '''

```

If we use the above and then edit the pipeline configuration after the jenkins container is up and running with this syntax, the pipeline runs:

```
                sh '''#!/bin/bash
                set -ex
                echo "Updating keyvault access for Azure Firewall ..."
                pwd
                '''

```

So the problem seems to be related to the interaction between CASC plugin and the syntax in the declarative pipeline script.

**Comment by timja** [comment]
You can use `withEnv` or env.MY_NAME = '....'

and then single quotes should work fine for your interpolation

**Comment by archmangler** [comment]
Hi @timja  - thanks for your response. I tested it as follows:
```
```
                script {

                   //This Works ok
                    echo "Retrieving value transported from other stages " + afwMid
                    env.AFW_MID=afwMid
                }
                
//This fails with: "script.sh.copy: line 6: ${env.AFW_MID}: bad substitution"
                sh '''#!/bin/bash
                set -ex
                echo "Updating level-0 foundation keyvault access for Azure Firewall ..."
                pwd
                echo "Retrieving transported variable - AFW MID ..."
                echo ${env.AFW_MID}
                export AFW_CERT_MANAGED_IDENTITY_PRINCIPAL_ID=${env.AFW_MID}
                ls -l
                ./test.sh
                ./deploy.sh
                '''

```

It looks like trying to interpolate ${env.VAR_NAME} within sh ''' ... ''' is not allowed.

**Comment by archmangler** [comment]
A complete testing example (objective: to get `sh` with single quotes to interpolate pipeline variables)

```
def something="entity"
pipeline {
  agent any
  stages {
    stage("hello") {
      steps {
          
        script {
          echo something
          something = "wintermute";
        }
        
        script {
            
            echo "Retrieving value transported between stages" + something
            AFW_MID=something     
        }

      }
    }
    
    stage("goodbye") {
      steps {
        script {
            env.mid = AFW_MID
            echo "Getting value from last stage: ...  "
            echo mid
             echo "Done getting value from last stage: ...  "
        }
        
        //Single quote multiline shell command bloc:
        sh '''
        echo "Getting pipeline env variable value with interpolation " env.mid
        '''
    
      }
    }
  }
```

**Comment by archmangler** [comment]
Aw heck, never mind, this works:

```
def something="entity"
pipeline {
  agent any
  stages {
    stage("hello") {
      steps {
          
        script {
          echo something
          something = "wintermute";
        }
        
        script {
            
            echo "Retrieving value transported between stages" + something
            AFW_MID=something     
        }

      }
    }
    
    stage("goodbye") {
      steps {
        script {
            env.mid = AFW_MID
            echo "Getting value from last stage: ...  "
            echo mid
             echo "Done getting value from last stage: ...  "
        }
        
        //Single quote multiline shell command bloc:
        sh '''
        echo "Getting pipeline env variable value with interpolation " $mid
        '''
    
      }
    }
  }
}
```
