### ISSUE TITLE
Exporter configuration file of empty jenkins can't be imported

### ISSUE THREAD

**Issue by mareths** [jenkinsci/configuration-as-code-plugin#264]
I try to export configuration from empty Jenkins running with "mvn hpi:run" on the project :

```
plugins:
  sites:
  - id: "default"
    url: "http://updates.jenkins-ci.org/update-center.json"
jenkins:
  agentProtocols:
  - "CLI-connect"
  - "CLI2-connect"
  - "JNLP-connect"
  - "JNLP2-connect"
  - "JNLP4-connect"
  - "Ping"
  primaryView: "all"
  mode: NORMAL
  numExecutors: 4
  scmCheckoutRetryCount: 0
  projectNamingStrategy: "standard"
  views:
  - "all"
  disableRememberMe: false
  markupFormatter: "plainText"
  globalNodeProperties:
  - "envVars"
  slaveAgentPort: 0
  myViewsTabBar: "standard"
  viewsTabBar: "standard"
```

When I assign the environment variable CASC_JENKINS_CONFIG with this generated jenkins.yaml, jenkins display this error :

```
java.lang.NullPointerException
	at hudson.Util.rawEncode(Util.java:1052)
	at hudson.model.View.getViewUrl(View.java:524)
	at hudson.model.View.toString(View.java:528)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:209)
Caused: org.jenkinsci.plugins.casc.ConfiguratorException: view: Failed to set attribute primaryView(class: class hudson.model.View, multiple: false)
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:212)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:44)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:412)
Caused: org.jenkinsci.plugins.casc.ConfiguratorException: jenkins: error configuring <jenkins> with <jenkins> configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:418)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:352)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:325)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:176)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:145)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:47)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1124)
	at jenkins.model.Jenkins.<init>(Jenkins.java:929)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:235)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:252)
```

The items "primaryView" and "views" (next error if i remove the item "primaryView") can't be set, because jenkins has no views

Export always return views "all", even if jenkins has not jobs or views defined (additional the issue https://github.com/jenkinsci/configuration-as-code-plugin/issues/222)

Exporter should remove this fields in generated configuration if no views and jobs is present.

**Comment by ndeloof** [comment]
there's indeed a significant design issue in jenkins with "primaryView" attribute which is actually a view name for one of the views from configured list. The setter uses a view but actually the stored attribute is the view name. So we are building a useless view object, which doesn't have an owner set (so the NPE).

not sure yet how to handle this :-\
