### ISSUE TITLE
Not able to configure file credential

### ISSUE THREAD

**Issue by gogskrish** [jenkinsci/configuration-as-code-plugin#271]
I went through the schema and configured file credential. However i could see the exception below.

      - file:
          scope: GLOBAL
          id: jenkins-agent-ssh-key-file
          description: "Key to login into docker as jenkins user."
          filename: "jenkins-agent-ssh-key-file"
          secretbytes: ABC

java.lang.IllegalArgumentException: file is required to configure class org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl
	at org.jenkinsci.plugins.casc.DataBoundConfigurator.configure(DataBoundConfigurator.java:67)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:74)
	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:30)
	at org.jenkinsci.plugins.casc.credentials.CredentialsRootConfigurator.configure(CredentialsRootConfigurator.java:57)
	at org.jenkinsci.plugins.casc.credentials.CredentialsRootConfigurator.configure(CredentialsRootConfigurator.java:26)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:223)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode._configureWithPaths(ConfigurationAsCode.java:165)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:127)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:110)
Caused: java.lang.reflect.InvocationTargetException

**Comment by ndeloof** [comment]
FileCredentialsImpl indeed rely on commons-fileupload to provide the actual file for data-binding.

proposed a fix: https://github.com/jenkinsci/plain-credentials-plugin/pull/11

**Comment by bbxx111** [comment]
Is there any way to avoid this problem ?

**Comment by bbxx111** [comment]
@ndeloof the proposed fix have been approved, and the test failure have been fixed too. 
#https://github.com/jenkinsci/plain-credentials-plugin/pull/11

Thank you.

**Comment by dgarzon** [comment]
@ndeloof Why did you close your proposed fix PR? This should be fixed on the `plain-credentials-plugin` and your solution did it, no? Deal breaker if we cannot get file credentials working with CasC.

**Comment by ndeloof** [comment]
I don't have time to work on this PR, feel free to cherypick what I did to discuss adequate fix.

**Comment by casz** [comment]
This was fixed in https://github.com/jenkinsci/plain-credentials-plugin/pull/14 and released in v1.5 of plain-credentials-plugins
