### ISSUE TITLE
Job loading Chicken&Egg

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#280]
IMHO it is a serious fundamental issue in the plugin now. 

* The plugin gets invoked somewhere between "EXTENSIONS_AUGMENTED" and "JOBS_LOADED" milestones on Jenkins startup
* JCasC happens in parallel with Job loading. If Job loading takes plugin configuration into account, we are in the undefined behavior zone
* Plugin dynamic loading potentially makes it even worse since plugins may have ItemListeners & Co
* For big instances the plugin invocation may be delayed. We have instances which are loading jobs for 30 minutes.

From https://speakerdeck.com/onenashev/gbg-jam-managing-jenkins-with-groovy-hooks-and-jcasc:

<img width="1048" alt="screen shot 2018-06-11 at 11 25 19" src="https://user-images.githubusercontent.com/3000480/41223488-39f3ac32-6d6a-11e8-952c-89b365fb4003.png">

A solution would be to introduce new milestones in the Jenkins core to have strict ordering between JCasC and Job loading. IMHO JCasC should always happen before we start loading jobs.

**Comment by oleg-nenashev** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-51856

**Comment by casz** [comment]
relates to #199 :)

**Comment by oleg-nenashev** [comment]
Yes, it is a duplicate. Not sure why #199 was closed, I am fine with reopening that ticket and closing this one as a dup

**Comment by x10an14** [comment]
Adding my experience here, as opposed to #199, since this one is still open.

Are these error messages an artifact of the dilemma raised in this issue (and issue #199)?:
```
jenkins_1  | Jul 26, 2018 10:40:33 AM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1  | SEVERE: Failed ConfigurationAsCode.init
jenkins_1  | java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | 	... 8 more
jenkins_1  | Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: No configurator for root element <jobs>
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:505)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:511)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:409)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:159)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:151)
jenkins_1  | 	... 13 more
jenkins_1  | 
jenkins_1  | Jul 26, 2018 10:40:33 AM hudson.util.BootFailure publish
jenkins_1  | SEVERE: Failed to initialize Jenkins
jenkins_1  | hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.WebAppMain$3.run(WebAppMain.java:250)
jenkins_1  | Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
jenkins_1  | 	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
jenkins_1  | 	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
jenkins_1  | 	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
jenkins_1  | 	at hudson.model.Hudson.<init>(Hudson.java:85)
jenkins_1  | 	at hudson.model.Hudson.<init>(Hudson.java:81)
jenkins_1  | 	at hudson.WebAppMain$3.run(WebAppMain.java:233)
jenkins_1  | Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | 	... 8 more
jenkins_1  | Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: No configurator for root element <jobs>
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:505)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:511)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:409)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:159)
jenkins_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:151)
jenkins_1  | 	... 13 more
jenkins_1  | 
jenkins_1  | Jul 26, 2018 10:40:33 AM jenkins.model.Jenkins cleanUp
```

My jobs config (using `configuration-as-code:0.10-alpha`):
```
jobs:
  - >
    multibranchPipelineJob('demo-example') {
      description('Simplistic hello-world example job')
      branchSources {
        git {
          remote('<valid ssh address for git repo with Jenkinsfile>')
        }
      }
    }
```

**Comment by jonbrohauge** [comment]
@x10an14 the way to define jobs have changed.

**Comment by x10an14** [comment]
@jonbrohauge I tried that way first, but then I got `snakeyaml` parse-errors... 

Until I get the the plugin-installs to work again ([ref this conversation here](https://gitter.im/jenkinsci/configuration-as-code-plugin?at=5b59b6e5bd17b96159050b5f)), I'm a bit at a loss of how to continue testing =(

I'll try again as soon as the opportunity presents itself! =)

**Comment by x10an14** [comment]
I got it to work now!

It seems that if you're using the `jenkins/jenkins` docker-hub docker-image (and use the `install-plugins.sh` available inside to install your plugins), the following was necessary for me to get the [above-mentioned config](https://github.com/jenkinsci/configuration-as-code-plugin/issues/280#issuecomment-408056558) to work (when using `configuration-as-code:0.10-alpha`, that is):
```
diff --git a/plugins.txt b/plugins.txt
index 7d1b06b..988df91 100644
--- a/plugins.txt
+++ b/plugins.txt
@@ -1,5 +1,6 @@
 git:3.9.1
 saml:1.0.7
+job-dsl:1.70
 docker-slaves:1.0.7
 pipeline-utility-steps:2.1.0
 pipeline-model-definition:1.3.1
```

@jonbrohauge I'd imagine your tip is right on the money for versions `0.11-alpha` and onwards for `configuration-as-code` plugin! =)

**Comment by jonbrohauge** [comment]
@x10an14 Haven't used 0.10-alpha. I went from 0.9-alpha directly to homegrown 0.11-alpha-SNAPSHOT, due to me playing with `CASC_VAULT_TOKEN`

**Comment by casz** [comment]
We should solve this tomorrow at the hackathon at [Day of Jenkins as Code](https://www.code-conf.com/2018/day-of-jenkins-as-code/)

**Comment by Bryann** [comment]
any progress on this issue so far?

**Comment by oleg-nenashev** [comment]
not yet :(

**Comment by arnaud-deprez** [comment]
Dear,

Since I upgraded to:

```
job-dsl:1.74
configuration-as-code:1.22
configuration-as-code-groovy:1.1
```
I removed `configuration-as-code-support` plugin as documented (well, it's only after reading the whole changelog that I realized it was not needed anymore).

and with a job configuration like:

```
jobs:
  - script: >
       multibranchPipelineJob('demo-example') {...}
```

And I met the same issue than https://github.com/jenkinsci/configuration-as-code-plugin/issues/280#issuecomment-408056558

With an updated stacktrace, it gives:

```
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: No configurator for root element <jobs>
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:648)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:672)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:656)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:555)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:278)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:270)
	... 13 more
```

If I remove the `jobs` configuration, then jenkins starts.

Is it linked to that issue ? Should I create another one ?
Any help is appreciated.

**Comment by oleg-nenashev** [comment]
not stale

**Comment by olivergondza** [comment]
Thinking of the idea of separate milestone in context of JENKINS-58993:

The problem I see is [Jenkins#loadConfig()](https://github.com/jenkinsci/jenkins/blob/eedf2a4e2a25f5883d828f22c2429ceebe2bd157/core/src/main/java/jenkins/model/Jenkins.java#L3201) attains `JOB_LOADED`, which we would like to rectify as well I guess. If for nothing else, just to make sure it does not run after jcasc initializer.

So we can let it to attain the earlier milestone we create, but that would not make sure it happens before JCasC has run as it would be attaining the same milestone. So I guess we either have to figure out of get `Jenkins#loadConfig()` completed _before_ the new milestone starts or introduce 2 new milestones for this purpose.

---

I am drifting off a bit but are we not having the same problem with loading jobs from disk vs. populating them from JCasC? When the Jenkins is being restarted so the seed job is on disk, we need to make sure JCasC overwrites the one from disk and not the other way around. Is there some existing mechanism to ensure that does not happen?

**Comment by fcojfernandez** [comment]
FTR, I've just opened: https://github.com/jenkinsci/jenkins/pull/4450
