### ISSUE TITLE
Couldn't set quietPeriod

### ISSUE THREAD

**Issue by sshepel** [jenkinsci/configuration-as-code-plugin#293]
Jenkins version: `2.121.1`
CasC plugin version: `0.8`

Following `jenkins.yaml` snippet:
```
jenkins:
  quietPeriod: 0
```
return following error:
```
org.jenkinsci.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.model.Hudson : quietPeriod
```
Another try for this:
```
jenkins:
  unclassified:
     quietPeriod: 0
```
returns following:
```
org.jenkinsci.plugins.casc.ConfiguratorException: Item isn't a Mapping
	at org.jenkinsci.plugins.casc.model.CNode.asMapping(CNode.java:17)
	at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:51)
	at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:13)
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:205)
	at org.jenkinsci.plugins.casc.GlobalConfigurationCategoryConfigurator.configure(GlobalConfigurationCategoryConfigurator.java:51)
	at org.jenkinsci.plugins.casc.GlobalConfigurationCategoryConfigurator.configure(GlobalConfigurationCategoryConfigurator.java:18)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:403)
Caused: org.jenkinsci.plugins.casc.ConfiguratorException: unclassified: error configuring <unclassified> with <unclassified> configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:409)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:343)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:316)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:176)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:145)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

**Comment by ndeloof** [comment]
there's no reason `unclassified: quietPeriod: 0` would work, quietPeriod is a Jenkins attribute, should be detected.
My guess is we don't get a PropertyDescriptor as `Jenkins` do use distinct types (`int` vs `Integer`) for getter and setter and just break javabeans convention

**Comment by sshepel** [comment]
@ndeloof thanks for clarification, at least now we know that `unclassified` it's a wrong tag for `quietPeriod` ;)

**Comment by sshepel** [comment]
@ndeloof just noticed this on plugin's github main page:
![quietperiod](https://user-images.githubusercontent.com/9946053/41592266-ac54b1b2-73c4-11e8-8eaf-69244800713f.jpg)

**Comment by ndeloof** [comment]
I didn't noticed there's a GlobalConfigurator for this purpose, interesting.
not something we can use unfortunately :'(
