### ISSUE TITLE
CasC config exporter failing with argument type mismatch

### ISSUE THREAD

**Issue by kstevena** [jenkinsci/configuration-as-code-plugin#304]
Using the latest release (0.9-alpha) and latest lts jenkins (2.121.1) docker image, list of installed plugins version detailed at the bottom, the export of the configuration is failing with the following error:
by the way this instance is already bootstraped with CasC.

```
Jun 29, 2018 8:27:51 AM org.eclipse.jetty.server.handler.ContextHandler$Context log
WARNING: Error while serving https://XXX/configuration-as-code/export
java.lang.reflect.InvocationTargetException
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
        at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
        at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
        at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
        at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jenkinsci.plugins.casc.DataBoundConfigurator.describe(DataBoundConfigurator.java:218)
        at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:129)
        at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:35)
        at org.jenkinsci.plugins.casc.Attribute.describe(Attribute.java:175)
        at org.jenkinsci.plugins.casc.DataBoundConfigurator.describe(DataBoundConfigurator.java:227)
        at org.jenkinsci.plugins.casc.Attribute.describe(Attribute.java:175)
        at org.jenkinsci.plugins.casc.credentials.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:51)
        at org.jenkinsci.plugins.casc.credentials.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:21)
        at org.jenkinsci.plugins.casc.Attribute.describe(Attribute.java:179)
        at org.jenkinsci.plugins.casc.credentials.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:76)
        at org.jenkinsci.plugins.casc.credentials.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:37)
        at org.jenkinsci.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:234)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
        ... 81 more
```

list of plugins:
ace-editor:1.1
ant:1.8
apache-httpcomponents-client-4-api:4.5.5-3.0
artifactory:2.16.1
authentication-tokens:1.3
blackduck-detect:1.4.1
blueocean:1.6.1
blueocean-autofavorite:1.2.2
blueocean-bitbucket-pipeline:1.6.1
blueocean-commons:1.6.1
blueocean-config:1.6.1
blueocean-core-js:1.6.1
blueocean-dashboard:1.6.1
blueocean-display-url:2.2.0
blueocean-events:1.6.1
blueocean-github-pipeline:1.6.1
blueocean-git-pipeline:1.6.1
blueocean-i18n:1.6.1
blueocean-jira:1.6.1
blueocean-jwt:1.6.1
blueocean-personalization:1.6.1
blueocean-pipeline-api-impl:1.6.1
blueocean-pipeline-editor:1.6.1
blueocean-pipeline-scm-api:1.6.1
blueocean-rest:1.6.1
blueocean-rest-impl:1.6.1
blueocean-web:1.6.1
bouncycastle-api:2.16.3
branch-api:2.0.20
cloudbees-bitbucket-branch-source:2.2.11
cloudbees-folder:6.5.1
config-file-provider:2.18
configuration-as-code:0.9-alpha
credentials:2.1.17
credentials-binding:1.16
display-url-api:2.2.0
docker-commons:1.13
docker-java-api:3.0.14
docker-plugin:1.1.4
docker-workflow:1.17
durable-task:1.22
favorite:2.3.2
gerrit-trigger:2.27.5
git:3.9.1
git-client:2.7.2
github:1.29.2
github-api:1.92
github-branch-source:2.3.6
gitlab-plugin:1.5.6
git-server:1.7
gradle:1.28
handlebars:1.1.1
handy-uri-templates-2-api:2.1.6-1.0
htmlpublisher:1.16
ivy:1.28
jackson2-api:2.8.11.3
javadoc:1.4
jenkins-design-language:1.6.1
jira:3.0.0
job-dsl:1.69
jquery-detached:1.2.1
jsch:0.1.54.2
junit:1.24
kubernetes:1.9.2
kubernetes-credentials:0.3.1
kubernetes-pipeline-aggregator:1.5
kubernetes-pipeline-arquillian-steps:1.5
kubernetes-pipeline-devops-steps:1.5
kubernetes-pipeline-steps:1.5
ldap:1.20
mailer:1.21
matrix-auth:2.2
matrix-project:1.13
maven-plugin:3.1.2
mercurial:2.4
momentjs:1.1.1
pipeline-build-step:2.7
pipeline-graph-analysis:1.7
pipeline-input-step:2.8
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.1
pipeline-model-extensions:1.3.1
pipeline-rest-api:2.10
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.1
pipeline-stage-view:2.10
plain-credentials:1.4
pubsub-light:1.12
rabbitmq-build-trigger:2.5
rabbitmq-consumer:2.8
scm-api:2.2.7
script-security:1.44
sonar:2.7.1
sse-gateway:1.15
ssh-credentials:1.14
ssh-slaves:1.26
structs:1.14
token-macro:2.5
variant:1.1
workflow-aggregator:2.5
workflow-api:2.28
workflow-basic-steps:2.9
workflow-cps:2.54
workflow-cps-global-lib:2.9
workflow-durable-task-step:2.19
workflow-job:2.21
workflow-multibranch:2.19
workflow-scm-step:2.6
workflow-step-api:2.16
workflow-support:2.19

**Comment by casz** [comment]
Seems like a incomplete stacktrace, can you please provide the pieces that are missing in the top.

**Comment by kstevena** [comment]
Indeed, I updated it.

**Comment by ndeloof** [comment]
fixed by https://github.com/jenkinsci/configuration-as-code-plugin/commit/969d840971052c6529e5ab39d7f11ba0193eb281
