### ISSUE TITLE
Can't run plugin in development monde

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/configuration-as-code-plugin#314]
using `mvn hpi:run` from plugin module:

```
GRAVE: Failed to create Guice container from all the plugins
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:51)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:35)
	at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:41)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:93)
	at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:56)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:187)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:477)
	at hudson.ExtensionList.load(ExtensionList.java:365)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
	at hudson.ExtensionList.getComponents(ExtensionList.java:168)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1121)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

juil. 03, 2018 6:37:54 AM hudson.ExtensionFinder$Sezpoz _find
AVERTISSEMENT: Failed to load hudson.ExtensionFinder$GuiceFinder
java.lang.InstantiationException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.model.Jenkins$EnforceSlaveAgentPortAdministrativeMonitor.j(Jenkins.java:1281)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

2) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.AdminCallableMonitor.jenkins(AdminCallableMonitor.java:33)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

3) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.MasterKillSwitchConfiguration.jenkins(MasterKillSwitchConfiguration.java:18)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

3 errors
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:191)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:477)
	at hudson.ExtensionList.load(ExtensionList.java:365)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
	at hudson.ExtensionList.getComponents(ExtensionList.java:168)
	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1121)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ndeloof** [comment]
duplicate https://github.com/jenkinsci/configuration-as-code-plugin/issues/322
