### ISSUE TITLE
mvn hpi:run fails to load

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#322]
It seems the developer tooling is not compatible with #234 somehow. When `JNLPLauncherLegacyConstructorProvider` is marked an Extension, `mvn hpi:run` fails with the following error:

```
1) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.model.Jenkins$EnforceSlaveAgentPortAdministrativeMonitor.j(Jenkins.java:1281)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

2) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.AdminCallableMonitor.jenkins(AdminCallableMonitor.java:33)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

3) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:306)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.MasterKillSwitchConfiguration.jenkins(MasterKillSwitchConfiguration.java:18)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:508)

3 errors
    at net.java.sezpoz.IndexItem.instance(IndexItem.java:191)
    at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
    at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
    at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:477)
    at hudson.ExtensionList.load(ExtensionList.java:365)
    at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
    at hudson.ExtensionList.getComponents(ExtensionList.java:168)
    at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1121)
    at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
    at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
    at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
```

**Comment by oleg-nenashev** [comment]
@ndeloof I will submit a fix this weekend. Sorry, was not able to finalize it on Wed

**Comment by ndeloof** [comment]
no worries, as we have a workaround for it this can wait for you to have spare time. Don't change your week-end plans for it :)

**Comment by MadsNielsen** [comment]
@oleg-nenashev Was this the fix you talked about which you could do by removing the `Optional` flag on the extension point?

**Comment by oleg-nenashev** [comment]
Actually, now there is a bit different issue in the codebase. I tested it with #376 , and the error is still there when you run on the default Jenkins core.

Why?

* Jenkins Core 2.60.3 does not support `Beta` annotations. They are added to the core by https://github.com/jenkinsci/jenkins/commit/a54d49b634e2cdd2fc11ab0021a1865630fc339e (available in 2.121.1)
* Although it should flawlessly work in common cases, Guice annotation processing seems to be failing when it comes to extension indexing. 
* My PR in https://github.com/jenkinsci/configuration-as-code-plugin/pull/355 annotated extension points with `Beta`, and it has blown up the master codebase with `hpi:run` similarly to #234 
* Production usages run well on older Jenkins versions AFAICT

The stacktraces for `hpi:run` are quite bizarre, but removal of Beta annotations actually solves the issue. Using `mvn hpi:run -Djenkins.version=2.121.1` also "solves" the issue.

So this is a case for sezpoz or guice patch, I'd guess. In this plugin  we can only remove annotations, bump the core dependency, or enforce accmod dependency to make hpi:run running. The latter option would do the job, but I am not sure how legitimate it is. CC @jglick 

To debug such issues...
1) Use mvnDebug hpi:run
2) Set debug breakpoints to `java.lang.TypeNotPresentException` in IDE
3) Attach IDE's remote debugger to the plugin
4) Capture loading exceptions when Jenkins starts loading the plugin

**Comment by ndeloof** [comment]
thanks a lot @oleg-nenashev for diagnostic !

**Comment by oleg-nenashev** [comment]
What is left to be done here?

**Comment by ndeloof** [comment]
We still don't have a fix but bump Jenkins version being used for hpi:run

**Comment by oleg-nenashev** [comment]
Moved to the 1.0 milestone fore review so that I close the RC milestone
