### ISSUE TITLE
Unable to export empty configuration

### ISSUE THREAD

**Issue by wlfshmn** [jenkinsci/configuration-as-code-plugin#332]
Environment is docker container jenkins/jenkins:2.121.1 and jcasc 0.9a

Jenkins is unconfigured and freshly bootstrapped from official docker images, plus a plugins list. List below is resulting installed plugins, not the provided list.

Plugin list:
```
ace-editor:1.1
analysis-collector:1.52
analysis-core:1.95
ansicolor:0.5.2
ant:1.8
antisamy-markup-formatter:1.5
apache-httpcomponents-client-4-api:4.5.5-3.0
artifactory:2.16.1
authentication-tokens:1.3
blueocean-autofavorite:1.2.2
blueocean-bitbucket-pipeline:1.6.2
blueocean-commons:1.6.2
blueocean-config:1.6.2
blueocean-core-js:1.6.2
blueocean-dashboard:1.6.2
blueocean-display-url:2.2.0
blueocean-events:1.6.2
blueocean-git-pipeline:1.6.2
blueocean-github-pipeline:1.6.2
blueocean-i18n:1.6.2
blueocean-jira:1.6.2
blueocean-jwt:1.6.2
blueocean-personalization:1.6.2
blueocean-pipeline-api-impl:1.6.2
blueocean-pipeline-editor:1.6.2
blueocean-pipeline-scm-api:1.6.2
blueocean-rest-impl:1.6.2
blueocean-rest:1.6.2
blueocean-web:1.6.2
blueocean:1.6.2
bouncycastle-api:2.16.3
branch-api:2.0.20
cloudbees-bitbucket-branch-source:2.2.11
cloudbees-folder:6.5.1
config-file-provider:2.18
configuration-as-code:0.9-alpha
credentials-binding:1.16
credentials:2.1.17
cucumber-reports:3.18.0
display-url-api:2.2.0
docker-commons:1.13
docker-workflow:1.17
durable-task:1.22
favorite:2.3.2
git-changelog:2.6
git-client:2.7.2
git-server:1.7
git:3.9.1
github-api:1.92
github-branch-source:2.3.6
github:1.29.2
gradle:1.29
greenballs:1.15
handy-uri-templates-2-api:2.1.6-1.0
htmlpublisher:1.16
ivy:1.28
jackson2-api:2.8.11.3
javadoc:1.4
jdk-tool:1.1
jenkins-design-language:1.6.2
jira:3.0.0
job-dsl:1.70
jquery-detached:1.2.1
jsch:0.1.54.2
junit:1.24
ldap:1.20
mailer:1.21
matrix-project:1.13
mattermost:2.5.0
maven-plugin:3.1.2
mercurial:2.4
pipeline-build-step:2.7
pipeline-graph-analysis:1.7
pipeline-input-step:2.8
pipeline-maven:3.5.9
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.1
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.1
pipeline-model-extensions:1.3.1
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.1
pipeline-utility-steps:2.1.0
plain-credentials:1.4
pubsub-light:1.12
resource-disposer:0.11
scm-api:2.2.7
script-security:1.44
sse-gateway:1.15
ssh-agent:1.15
ssh-credentials:1.14
ssh-slaves:1.26
structs:1.14
timestamper:1.8.10
token-macro:2.5
variant:1.1
workflow-api:2.28
workflow-basic-steps:2.9
workflow-cps-global-lib:2.9
workflow-cps:2.54
workflow-durable-task-step:2.19
workflow-job:2.22
workflow-multibranch:2.19
workflow-scm-step:2.6
workflow-step-api:2.16
workflow-support:2.19
ws-cleanup:0.34
```

Exception as logged when accessing export function
```
jenkins-master_1  | WARNING: Error while serving http://builds.local:9090/configuration-as-code/export
jenkins-master_1  | java.lang.reflect.InvocationTargetException
jenkins-master_1  | 	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
jenkins-master_1  | 	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
jenkins-master_1  | 	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
jenkins-master_1  | 	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
jenkins-master_1  | 	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
jenkins-master_1  | 	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
jenkins-master_1  | 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
jenkins-master_1  | 	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
jenkins-master_1  | 	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
jenkins-master_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
jenkins-master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
jenkins-master_1  | 	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
jenkins-master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins-master_1  | 	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
jenkins-master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins-master_1  | 	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
jenkins-master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins-master_1  | 	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
jenkins-master_1  | 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins-master_1  | 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
jenkins-master_1  | 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
jenkins-master_1  | 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins-master_1  | 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
jenkins-master_1  | 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
jenkins-master_1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
jenkins-master_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
jenkins-master_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
jenkins-master_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
jenkins-master_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
jenkins-master_1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
jenkins-master_1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
jenkins-master_1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
jenkins-master_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
jenkins-master_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
jenkins-master_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
jenkins-master_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
jenkins-master_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
jenkins-master_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
jenkins-master_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
jenkins-master_1  | 	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
jenkins-master_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins-master_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins-master_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins-master_1  | Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Can't read attribute 'users' from hudson.security.HudsonPrivateSecurityRealm@34c54109
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.Attribute._getValue(Attribute.java:226)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.Attribute.getValue(Attribute.java:162)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.Attribute.equals(Attribute.java:183)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:223)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.DataBoundConfigurator.describe(DataBoundConfigurator.java:221)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:129)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:35)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.Attribute.describe(Attribute.java:179)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.JenkinsConfigurator.describe(JenkinsConfigurator.java:69)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.JenkinsConfigurator.describe(JenkinsConfigurator.java:20)
jenkins-master_1  | 	at org.jenkinsci.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:234)
jenkins-master_1  | 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
jenkins-master_1  | 	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
jenkins-master_1  | 	... 83 more
```

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/334
