### ISSUE TITLE
EC2 plugin "java.lang.NullPointerException" when no userData declared

### ISSUE THREAD

**Issue by yogeek** [jenkinsci/configuration-as-code-plugin#381]
Jenkins Version : 2.121.1
Jenkins CasC version : 0.9-alpha
EC2 plugin : 1.39

When reloading a new EC2 plugin configuration on a live instance, if `userData` field is not set, trying to launch a job leads to the following error :

```
Jul 18, 2018 11:10:04 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting to provision slave from template hudson.plugins.ec2.SlaveTemplate@73c2bb51 needed by excess workload of 1 units of label 'ec2-slave'
Jul 18, 2018 11:10:05 AM INFO hudson.plugins.ec2.SlaveTemplate logProvisionInfo
Considering launching ami-xxx for template EC2 Slave
Jul 18, 2018 11:10:06 AM INFO hudson.plugins.ec2.SlaveTemplate logProvisionInfo
Setting Instance Initiated Shutdown Behavior : ShutdownBehavior.Terminate
Jul 18, 2018 11:10:06 AM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@7870208f failed
java.lang.NullPointerException
	at hudson.plugins.ec2.SlaveTemplate.provisionOndemand(SlaveTemplate.java:547)
	at hudson.plugins.ec2.SlaveTemplate.provision(SlaveTemplate.java:407)
	at hudson.plugins.ec2.EC2Cloud.getNewOrExistingAvailableSlave(EC2Cloud.java:534)
	at hudson.plugins.ec2.EC2Cloud.provision(EC2Cloud.java:551)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:715)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:320)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:61)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:809)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Here is the configuration leading to the error :
```
jenkins:

  clouds:
    - amazonEC2:
        cloudName: "ec2"
        credentialsId: aws_credentials
        privateKey: $PRIVATE_KEY
        templates:
          - description: "EC2 Slave"
            ami: "ami-xxx"
            type: "T2Xlarge"
            securityGroups: "jenkins"
            remoteFS: "/home/jenkins"
            remoteAdmin: "jenkins"
            subnetId: "subnet-xxx"
            labelString: "ec2-slave"
            mode: "NORMAL"
            numExecutors: 4
            tags:
              - name: Name
                value: Jenkins Slave
            #userData: ""
```

And when uncommenting `userData: ""`, the error is gone and the slave instance is created normally.

**Comment by yogeek** [comment]
Already declared in [JENKINS-52319](https://issues.jenkins-ci.org/browse/JENKINS-52319)

**Comment by ndeloof** [comment]
indeed. CasC only can detect required attribute if they are annotated accordingly. Also plugin should handle possible null inputs.
