### ISSUE TITLE
jobs - stopped working 0.9-alpha -> 0.11-alpha

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#391]
Using the [cloudbees folder plugin](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin) version 6.5.1
This very basic job section breaks in 0.11-alpha:
```yaml
jenkins:
[...]
unclassified:
[...]
jobs:
  - >
      folder('system') {
        description('system specific jobs are placed here')
      }
```
The error message is:
```
Jul 20, 2018 10:16:50 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: java.lang.IllegalArgumentException: No org.jenkinsci.plugins.casc.integrations.jobdsl.ScriptSource implementation found for folder('system') {
  description('system specific jobs are placed here')
}
	at org.jenkinsci.plugins.casc.impl.configurators.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:129)
	at org.jenkinsci.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:90)
	at org.jenkinsci.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:42)
	at org.jenkinsci.plugins.casc.integrations.jobdsl.SeedJobConfigurator.configure(SeedJobConfigurator.java:58)
	at org.jenkinsci.plugins.casc.integrations.jobdsl.SeedJobConfigurator.configure(SeedJobConfigurator.java:29)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:491)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:511)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:409)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:159)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:151)
	... 13 more
```

**Comment by jonbrohauge** [comment]
BTW: I've tried to use a `freestylejob` as well with the same error.

**Comment by ndeloof** [comment]
source for script has been updated as https://github.com/jenkinsci/configuration-as-code-plugin/commit/0a75f9dda91b52ecfe97cd597553928d793e6811 so it is more flexible. To pass inline script use:
```yaml
jobs:
  - script: some(groovy).stuff()

```
