### ISSUE TITLE
plugins installation not working

### ISSUE THREAD

**Issue by ewelinawilkosz** [jenkinsci/configuration-as-code-plugin#401]
yaml 
```
plugins:
  required:
    mailer: 1.21
    git: 3.6.0
```

mvn hpi:run
```
(...)
INFO: Augmented all extensions
Jul 26, 2018 3:29:28 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:507)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:419)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:163)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:155)
	... 13 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Can't install mailer:1.21@default: default does not host requested plugin
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:243)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:160)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:82)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:52)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.lambda$configureWith$4(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:501)
	... 17 more

Jul 26, 2018 3:29:28 PM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:507)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:419)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:163)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:155)
	... 13 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Can't install mailer:1.21@default: default does not host requested plugin
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:243)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:160)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:82)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:52)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.lambda$configureWith$4(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:501)
	... 17 more

Jul 26, 2018 3:29:28 PM hudson.model.ComputerSet <clinit>
WARNING: Failed to instantiate NodeMonitors
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:216)
	at hudson.util.FileChannelWriter.write(FileChannelWriter.java:72)
	at java.io.Writer.write(Writer.java:192)
	at hudson.util.AtomicFileWriter.write(AtomicFileWriter.java:162)
	at java.io.Writer.write(Writer.java:157)
	at hudson.XmlFile.write(XmlFile.java:189)
	at hudson.model.ComputerSet$1.save(ComputerSet.java:82)
	at hudson.util.PersistedList.onModified(PersistedList.java:173)
	at hudson.util.PersistedList.replaceBy(PersistedList.java:85)
	at hudson.model.ComputerSet.<clinit>(ComputerSet.java:464)
	at jenkins.metrics.impl.JenkinsHealthCheckProviderImpl.getHealthChecks(JenkinsHealthCheckProviderImpl.java:92)
	at jenkins.metrics.api.Metrics.afterExtensionsAugmented(Metrics.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins$19 onAttained
INFO: Started termination
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins$19 onAttained
INFO: Completed termination
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins _cleanUpDisconnectComputers
INFO: Starting node disconnection
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins _cleanUpShutdownPluginManager
INFO: Stopping plugin manager
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins _cleanUpPersistQueue
INFO: Persisting build queue
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins _cleanUpAwaitDisconnects
INFO: Waiting for node disconnection completion
Jul 26, 2018 3:29:28 PM jenkins.model.Jenkins cleanUp
INFO: Jenkins stopped
```

**Comment by ewelinawilkosz** [comment]
cc @alexsedowa
@ndeloof please comment if you can think of anything :)

**Comment by ndeloof** [comment]
@ewelinawilkosz Just tried this exact same config and works for me
```
juil. 30, 2018 9:40:29 AM hudson.model.UpdateCenter$UpdateCenterConfiguration download
INFOS: Downloading mailer
juil. 30, 2018 9:40:38 AM hudson.model.UpdateCenter$DownloadJob run
INFOS: Starting the installation of git on behalf of SYSTEM
juil. 30, 2018 9:40:39 AM hudson.model.UpdateCenter$UpdateCenterConfiguration download
INFOS: Downloading git
```

I wonder something went wrong on your instance while downloading update center metadata.

That being said I still discovered another issue downloading dependencies as "latest" -> https://github.com/jenkinsci/configuration-as-code-plugin/pull/403

unfortunately we hardly can't write unit test for this feature :'(

**Comment by tomasbjerre** [comment]
I am also seeing this now.

I have my configuration here:
https://github.com/tomasbjerre/docker-jenkins-sandbox/tree/default-does-not-host

And when I do `sudo ./build.sh && sudo ./run.sh` I get:

```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Aug 11, 2018 5:30:53 AM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @336ms to org.eclipse.jetty.util.log.JavaUtilLog
Aug 11, 2018 5:30:53 AM winstone.Logger logInternal
INFO: Beginning extraction from war file
Aug 11, 2018 5:30:54 AM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
Aug 11, 2018 5:30:54 AM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT, build timestamp: 2017-11-21T21:27:37Z, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: DefaultSessionIdManager workerName=node0
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: No SessionScavenger set, using defaults
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.session.HouseKeeper startScavenging
INFO: Scavenging every 660000ms
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started w.@66971f6b{/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@770d0ea6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Aug 11, 2018 5:30:55 AM org.eclipse.jetty.server.Server doStart
INFO: Started @1924ms
Aug 11, 2018 5:30:55 AM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
Aug 11, 2018 5:30:56 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Aug 11, 2018 5:30:56 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Aug 11, 2018 5:30:57 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Aug 11, 2018 5:30:57 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Aug 11, 2018 5:30:57 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Aug 11, 2018 5:30:57 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:507)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:419)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:163)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:155)
	... 13 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Can't install violation-comments-to-gitlab:latest@default: default does not host requested plugin
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:243)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:160)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:82)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:52)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.lambda$configureWith$4(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:501)
	... 17 more

Aug 11, 2018 5:30:57 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1102)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:507)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:419)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:163)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:155)
	... 13 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Can't install violation-comments-to-gitlab:latest@default: default does not host requested plugin
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:243)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:160)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:82)
	at org.jenkinsci.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:52)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.lambda$configureWith$4(ConfigurationAsCode.java:524)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:501)
	... 17 more

Aug 11, 2018 5:30:58 AM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins

```

**Comment by ndeloof** [comment]
@tomasbjerre good catch, I will fix this. Try using a specific version, not "latest"

**Comment by ndeloof** [comment]
see https://github.com/jenkinsci/configuration-as-code-plugin/pull/439

**Comment by etashsingh** [comment]
This error comes up when you use:
```security:
  downloadSettings:
    useBrowser: false```
Remove it to make it work in correct manner.
