### ISSUE TITLE
ToolInstallation fails to load every other restart

### ISSUE THREAD

**Issue by sueastside** [jenkinsci/configuration-as-code-plugin#454]
CasC seems to randomly but rather frequently not be able to load the below configuration during startup.
When changing the configuration and doing a reload in the UI this issue does not seem to appear.

```
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
        at jenkins.model.Jenkins.executeReactor(Jenkins.java:1100)
        at jenkins.model.Jenkins.<init>(Jenkins.java:904)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: single entry map expected to configure a hudson.tools.ToolInstallation
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:79)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:99)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:43)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:291)
        at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:234)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:299)
        at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:234)
        at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:534)
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:499)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:534)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:521)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
        ... 13 more
```

```
tool:
  jdk:
    installations:
      - name: jdk8
        home: D:\SRVDATA\tools\jdk8
        properties:
          - installSource:
              installers:
              - jdkInstaller :
                  id: 'jdk-8u181-oth-JPR'
                  acceptLicense: true
  maven:
    settingsProvider:
      filePath:
        path: D:\SRVDATA\config\Maven\maven-jenkins-settings.xml
    globalSettingsProvider:
      filePath:
        path: D:\SRVDATA\config\Maven\maven-jenkins-settings.xml
    installations:
      - name: maven
        home: D:\SRVDATA\tools\maven
        properties:
          - installSource:
              installers:
              - maven:
                  id: '3.3.9'
```

**Comment by vektory79** [comment]
Seems like an error in the Maven configuration. The next config is more correct:
```yaml
  maven:
    settingsProvider:
      filePath:
        path: D:\SRVDATA\config\Maven\maven-jenkins-settings.xml
    globalSettingsProvider:
      filePath:
        path: D:\SRVDATA\config\Maven\maven-jenkins-settings.xml
    installations:
    - name: maven
      home: D:\SRVDATA\tools\maven
      properties:
      - installSource:
          installers:
          - mavenInstaller:
              id: '3.3.9'
```

**Comment by vektory79** [comment]
But wait... It's not a Maven. It's JDK configuration!
That config:
```yaml
tool:
  jdk:
    installations:
    - jdk:
        name: jdk8
        home: ""
        properties:
        - installSource:
            installers:
            - jdkInstaller:
                id: 'jdk-8u181-oth-JPR'
                acceptLicense: true
```
lead to another error:
```
Aug 24, 2018 5:42:10 PM org.eclipse.jetty.server.handler.ContextHandler$Context log
WARNING: Error while serving http://localhost:8080/configuration-as-code/replace
java.lang.reflect.InvocationTargetException
   at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:347)
   at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
   at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
   at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
   at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
   at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
   at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
   at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
   at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
   at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at hudson.security.HudsonPrivateSecurityRealm$5.doFilter(HudsonPrivateSecurityRealm.java:831)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:42)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
   at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
   at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
   at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:114)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
   at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
   at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
   at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
   at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
   at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   at org.eclipse.jetty.server.Server.handle(Server.java:530)
   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
   at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
Caused by: io.jenkins.plugins.casc.ConfiguratorException: tool: error configuring 'tool' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
   at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:611)
   at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:633)
   at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:539)
   at io.jenkins.plugins.casc.ConfigurationAsCode.doReplace(ConfigurationAsCode.java:168)
   at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
   at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
   ... 94 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: toolInstallation: Failed to set attribute installations(class: class hudson.tools.ToolInstallation, multiple: true)
   at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:308)
   at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:218)
   at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:300)
   at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:218)
   at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:633)
   at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:605)
   ... 99 more
Caused by: java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at io.jenkins.plugins.casc.Attribute._setValue(Attribute.java:294)
   at io.jenkins.plugins.casc.Attribute.setValue(Attribute.java:162)
   at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:306)
   ... 104 more
Caused by: java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lhudson.model.JDK;
   at hudson.model.JDK$DescriptorImpl.setInstallations(JDK.java:174)
   ... 111 more
```
I think, that this is a bug in the casc-plugin logic...

**Comment by vektory79** [comment]
Same error with Mercurial config:
```yaml
tool:
  mercurialinstallation:
    installations:
      - mercurialInstallation:
          name: "Mercurial 3"
          home: ""
          config: |
            [defaults]
            clone = --uncompressed
            bundle = --type none
          executable: "INSTALLATION/bin/hg"
          useCaches: true
          debug: false
          masterCacheRoot: ""
          useSharing: false
          properties:
          - installSource:
              installers:
              - command:
                  toolHome: "mercurial"
                  label: ""
                  command: "[ -d mercurial ] || wget -q -O - http://www.archlinux.org/packages/extra/x86_64/mercurial/download/ | xzcat | tar xvf -"
```

**Comment by vektory79** [comment]
I been goed to rabbit hole. Seems like it is Hazenbug, because both variants of configuration can work or not with sequenced restarts.

Canit be because of inconsistency of casc-plugin dependencies for Jenkins core?

**Comment by ndeloof** [comment]
some toolInstallers do explicitely override `setInstallations(T... installations)` (JDK$DescriptorImpl do define `setInstallations(JDK... jdks)`) which seems to provide a mismatch in computation of the array component type, and an invocation exception during argument cast.

**Comment by vektory79** [comment]
Currently I trying to fix the `setInstallations` concretization issue. But bug with unpredictable entire configuration format is weird and slowdown the process... And I have no idea how to fix it.

**Comment by ndeloof** [comment]
"_unpredictable entire configuration format_" can you please explain what you mean here ?

**Comment by vektory79** [comment]
Format of JDK tool configuration can sporadically switching between two variants from run to run:
```yaml
tool:
  jdk:
    installations:
      - name: jdk8
        home: D:\SRVDATA\tools\jdk8
        properties:
          - installSource:
              installers:
              - jdkInstaller :
                  id: 'jdk-8u181-oth-JPR'
                  acceptLicense: true
```
and
```yaml
tool:
  jdk:
    installations:
    - jdk:
        name: jdk8
        home: ""
        properties:
        - installSource:
            installers:
            - jdkInstaller:
                id: 'jdk-8u181-oth-JPR'
                acceptLicense: true
```
I can use any of this two and from run to run it can or load normally or fail with format errors.

**Comment by ndeloof** [comment]
the later
```yaml
    installations:
    - jdk: ...
```
just seems to be wrong. `intallations:` is key part of a {key,value} pair. so value should get an additional indentation. It is actually a list so starts with a `- `. Not using indentation sounds like an empty value, then another entry, where key is a list (which we don't use, but yaml syntax supports)

**Comment by vektory79** [comment]
@ndeloof Yes. You are right. It's my mistake in configuration. But introduced by IntelliJ IDEA, which format config so.
