### ISSUE TITLE
Plugin management fails with "Cannot find configurator for type class io.jenkins.plugins.casc.plugins.Plugins"

### ISSUE THREAD

**Issue by dp304** [jenkinsci/configuration-as-code-plugin#455]
The [example in the readme](https://github.com/jenkinsci/configuration-as-code-plugin#plugin-management) for plugin installation with the CasC plugin
```yaml
plugins:
  required:
    git: 3.9.0
    warnings: 4.67
```
fails to work with 1.0-rc1, although the support plugin is also installed.
Such a code used to work with 0.11-alpha.
Jenkins version is 2.121.2. See [output log](https://github.com/jenkinsci/configuration-as-code-plugin/files/2293408/jenkinscascpluginerror.txt).

**Comment by anwoolterton** [comment]
yep I am seeing the same issue as this, have not found a workaround for it :(

from k8s configmap

  init_plugins.yaml: |
    plugins:
      required:
        - chucknorris: latest

io.jenkins.plugins.casc.ConfiguratorException: Cannot find configurator for type class io.jenkins.plugins.casc.plugins.Plugins
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:97)
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:93)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry.lookupOrFail(DefaultConfiguratorRegistry.java:70)
	at io.jenkins.plugins.casc.ConfigurationContext.lookupOrFail(ConfigurationContext.java:74)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:283)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:234)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:499)
Caused: io.jenkins.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class io.jenkins.plugins.casc.plugins.PluginManagerConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:505)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:521)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1100)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)

**Comment by ndeloof** [comment]
PluginManager has to implement `check`
