### ISSUE TITLE
can't create credentials

### ISSUE THREAD

**Issue by HerrmannHinz** [jenkinsci/configuration-as-code-plugin#464]
hallo,

using jcasc rc1 here: `configuration-as-code:1.0-rc1`
jenkins version: `"2.138-alpine"`

## plugins installed via helm
```
  InstallPlugins:
      - kubernetes:latest
      - kubernetes-credentials:latest
      - configuration-as-code:1.0-rc1
      - workflow-aggregator:latest
      - workflow-job:latest
      - credentials-binding:latest
      - credentials:latest
      - git:latest
      - keycloak:latest
      - pipeline-input-step:latest
      - config-file-provider:latest
      - slack:latest
      - cloudbees-bitbucket-branch-source:2.2.12 # js-shared-lib dep
      - bitbucket:1.1.8 # js-shared-lib dep
      - workflow-cps-global-lib:2.9 # js-shared-lib dep
      - envinject:2.1.6 # js-shared-lib dep
      - job-dsl:1.70 # js-shared-lib dep
      - branch-api:2.0.20 # js-shared-lib dep
      - email-ext:2.63 # js-shared-lib dep
```

## jenkins.yaml
``` 
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-ci02-agent:50000"
      jenkinsUrl: "http://jenkins-ci02:8080"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      namespace: "jenkins-ci02"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "${computer.jnlpmac} ${computer.name}"
          envVars:
          - containerEnvVar:
              key: "JENKINS_URL"
              value: "http://jenkins-ci02:8080"
          image: "jenkins/jnlp-slave:3.23-1-alpine"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          privileged: true
          resourceLimitCpu: "200m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "200m"
          resourceRequestMemory: "512Mi"
        label: "jenkins-ci02-jenkins-slave"
        name: "default"
        nodeUsageMode: "NORMAL"
        workspaceVolume:
          emptyDirWorkspaceVolume:
            memory: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  mode: NORMAL
  noUsageStatistics: true
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  systemMessage: "ci02"
  views:
  - all:
      name: "all"
unclassified:
  bitbucketendpointconfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
    - bitbucketServerEndpoint:
        displayName: "https://xxxx.xxxx.com"
        manageHooks: false
        serverUrl: "https://xxxx.xxxx.com"
  globallibraries:
    libraries:
    - name: "paas-shared-lib-java"
      defaultVersion: "feature/cic8s-new-urls"
      implicit: true
      retriever:
        modernSCM:
          scm:
            git:
              credentialsId: "cin-ci-sharedlib"
              id: "paas-shared-lib-java"
              remote: "https://xxxx.xxxx.xxxxx/scm/ow-paas/jenkins-shared-library-java.git"
              traits:
              - headWildcardFilter:
                  includes: "feature/cic8s-new-urls"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope:    global
              id:       cin-ci-sharedlib
              username: cin-ci-sharedlib
              password: mysupersecretpassword      
``` 

## stack trace
``` 
Aug 20, 2018 11:52:22 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: No configurator for root element <credentials>
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:513)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:521)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
	... 13 more

Aug 20, 2018 11:52:22 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1100)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: No configurator for root element <credentials>
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:513)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:521)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:161)
	... 13 more
``` 

any idea?

**Comment by themysteq** [comment]
You have to install also `configuration-as-code-support` as mentioned in https://wiki.jenkins.io/display/JENKINS/Configuration+as+Code+Plugin

**Comment by HerrmannHinz** [comment]
@themysteq ahh! this seems to solve the problem. nice. thank you. 
will close the ticket now.
