### ISSUE TITLE
No configurator implementation to manage class hudson.security.GlobalMatrixAuthorizationStrategy

### ISSUE THREAD

**Issue by avalery** [jenkinsci/configuration-as-code-plugin#469]
Hello,

When I use this configuration for authorizationStrategy:

```yaml
jenkins:
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
```

Which is an example provided on this demo page (https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/global-matrix-auth), I get the following error:

> java.lang.IllegalStateException: No configurator implementation to manage class hudson.security.GlobalMatrixAuthorizationStrategy
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:93)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:99)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:299)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:234)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:499)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:534)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:521)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:433)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:169)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doReload(ConfigurationAsCode.java:147)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)

Is there something I missed...?

**Comment by casz** [comment]
"WARNING: Lots of functionality and integrations with other plugins was moved to a separate plugin for the first official RC. Please install: configuration-as-code-support plugin from the update center"

https://wiki.jenkins.io/display/JENKINS/configuration+as+code+plugin#ConfigurationasCodePlugin-1.0-rc1(10.08.2018)

**Comment by jonbrohauge** [comment]
@avalery 
This works for me:
```
jenkins:
 authorizationStrategy:
    globalMatrix:
      grantedPermissions:
            - "Overall/Read:anonymous"
```
I have configuration-as-code + configuration-as-code-support installed, both 1.0-RC1

**Comment by avalery** [comment]
Ah yes it's because I don't have configuration-as-code-support installed! It's working now. Thank you :)
