### ISSUE TITLE
Problem while reading 'plugins.txt' if plugin is defined without a version

### ISSUE THREAD

**Issue by srempfer** [jenkinsci/configuration-as-code-plugin#475]
Problem while reading 'plugins.txt' if plugin is defined without a version

```
jenkins    | Aug 25, 2018 2:28:57 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins    | SEVERE: Failed ConfigurationAsCode.init
jenkins    | java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins    |    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins    |    at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins    |    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins    |    at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins    |    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins    |    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins    |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins    |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins    |    at java.lang.Thread.run(Thread.java:748)
jenkins    | Caused by: java.lang.reflect.InvocationTargetException
jenkins    |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins    |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins    |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins    |    at java.lang.reflect.Method.invoke(Method.java:498)
jenkins    |    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins    |    ... 8 more
jenkins    | Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
jenkins    |    at java.lang.String.substring(String.java:1967)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.readShrinkwrapFile(PluginManagerConfigurator.java:322)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:139)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:88)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:58)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:633)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:605)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:633)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:539)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
jenkins    |    ... 13 more
```

This happens if a custom Jenkins Docker image is built with pre-installed plugins (https://github.com/jenkinsci/docker#script-usage) and a configuration for the plugins proxy is provided.

```
plugins:
  proxy:
    name: 192.168.0.252
    port: 9090`
```

Reason is that the install script treats the version part as optional (https://github.com/jenkinsci/docker/blob/master/install-plugins.sh => version="${2:-latest}" ) but the PluginManagerConfigurator not

Even if a version is specified startup fails because the update site is not yet up to date and so the plugin is unknown

```
jenkins    | SEVERE: Failed ConfigurationAsCode.init
jenkins    | java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins    |    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins    |    at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins    |    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins    |    at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
jenkins    |    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins    |    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins    |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins    |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins    |    at java.lang.Thread.run(Thread.java:748)
jenkins    | Caused by: java.lang.reflect.InvocationTargetException
jenkins    |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins    |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins    |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins    |    at java.lang.reflect.Method.invoke(Method.java:498)
jenkins    |    at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins    |    ... 8 more
jenkins    | Caused by: io.jenkins.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class io.jenkins.plugins.casc.plugins.PluginManagerConfigurator configurator
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:611)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:633)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:539)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
jenkins    |    ... 13 more
jenkins    | Caused by: io.jenkins.plugins.casc.ConfiguratorException: update site default isn't hosting plugin git
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:257)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:166)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:88)
jenkins    |    at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:58)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:633)
jenkins    |    at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:605)
jenkins    |    ... 17 more
```

Jenkins version: 2.121.3
Plugin version: 1.0-rc2
OS: Custom Docker image based on jenkins/jenkins:lts

**Comment by srempfer** [comment]
I found out that the proxy and update sites are only configured if a configuration is provided.

This is different for the plugins. The method ‘readShrinkwrapFile’ is called whether or not a plugin configuration is provided. 

https://github.com/jenkinsci/configuration-as-code-plugin/blob/464aa9fb1ec97ca8889f47ed38c75d8a54b8aa58/plugin/src/main/java/io/jenkins/plugins/casc/plugins/PluginManagerConfigurator.java#L130-L144

Is there a reason for? If not, I would change this and fill a PR.

**Comment by ndeloof** [comment]
This is by intent : 
while the docker image install-script is designed to build immutable docker images (so resolving a plugin to "latest" just result into packaging a specific plugin version into docker image) configuration-as-code is designed to enforce reproducibility, and as such **require** a version for plugins.

**Comment by srempfer** [comment]
OK, thanks for the explanation why the plugin version is not treated as optional.

One question I still want to ask you:

Scenario 1:
`No configuration is provided`
=> readShrinkwrapFile is not called because PluginManagerConfigurator is not involved

Scenario 2:
`
jenkins:
  securityRealm:
    (...)
`
=> readShrinkwrapFile is not called because PluginManagerConfigurator is not involved

Scenario 2:
`
plugins:
  proxy:
    (...)
`
=> readShrinkwrapFile is called because PluginManagerConfigurator is involved

Scenario 4:
`
plugins:
  required:
    (...)
`
 => readShrinkwrapFile is called because PluginManagerConfigurator is involved


Is the call of readShrinkwrapFile() in Scenario 2 even if no configuration for required plugins is provided also by intent?

**Comment by ndeloof** [comment]
readShrinkwrapFile should indeed be loaded in all scenarios, but not trivial to implement in current design
