### ISSUE TITLE
Jenkins down after installing plugin

### ISSUE THREAD

**Issue by mwarkentin** [jenkinsci/configuration-as-code-plugin#479]
Hello,

I decided to give this plugin a try on our dev jenkins instance - after installing it and restarting Jenkins I am receiving the following error on all screens (jenkins completely inaccessible).

I believe these are the versions installed but since I can't access the instance I can't verify 100%:

* Jenkins 2.107.3
* CasC plugin: 1.0-rc2 (23.08.2018)
* Operating system: Alpine Linux

```
java.lang.IllegalStateException: Expected 1 instance of hudson.PluginManager$PluginUpdateMonitor but got 0
	at hudson.ExtensionList.lookupSingleton(ExtensionList.java:436)
	at hudson.PluginManager$PluginUpdateMonitor.getInstance(PluginManager.java:2015)
	at hudson.maven.PluginImpl.init(PluginImpl.java:58)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1062)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1096)
	at jenkins.model.Jenkins.<init>(Jenkins.java:900)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

**Comment by ndeloof** [comment]
Sounds like you had an earlier error to prevent jenkins to start some required components. Please check your jenkins log.

**Comment by ndeloof** [comment]
@mwarkentin can you please double check your startup logs and share here any warning reported to help us understand what's going wrong on your installation and how CasC might have caused this ?

**Comment by mwarkentin** [comment]
Hi @ndeloof, sorry about the delay - here's the logs I get when restarting our jenkins docker container - maybe these are more useful to you: https://gist.github.com/mwarkentin/e047fdc495a9a292c110c561bc2984e6

I'm not sure if anything here references the configuration as code plugin.

**Comment by mwarkentin** [comment]
@ndeloof I confirmed that after removing the plugin and restarting jenkins that it started up successfully.

**Comment by mwarkentin** [comment]
What determines whether something is a "real" master? Happy to look into specific configuration options that we have set, etc. to help figure this out.

**Comment by mwarkentin** [comment]
Gotcha - definitely not doing that!

**Comment by mwarkentin** [comment]
@ndeloof just wondering if any ideas on what might've happened have occurred to you? Is it worth testing again now that 1.0 (and 1.1) are out?

Thanks!

**Comment by ndeloof** [comment]
I have no idea what could have caused this, so have no idea if this was a side effect for some bug we could have fixed in the meantime. Giving it a try would for suer help :)

**Comment by mwarkentin** [comment]
Sounds good, I'll let you know if the issue persists!
