### ISSUE TITLE
Stackoverflow in export

### ISSUE THREAD

**Issue by patope** [jenkinsci/configuration-as-code-plugin#494]
Tried to export our current jenkins configuration, but it failed due stackoverflow. 

```
Error while serving https://[our.jenkins]/configuration-as-code/export
java.lang.StackOverflowError
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:819)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1282)
	at sun.misc.URLClassPath$FileLoader.findResource(URLClassPath.java:1249)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:215)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at org.eclipse.jetty.webapp.WebAppClassLoader.getResource(WebAppClassLoader.java:447)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1091)
	at hudson.util.MaskingClassLoader.getResource(MaskingClassLoader.java:82)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1091)
	at jenkins.util.AntClassLoader.getResource(AntClassLoader.java:889)
	at org.kohsuke.stapler.ClassDescriptor$ASM.loadParametersFromAsm(ClassDescriptor.java:346)
	at org.kohsuke.stapler.ClassDescriptor$ASM.access$100(ClassDescriptor.java:300)
	at org.kohsuke.stapler.ClassDescriptor.loadParameterNames(ClassDescriptor.java:233)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:231)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:132)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:188)
	at io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:337)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:247)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:132)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:184)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:253)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:132)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:188)
	at io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:337)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:247)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:132)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:184)
```

**Comment by ndeloof** [comment]
@patope which version are you using ?
Can you please try latest build (downloadable from https://ci.jenkins.io/job/Plugins/job/configuration-as-code-plugin/job/master/) to confirm this still happens with current codebase.

**Comment by patope** [comment]
That resolved stackoverflow issue, but i got two stacktraces on export instead.
one for `unclassified.jiraprojectproperty`
```
  jiraprojectproperty:
    sites: "FAILED TO EXPORT hudson.plugins.jira.JiraProjectProperty$DescriptorImpl#sites:\
      \ \nio.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'url'\
      \ from [Lhudson.plugins.jira.JiraSite;@6a030384\n\tat io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:246)\n\
      \tat io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:166)\n\tat io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:237)\n\
      \tat io.jenkins.plugins.casc.Attribute.describe(Attribute.java:188)\n\tat io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:368)\n\
```
and other one for `tool.gradle`
```
  gradle: "FAILED TO EXPORT hudson.plugins.gradle.GradleInstallation$DescriptorImpl\
    \ : \nio.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'installations'\
    \ from hudson.plugins.gradle.GradleInstallation$DescriptorImpl@15475c3e\n\tat\
    \ io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:252)\n\tat io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:166)\n\
    \tat io.jenkins.plugins.casc.Attribute.equals(Attribute.java:199)\n\tat io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:367)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator.describe(DescriptorConfigurator.java:65)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:94)\n\
```

**Comment by ndeloof** [comment]
jira issue is a known one https://issues.jenkins-ci.org/browse/JENKINS-52906

**Comment by shaunsmiley-rms** [comment]
jenkins ver: 2.121.3
plugin ver: 1.0-rc2

I'm getting the same gradle error, which shows up in the export yaml.
