### ISSUE TITLE
What happened to unclassified->mailer->smtpHost?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/configuration-as-code-plugin#503]
Having:
Jenkins: 2.140
JCASC + Support: 1.0-rc3
mailer: 1.21

I get this:
```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.tasks.Mailer$DescriptorImpl : smtpHost
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:355)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:265)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:330)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:265)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:640)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:605)
Caused: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:611)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:640)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:627)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:539)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1066)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1100)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

Using `JCASC + Support: 1.0-rc2` _mailer_ works.
After disabling the _mailer_ configuration, I can see that the configuration item _smtpHost_ has disappeared.

Screenshot taken from `JCASC + Support: 1.0-rc2`:
![image](https://user-images.githubusercontent.com/9496731/45285236-fd4b9e00-b4e2-11e8-9177-a0f7fe536122.png)

Screenshot taken from `JCASC + Support: 1.0-rc3`:
![image](https://user-images.githubusercontent.com/9496731/45285162-cbd2d280-b4e2-11e8-9f1d-9bebf00ea5e7.png)

**Comment by jonbrohauge** [comment]
I can see that the integration test takes this change into account:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/src/test/resources/io/jenkins/plugins/casc/MailerTest.yml

**Comment by jonbrohauge** [comment]
I guessing this is the root cause: https://issues.jenkins-ci.org/browse/JENKINS-53467

**Comment by ndeloof** [comment]
@jonbrohauge this "regression" was introduced as we discovered we need to exclude setters which don't have a matching getter, and introduce false positive in our model-discovery logic.

https://issues.jenkins-ci.org/browse/JENKINS-53467 is indeed logged for a correct fix on mailer-plugin, I'm also waiting for https://github.com/jenkinsci/mailer-plugin/pull/39 to be merged as a more generic fix
