### ISSUE TITLE
IvyBuildTrigger compatibility issue

### ISSUE THREAD

**Issue by dclem-23andme** [jenkinsci/configuration-as-code-plugin#515]
The IvyBuildTrigger plugin seems to not be compatible. There is a stacktrace (pasted below) in the YAML export when this plugin is installed.

Jenkins version: 2.141
OS: Debian 9.5 (official Jenkins Docker image)
Plugin version: 1.28

Stacktrace:

```
  ivybuildtrigger: "FAILED TO EXPORT hudson.ivy.IvyBuildTrigger$DescriptorImpl : \n\
    java.lang.IllegalAccessException: Class io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator\
    \ can not access a member of class hudson.ivy.IvyBuildTrigger$DescriptorImpl with\
    \ modifiers \"\"\n\tat sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)\n\
    \tat java.lang.Class.newInstance(Class.java:436)\n\tat io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator.describe(DescriptorConfigurator.java:64)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:94)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$6(GlobalConfigurationCategoryConfigurator.java:87)\n\
    \tat java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)\n\
    \tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\
    \tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\
    \tat java.util.Iterator.forEachRemaining(Iterator.java:116)\n\tat java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)\n\
    \tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)\n\t\
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\
    \tat java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)\n\
    \tat java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)\n\
    \tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\t\
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)\n\t\
    at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:87)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:30)\n\
    \tat io.jenkins.plugins.casc.ConfigurationAsCode.export(ConfigurationAsCode.java:406)\n\
    \tat io.jenkins.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:396)\n\
    \tat java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)\n\
    \tat org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)\n\t\
    at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)\n\
    \tat org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)\n\
    \tat org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)\n\tat org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)\n\
    \tat org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)\n\tat org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)\n\
    \tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)\n\
    \tat org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)\n\
    \tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)\n\
    \tat org.kohsuke.stapler.Stapler.service(Stapler.java:238)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\
    \tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)\n\t\
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)\n\
    \tat net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)\n\
    \tat net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)\n\
    \tat net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)\n\
    \tat org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:114)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)\n\tat\
    \ hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\t\
    at org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:52)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)\n\t\
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)\n\
    \tat hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)\n\
    \tat hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)\n\
    \tat hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\
    \tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)\n\
    \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\
    \tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\
    \tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\
    \tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\
    \tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\
    \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
    \tat org.eclipse.jetty.server.Server.handle(Server.java:531)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)\n\
    \tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)\n\
    \tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)\n\
    \tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\
    \tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\
    \tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)\n\
    \tat org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)\n\
    \tat java.lang.Thread.run(Thread.java:748)\n"
```

**Comment by ewelinawilkosz** [comment]
Please report a jira issue on that plugin, adding tag jcasc-compatibility.

**Comment by ndeloof** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-53570

**Comment by darxriggs** [comment]
@dclem-23andme, your issue description says "Plugin version: 1.28". What's this about?
I am asking because the latest version is 0.34 - see https://wiki.jenkins.io/display/JENKINS/IvyTrigger+Plugin.

I could **not reproduce** this issue with Jenkins 2.141, JCasC plugin 1.4, IvyTrigger plugin 0.34.

Could you please provide more details (preferable directly in the created Jira issue [JENKINS-53570](https://issues.jenkins-ci.org/browse/JENKINS-53570))?

**Comment by darxriggs** [comment]
Now I found out, what was mixed-up.

The reported class `IvyBuildTrigger` is part of the [Ivy](https://wiki.jenkins.io/display/JENKINS/Ivy+Plugin) plugin, not the [IvyTrigger](https://wiki.jenkins.io/display/JENKINS/IvyTrigger+Plugin) plugin.

@ndeloof, I updated the component in [JENKINS-53570](https://issues.jenkins-ci.org/browse/JENKINS-53570) accordingly.
