### ISSUE TITLE
reverse-proxy-auth-plugin plugin support

### ISSUE THREAD

**Issue by er1c** [jenkinsci/configuration-as-code-plugin#521]
I would like to use the `reverse-proxy-auth-plugin:latest` (https://plugins.jenkins.io/reverse-proxy-auth-plugin) for the `securityRealm`.

I'm not sure if this needs more explicit configuration support.

```
jenkins:

  securityRealm:
    reverse-proxy-auth:
      forwardedUser: "X-Forwarded-User"
```

```
Caused by: java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for reverse-proxy-auth
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:142)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:93)
```

a config.xml looks something like:

```
  <securityRealm class="org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm" plugin="reverse-proxy-auth-plugin@1.6.3">
    <proxyTemplate/>
    <authContext>
      <entry>
        <string>eric</string>
        <org.acegisecurity.GrantedAuthority-array>
          <org.acegisecurity.GrantedAuthorityImpl>
            <role>authenticated</role>
          </org.acegisecurity.GrantedAuthorityImpl>
        </org.acegisecurity.GrantedAuthority-array>
      </entry>
...
    </authContext>
    <authorityUpdateCache/>
    <inhibitInferRootDN>false</inhibitInferRootDN>
    <userSearchBase></userSearchBase>
    <userSearch>uid={0}</userSearch>
    <updateInterval>15</updateInterval>
    <forwardedUser>X-Forwarded-User</forwardedUser>
    <retrievedUser>eric</retrievedUser>
    <headerGroups>X-Forwarded-Groups</headerGroups>
    <headerGroupsDelimiter>|</headerGroupsDelimiter>
    <disableLdapEmailResolver>false</disableLdapEmailResolver>
    <displayNameLdapAttribute></displayNameLdapAttribute>
    <emailAddressLdapAttribute></emailAddressLdapAttribute>
  </securityRealm>

```

**Comment by er1c** [comment]
I think I got this to work via:

```
  securityRealm:
    ReverseProxySecurityRealm:
      forwardedUser: "X-Forwarded-User"
```

```
Sep 14, 2018 8:32:57 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm.forwardedUser = X-Forwarded-User
Sep 14, 2018 8:32:57 PM io.jenkins.plugins.casc.BaseConfigurator configure
INFO: Setting hudson.model.Hudson@770ac4de.authorizationStrategy = hudson.security.AuthorizationStrategy$Unsecured@4cff3af5
Sep 14, 2018 8:32:57 PM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm.forwardedUser = X-Forwarded-User
Sep 14, 2018 8:32:57 PM io.jenkins.plugins.casc.BaseConfigurator configure
INFO: Setting hudson.model.Hudson@770ac4de.securit
```

By looking at the code, I was able to see the name `ReverseProxySecurityRealm` for the class https://github.com/jenkinsci/reverse-proxy-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/reverse_proxy_auth/ReverseProxySecurityRealm.java
