### ISSUE TITLE
NullPointerException if yaml file is empty

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#548]
If I have:

```
/var/jenkins_home/casc_configs/casc.yaml
CASC_JENKINS_CONFIG="/var/jenkins_home/casc_configs"
```
and `casc.yaml` is empty, then I get this error on startup:

```
java.lang.NullPointerException
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:627)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:540)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
```

using version 1.0.

**Comment by ndeloof** [comment]
corner case :)
