### ISSUE TITLE
Exception if configuration dir does not exist

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#549]
If I have:
```
CASC_JENKINS_CONFIG="/var/jenkins_home/casc_configs"
```
but the directory doesn't exist, Jenkins startup fails with this error:
```
java.nio.file.NoSuchFileException: /var/jenkins_home/casc_configs
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72)
	at java.nio.file.Files.find(Files.java:3687)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configs(ConfigurationAsCode.java:565)
Caused: io.jenkins.plugins.casc.ConfiguratorException: File does not exist: /var/jenkins_home/casc_configs
	at io.jenkins.plugins.casc.ConfigurationAsCode.configs(ConfigurationAsCode.java:569)
	at io.jenkins.plugins.casc.ConfigurationAsCode.getStandardConfigSources(ConfigurationAsCode.java:280)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
```

It could just log an error and startup with no configuration read.

**Comment by ndeloof** [comment]
`NoSuchFileException: /var/jenkins_home/casc_configs` is pretty obvious about the cause for this failure.

> It could just log an error and startup with no configuration read

which could result in jenkins being partially configured without security enabled, something we definitively can't support.

using *-as-code principle assume the configuration is always valid and has been validated in some test/staging environment, you should not directly edit your yaml files and try on production.

**Comment by martinmosegaard** [comment]
OK. Maybe we could improve the error message to saying that CasC expected the folder to exist because of the environment variable? Instead of just a builtin exception.
