### ISSUE TITLE
Exception with no message if yaml indentation is wrong

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/configuration-as-code-plugin#550]
I had a yaml file declaring a global library, but the indentation was wrong:

```
unclassified:
    globalLibraries:
    libraries:
      - name: "awesome-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/jenkins-infra/pipeline-library.git"
```
- the error is that `libraries` should be nested under `globalLibraries`.

This makes Jenkins startup fail with a NullPointerException:

```
java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:12)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:73)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:73)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:627)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:540)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:262)
```

It should at most log an error that the desired configuration cannot be applied - and preferably let me know why. But it should not prevent startup.

**Comment by ndeloof** [comment]
Error reporting and diagnostic message is indeed a neglected aspect of this plugin (see #542)

> But it should not prevent startup.

I disagree on this point. Bad configuration should not be ignored. Configuration applied to a production jenkins master should always have been validated before being applied. The risk to get jenkins in some weird state without control has way too much impacts on security and stability.

**Comment by ndeloof** [comment]
closing as we plan to address usability in diagnostic message in #542
