### ISSUE TITLE
Mesos plugin fails when new jenkins instance rolls out

### ISSUE THREAD

**Issue by angry-cellophane** [jenkinsci/configuration-as-code-plugin#578]
### Setup:
jenkins 2.121.3
configuration-as-code 1.0
configuration-as-code-support 1.0
mesos 0.18.1

Conf file
```yaml
jenkins:
  clouds:
  - mesos:
      checkpoint: true
      credentialsId: "MY_CREDS"
      declineOfferDuration: "600000"
      frameworkName: "my-name"
      master: "zk://leader.mesos"
      nativeLibraryPath: "path_to_lib"
      onDemandRegistration: false
      principal: ${MESOS_PRINCIPAL}
      role: ${MESOS_ROLE}
      slaveInfos:
      - defaultSlave: false
        diskNeeded: 0.0
        executorCpus: 2.1
        executorMem: 2048
        slaveCpus: 2.0
        slaveMem: 2048
        idleTerminationMinutes: 3
        jnlpArgs: "-noReconnect"
        jvmArgs: "-Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true"
        labelString: "java"
        maxExecutors: 1
        minExecutors: 1
        mode: EXCLUSIVE
        remoteFSRoot: jenkins
        containerInfo:
          type: DOCKER
          dockerImage: "my_image"
          networking: BRIDGE
          dockerPrivilegedMode: false
          dockerForcePullImage: false
          dockerImageCustomizable: false
      slavesUser: user_name
unclassified:
  location:
    adminAddress: admin@mail.com
    url: ${DYNAMIC_JENKINS_URL}
```

### Issue:
If you kick off a new jenkins instance with empty $JENKINS_HOME the instance will fail with an exception and stop.

```
Oct 05, 2018 5:11:17 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init                                                                                                                                     
java.lang.Error: java.lang.reflect.InvocationTargetException                                                                                                                
Caused by: java.lang.reflect.InvocationTargetException                                                                                                                     
Caused by: io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator     
Caused by: io.jenkins.plugins.casc.ConfiguratorException: mesos: Failed to construct instance of class org.jenkinsci.plugins.mesos.MesosCloud.                              
 Constructor: public org.jenkinsci.plugins.mesos.MesosCloud(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.List,boolean,boolean,boolean,java.lang.String,java.lang.String,java.lang.String) throws java.lang.NumberFormatException. 
 Arguments: [java.lang.String, java.lang.String, null, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, null, java.util.ArrayList, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, null, java.lang.String, null] 
Caused by: java.lang.reflect.InvocationTargetException                                                                                                                      
Caused by: java.lang.IllegalArgumentException: Cannot start scheduler if jenkinsMaster is null                                                                              
Oct 05, 2018 5:11:17 PM hudson.util.BootFailure publish                                                           
SEVERE: Failed to initialize Jenkins                                           
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException                                                                                                    
Caused by: java.lang.reflect.InvocationTargetException                                                                                           
Caused by: io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator     
Caused by: io.jenkins.plugins.casc.ConfiguratorException: mesos: Failed to construct instance of class org.jenkinsci.plugins.mesos.MesosCloud.                              
 Constructor: public org.jenkinsci.plugins.mesos.MesosCloud(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.List,boolean,boolean,boolean,java.lang.String,java.lang.String,java.lang.String) throws java.lang.NumberFormatException. 
 Arguments: [java.lang.String, java.lang.String, null, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, null, java.util.ArrayList, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, null, java.lang.String, null]
 at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:150)
 at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:74)
 at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:248)
 at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:80)
 at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:96)
 at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:101)
 at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:43)
 at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:322)
 at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:265)
 at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:641)
 at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:606)
 ... 18 more
Caused by: java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:142)
 ... 28 more
Caused by: java.lang.IllegalArgumentException: Cannot start scheduler if jenkinsMaster is null
 at org.jenkinsci.plugins.mesos.MesosImpl.startScheduler(MesosImpl.java:14)
 at org.jenkinsci.plugins.mesos.MesosCloud.restartMesos(MesosCloud.java:347)
 at org.jenkinsci.plugins.mesos.MesosCloud.<init>(MesosCloud.java:216)
 at org.jenkinsci.plugins.mesos.MesosCloud.<init>(MesosCloud.java:166)
 ... 33 more
```

My understanding it fails at this point in mesos plugin - https://github.com/jenkinsci/mesos-plugin/blob/mesos-0.18.1/src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java#L347

Because jenkins location is not set yet.
As a workaround it is possible to change the mesos config  to override the url - https://github.com/jenkinsci/mesos-plugin/blob/mesos-0.18.1/src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java#L334

```yaml
  clouds:
  - mesos:
      jenkinsURL: ${JENKINS_URL}
```

It looks like a race to me.

Please can anyone confirm if it's an issue? Also it would be glad to clarify the order the plugin applies the config's items.

**Comment by casz** [comment]
This is how you set the JENKINS URl

https://github.com/jenkinsci/configuration-as-code-plugin/blob/ff8074f852135f41b24cac460e23c74e203a8fc1/demos/jenkins/jenkins.yaml#L68-L70

**Comment by angry-cellophane** [comment]
@casz the location property you pointed to is in the snippet at the bottom.
The issue is that the mesos config is applied before location

**Comment by ndeloof** [comment]
@angry-cellophane nothing we can do here, as both CasC and MesosCloud.init are initializers, and as a result we get such a race condition.

It seems a possible workaround for this specific issue is to set `jenkinsURL` in MesosCloud yaml.

**Comment by ndeloof** [comment]
for the record, this is related to https://github.com/jenkinsci/configuration-as-code-plugin/issues/280

**Comment by angry-cellophane** [comment]
@ndeloof thank you.
Adding a note about this issue in docs or the mesos demo could probably save other users' time.
I can do it if no one minds.

**Comment by oleg-nenashev** [comment]
It is possible to prevent race conditions by introducing new Init
milestones in the Jenkins Core.
E.g. https://github.com/jenkinsci/configuration-as-code-plugin/issues/280

It is not that difficult to implement.

**Comment by ndeloof** [comment]
@angry-cellophane please help us improve the demo, some real world usage is the best way to ensure it's offering a valid sample config

**Comment by ndeloof** [comment]
closing as duplicate for #280
