### ISSUE TITLE
jenkins.noUsageStatistics throws exception

### ISSUE THREAD

**Issue by angry-cellophane** [jenkinsci/configuration-as-code-plugin#579]
jenkins 2.121.3
configuration-as-code 1.0
configuration-as-code-support 1.0

config file
```yaml
jenkins:
  noUsageStatistics: true
```
noUsageStatistics in jenkins.model.Jenkins https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L810

Jenkins cannot load the config and throws an exception 
```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.model.Jenkins : noUsageStatistics
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:355)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:265)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:641)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:606)
Caused: io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:612)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:641)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:628)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:540)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:270)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doReload(ConfigurationAsCode.java:151)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
```

**Comment by casz** [comment]
Should be according to the reference schema: http://JENKINS_URL/configuration-as-code/reference

```yml
unclassified:
  usagestatistics: false
```

However it throws another exception
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:630)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:517)
	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:31)
	... 5 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Item isn't a Mapping
	at io.jenkins.plugins.casc.model.CNode.asMapping(CNode.java:18)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:262)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:329)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:264)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	... 10 more
```

**Comment by ndeloof** [comment]
Jenkins.setNoUsageStatistics exists but there's no getNoUsageStatistics so this attribute is excluded from the introspected data model

I don't know why we get  usagestatistics for "unclassified" element, this suggest some descriptor declare this symbol, I can't find it.

**Comment by ndeloof** [comment]
so, after a debug session:
`unclassified : usageStatistic` points to hudson.model.UsageStatistics (a PageDecorator, and as such a Descriptor) which has a global jelly view to let user configure `usageStatisticsCollected` attribute. So as expected this guy is part of the available configuration.
But this is not a boolean attribute, this is a nested data structure, that one would like to use to set 
`usageStatisticsCollected`. BUT there's no getter/setter for this purpose. So actually no way to control this feature

**Comment by casz** [comment]
Seems like only usage statistic is handled via java launch parameter.
https://jenkins.io/blog/2016/03/30/usage-statistics-privacy-advisory/
