### ISSUE TITLE
AzureVM cloud plugin can't convert descriptor to yaml

### ISSUE THREAD

**Issue by timja** [jenkinsci/configuration-as-code-plugin#581]
Hi

I started on the azure vm agents plugin (https://github.com/jenkinsci/azure-vm-agents-plugin) trying to make the export work 

I made some progress on that, but got stuck trying to add an [AzureVMCloudRetensionStrategy](https://github.com/jenkinsci/azure-vm-agents-plugin/blob/f72794484a031e5556a4dc5ba2fbde115670d7a5/src/main/java/com/microsoft/azure/vmagent/AzureVMCloudRetensionStrategy.java#L31) to the [yaml](https://github.com/timja/azure-vm-agents-plugin/blob/configuration-as-code-export-compat/src/test/resources/configuration-as-code.yml#L41) definition

[candidates](https://github.com/jenkinsci/configuration-as-code-plugin/blob/5bd56df3080e012b5491388b5c8e7a6310723637/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/HeteroDescribableConfigurator.java#L91)

Returns null with: `class com.microsoft.azure.vmagent.AzureVMCloudBaseRetentionStrategy` as the argument [AzureVMCloudBaseRetentionStrategy](https://github.com/jenkinsci/azure-vm-agents-plugin/blob/fb837a3b410b9d30dc6e6f3218d46521793fb8f0/src/main/java/com/microsoft/azure/vmagent/AzureVMCloudBaseRetentionStrategy.java#L10) is the base class for the retention strategy it doesn't have a descriptor on it but the sub classes do.

What can I do here?
Is there a way to do this now, or does:
1. configuration-as-code need a change to support it
2. azure vm clouds need a change
3. don't use the automatic binding in this plugin and implement a custom mapping, may be a good option as this plugin suggest that people use a [builder](https://github.com/jenkinsci/azure-vm-agents-plugin#configure-vm-template-using-groovy-script) for constructing it with lots of defaults set that wouldn't be set with automatic binding.

My branch can be found at:
https://github.com/timja/azure-vm-agents-plugin/tree/configuration-as-code-export-compat

The final stacktrace that happens is, but that happens because there is no target found:
```
java.lang.IllegalArgumentException: No com.microsoft.azure.vmagent.AzureVMCloudBaseRetentionStrategy implementation found for idleTerminationMinutes
Possible solution: Try to install 'configuration-as-code-support' plugin

	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.findDescribableBySymbol(HeteroDescribableConfigurator.java:142)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:93)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:131)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:74)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:247)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:80)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:123)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:74)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:247)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:80)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:96)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:101)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:43)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:321)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:264)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:630)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:517)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:500)
	at com.microsoft.azure.vmagent.test.ConfigAsCodeTest.configure(ConfigAsCodeTest.java:30)
	at com.microsoft.azure.vmagent.test.ConfigAsCodeTest.export_configuration(ConfigAsCodeTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:523)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ndeloof** [comment]
your test yaml uses:
```yaml
  vmTemplates:
     - templateName: azure-jenkins-agents
        retentionStrategy:
            idleTerminationMinutes: 60
```

as AzureVMCloudBaseRetentionStrategy is abstract, you need to provide a symbol for concrete implementation to use:

```yaml
  vmTemplates:
     - templateName: azure-jenkins-agents
        retentionStrategy:
            <some_AzureVMCloudBaseRetentionStrategy_implementation_symbol>:
                attribute: value
                attribute: value
```

**Comment by ndeloof** [comment]
as discussed on gitter, the issue here is that Azure-vm-plugin do extend RetentionStrategy to define an internal-only extension point, and doing so do expose Descriptor<RetentionStrategy>, which means those implementation doesn't match a lookup for the desired type (AzureVMCloudBaseRetentionStrategy).

Recommendation : define a custom ExtensionPoint for this plugin, which produce RetentionStrategy instances to configure the VM-agents.
