### ISSUE TITLE
Invalid configuration elements for [...] git

### ISSUE THREAD

**Issue by HerveMARTIN** [jenkinsci/configuration-as-code-plugin#590]
When adding this part of configuration-as-code file (jenkins.yaml) : 
```
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
```
we get this stack : 
```
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1103)
	at jenkins.model.Jenkins.<init>(Jenkins.java:907)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: tool: error configuring 'tool' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:630)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.tools.ToolConfigurationCategory : git
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:353)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:343)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:264)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	... 18 more
```
What's wrong?

**Comment by ewelinawilkosz** [comment]
do you have git plugin installed?

**Comment by ewelinawilkosz** [comment]
can you also share Jenkins and Configuration as Code plugins version? I was using basically the same syntax yesterday and no complains from Jenkins...

**Comment by HerveMARTIN** [comment]
I'm using docker image jenkins/jenkins:latest and latest (1.1) configuration-as-code version with this Dockerfile line : 
RUN /usr/local/bin/install-plugins.sh configuration-as-code

**Comment by casz** [comment]
I guess pre installing git plugin #280 acting up again is my guess.

**Comment by HerveMARTIN** [comment]
Ok, i've adding the git plugin in the Dockerfile and it works fine now.
The counterpart is that some other (dependency) plugins are loaded but that's ok for me :)

**Comment by HerveMARTIN** [comment]
Do you want me to close this issue or do you want to keep it open until #280 is solved?

**Comment by casz** [comment]
Just close your issue 😇 the workaround is to preinstall plugins.
