### ISSUE TITLE
Plugins installation causes stackstrace

### ISSUE THREAD

**Issue by gomesp** [jenkinsci/configuration-as-code-plugin#605]
I am trying this plugin for the first time, so please forgive me for asking a very basic question.

I created a sample Docker image to try your demos, and it seems that every time I add a plugin via CasC I get a stacktrace (below).

The code I am running is in this repository: https://github.com/gomesp/docker-jenkins
If I add the plugins config it will fail. I can't see any difference between my config below and your demo. 

So, I have two questions:

1. If I replace the plugin version from latest to a specific version (e.g. chucknorris: 1.1) then the stacktrace is gone, but the plugin is only available after a restart. Is it possible to have a working configuration with the latest plugin versions?
2. Is it possible to have the plugins available without restarting Jenkins, i.e. installed before the first initialisation?

```
plugins:
  required:
    chucknorris: latest
```

```
INFO: Started @3982ms
Oct 20, 2018 10:36:13 AM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
Oct 20, 2018 10:36:16 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Oct 20, 2018 10:36:17 AM hudson.ClassicPluginStrategy createClassJarFromWebInfClasses
WARNING: Created /var/jenkins_home/plugins/gradle/WEB-INF/lib/classes.jar; update plugin to a version created with a newer harness
Oct 20, 2018 10:36:18 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Oct 20, 2018 10:36:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Oct 20, 2018 10:36:29 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Oct 20, 2018 10:36:31 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
INFO: Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
Oct 20, 2018 10:36:31 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Oct 20, 2018 10:36:31 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class io.jenkins.plugins.casc.plugins.PluginManagerConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:630)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: update site default isn't hosting plugin chucknorris
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:278)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:177)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:92)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:58)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	... 18 more

Oct 20, 2018 10:36:31 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1103)
	at jenkins.model.Jenkins.<init>(Jenkins.java:907)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: plugins: error configuring 'plugins' with class io.jenkins.plugins.casc.plugins.PluginManagerConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:630)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: update site default isn't hosting plugin chucknorris
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.getPluginMetadata(PluginManagerConfigurator.java:278)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configurePlugins(PluginManagerConfigurator.java:177)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:92)
	at io.jenkins.plugins.casc.plugins.PluginManagerConfigurator.configure(PluginManagerConfigurator.java:58)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:645)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	... 18 more

Oct 20, 2018 10:36:31 AM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
Oct 20, 2018 10:36:31 AM jenkins.model.Jenkins$18 onAttained
INFO: Started termination
Oct 20, 2018 10:36:31 AM jenkins.model.Jenkins$18 onAttained
INFO: Completed termination
Oct 20, 2018 10:36:31 AM jenkins.model.Jenkins _cleanUpDisconnectComputers
INFO: Starting node disconnection
Oct 20, 2018 10:36:32 AM jenkins.model.Jenkins _cleanUpShutdownPluginManager
INFO: Stopping plugin manager
Oct 20, 2018 10:36:32 AM jenkins.model.Jenkins _cleanUpPersistQueue
INFO: Persisting build queue
Oct 20, 2018 10:36:32 AM jenkins.model.Jenkins _cleanUpAwaitDisconnects
INFO: Waiting for node disconnection completion
Oct 20, 2018 10:36:32 AM jenkins.model.Jenkins cleanUp
INFO: Jenkins stopped
```

**Comment by blontic** [comment]
I seem to be getting the same errors with plugins and docker

**Comment by jonbrohauge** [comment]
At some point there were issues regarding the use of _latest_ in stead of an explicit version. I cannot recollect if this issue has been resolved.

**Comment by blontic** [comment]
Tested with a redhat base and it works fine. May be just the Docker build of Jenkins

**Comment by gomesp** [comment]
@blontic A RHEL base image or VM? I'm keen to see it working with the official Jenkins image (based on Alpine)

**Comment by dmolesUC3** [comment]
I'm seeing this with `jenkins/jenkins:lts` and the following `jenkins.yaml`:

```
plugins:
  required:
    blueocean: latest
    configuration-as-code: latest

jenkins:
  authorizationStrategy: unsecured
  mode: NORMAL
  numExecutors: 2
  scmCheckoutRetryCount: 2
  systemMessage: |
    Jenkins Docker image built from https://github.com/dmolesUC3/mrt-jenkins-docker

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
  jdk:
    installations:
      - name: jdk8
        home: /usr/lib/jvm/java-8-openjdk-amd64/
      - name: jdk11
        home: /opt/jdk/jdk-11
```

Note my Dockerfile also has

```
RUN install-plugins.sh \
    configuration-as-code \
    blueocean
```

(or, I assume, the `jenkins.yaml` would never get picked up in the first place). The container and Jenkins start OK, but when I navigate to Jenkins in the browser I get

> # Error
> 
> ```
> io.jenkins.plugins.casc.ConfiguratorException: update site default isn't hosting plugin configuration-as-code
> ```

Pinning the versions to

```
    blueocean: 1.13.1
    configuration-as-code: 1.7
```

gets around the problem.

**Comment by ewelinawilkosz** [comment]
@dmolesUC3 we're currently working on removing plugin management support from JCasC: https://github.com/jenkinsci/configuration-as-code-plugin/pull/769 - that feature was experimental and never worked well and causes issues (randomly) - it is not very safe to use it
here is another PR with discussion: https://github.com/jenkinsci/configuration-as-code-plugin/pull/766

**Comment by gomesp** [comment]
Thanks for the feedback @ewelinawilkosz - It seems there's nothing else here to do but to close the issue then?

**Comment by timja** [comment]
@casz can we close this please?
