### ISSUE TITLE
SeedJobConfigurator should have an option to create a workspace when instantiating the JenkinsJobManagement object

### ISSUE THREAD

**Issue by rdpa** [jenkinsci/configuration-as-code-plugin#608]
Running jenkins in docker based on the upstream jenkins:lts-alpine image. Relevant plugins we are using are configuration-as-code:1.2 and job-dsl:1.70

In [SeedJobConfigurator](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/support/src/main/java/io/jenkins/plugins/casc/support/jobdsl/SeedJobConfigurator.java#L59), the [JenkinsJobManagement constructor](https://github.com/jenkinsci/job-dsl-plugin/blob/45052e1545c4c30496cfdda1943a1d7eac998ccc/job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/JenkinsJobManagement.java#L79) is called with specifying null for the workspace. From my testing, this causes a NullPointerException in the [readFileFromWorkspace jobdsl method](https://jenkinsci.github.io/job-dsl-plugin/#path/readFileFromWorkspace) when the method tries to access the workspace object. See the following relevant snippet of the stacktrace:

```
...
Caused by: io.jenkins.plugins.casc.ConfiguratorException: jobs: error configuring 'jobs' with class io.jenkins.plugins.casc.support.jobdsl.SeedJobConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:614)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: jobs: Failed to execute script with hash 766667353
	at io.jenkins.plugins.casc.support.jobdsl.SeedJobConfigurator.configure(SeedJobConfigurator.java:73)
	at io.jenkins.plugins.casc.support.jobdsl.SeedJobConfigurator.configure(SeedJobConfigurator.java:33)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:637)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:608)
	... 17 more
Caused by: java.lang.NullPointerException
	at javaposse.jobdsl.plugin.JenkinsJobManagement.locateValidFileInWorkspace(JenkinsJobManagement.java:408)
	at javaposse.jobdsl.plugin.JenkinsJobManagement.readFileInWorkspace(JenkinsJobManagement.java:233)
	at javaposse.jobdsl.dsl.JobManagement$readFileInWorkspace$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at javaposse.jobdsl.dsl.JobParent.readFileFromWorkspace(JobParent.groovy:247)
...
```
I only tested with FromFileScriptSource, but based on the code I believe it impacts the other two types of sources as well.

**Comment by ndeloof** [comment]
job-dsl script execution from CasC is a hack, and by nature we don't have a workspace as we don't actually execute within an actual job.

**Comment by rdpa** [comment]
My understanding is that you don't need to be in a job context to have a jobdsl workspace, all we'd need to do is instantiate a [local filepath](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/FilePath.java#L271-L274) from the config and pass it. Could also default to null to avoid breaking backwards compatibility. I'd be happy to attempt a PR if you think its worth the time

**Comment by ndeloof** [comment]
we can indeed use a fake workspace, but then this directory would exist outside any management from jenkins master. Can you please give more details on the reason you need a workspace for your seed job script ?

**Comment by rdpa** [comment]
Fair enough. I'll see what we can do with URLs. Thanks.

**Comment by SpComb** [comment]
> sure, you don't have to put job-dsl syntax in your yaml file; this is _possible_, but not _required_. Just set URL for your groovy script(s)

Is there an example of loading `jenkins.yml` -> `jobs` from URLs?

I found an [example](https://github.com/jenkinsci/job-dsl-plugin/blob/master/job-dsl-plugin/src/test/resources/javaposse/jobdsl/plugin/ConfigurationAsCodeTest.yaml) that shows that `file: ...` is also supported in addition to the inline-YAML `script: ...` used in most CaaC examples, but this leads to an additional annoyance vs use of ` readFileFromWorkspace(...)`: any `${...}` groovy references in the pipeline script embedded in the JobDSL script will get evaluated by the configuration-as-code plugin, and need an additional escaping step:

```
Processing provided DSL script
2021-10-21 12:29:20.209+0000 [id=34]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
groovy.lang.MissingPropertyException: No such property: env for class: javaposse.jobdsl.dsl.helpers.workflow.CpsContext
```

**Comment by cowai** [comment]
I found a workaround to load the other groovy on Job DSL while using JCasC and Job DSL. I use `new File()` intead of `readFileFromWorkspace()`.


```external.groovy
// external.groovy
class Util {
  public static final String CREDENTIAL_ID = 'token_id'
  public static final STAGES = ['production', 'development', 'staging']
  public static hello(String something) {
    return "Hello, " + something
  }
}
```

```groovy
// seed-job.groovy
String classSource = new File('/your/file/path/external.groovy').getText("UTF-8")
Class utilClass = new GroovyClassLoader().parseClass(classSource)
def util = utilClass.newInstance()

println util.CREDENTIAL_ID
println util.hello("world")
util.STAGES.each { stage ->
  println stage
}
```

Hope it helps.
