### ISSUE TITLE
CasC keeps complaining after restarting jenkins (after a try of updating stuff) 

### ISSUE THREAD

**Issue by HerrmannHinz** [jenkinsci/configuration-as-code-plugin#626]
VERSIONS: 
- [2.147 ] Jenkins version
- [1.1 ] Plugin version
- [linux/kubernetes ] OS

WHAT I DID: 

- tried to bump jenkins to 2.149 but this version update did not work
- + in the same update i've set casc to 1.2 
- that ended up in the below erros 
- switched back to jenkins 2.147
- same errors as below... 

LOGS: 

``` 
$ k logs -f jenkins-prod-777784d6cb-lc9cc
Picked up JAVA_TOOL_OPTIONS: -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Berlin -Dhudson.slaves.ChannelPinger.pingIntervalSeconds=60
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @354ms to org.eclipse.jetty.util.log.JavaUtilLog
Oct 31, 2018 9:10:43 AM winstone.Logger logInternal
INFO: Beginning extraction from war file
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_181-b13
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: DefaultSessionIdManager workerName=node0
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: No SessionScavenger set, using defaults
Oct 31, 2018 9:10:43 AM org.eclipse.jetty.server.session.HouseKeeper startScavenging
INFO: node0 Scavenging every 660000ms
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Oct 31, 2018 9:10:44 AM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started w.@49b2a47d{Jenkins v2.149,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
Oct 31, 2018 9:10:44 AM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@2438dcd{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Oct 31, 2018 9:10:44 AM org.eclipse.jetty.server.Server doStart
INFO: Started @1233ms
Oct 31, 2018 9:10:44 AM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
Oct 31, 2018 9:10:45 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Oct 31, 2018 9:10:45 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Oct 31, 2018 9:10:53 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Oct 31, 2018 9:10:53 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Oct 31, 2018 9:10:55 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Oct 31, 2018 9:10:55 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.configfiles.GlobalConfigFiles$1 in file:/var/jenkins_home/plugins/config-file-provider/WEB-INF/lib/config-file-provider.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
Oct 31, 2018 9:10:55 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:43)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:106)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml  in /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml, line 7, column 33:
          excludeClientIPFromCrumb: "true"
                                    ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:96)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:40)
	... 17 more

Oct 31, 2018 9:10:55 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1103)
	at jenkins.model.Jenkins.<init>(Jenkins.java:907)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:43)
	at io.jenkins.plugins.casc.yaml.YamlUtils.loadFrom(YamlUtils.java:106)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:542)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:272)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:264)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml  in /var/jenkins_home/casc_configs/..2018_10_31_08_27_50.882280034/jenkins.yaml, line 7, column 33:
          excludeClientIPFromCrumb: "true"
                                    ^
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:96)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:82)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:40)
	... 17 more

Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins$18 onAttained
INFO: Started termination
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins$18 onAttained
INFO: Completed termination
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins _cleanUpDisconnectComputers
INFO: Starting node disconnection
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins _cleanUpShutdownPluginManager
INFO: Stopping plugin manager
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins _cleanUpPersistQueue
INFO: Persisting build queue
Oct 31, 2018 9:10:55 AM jenkins.model.Jenkins cleanUp
INFO: Jenkins stopped
``` 

any idea?

**Comment by HerrmannHinz** [comment]
after talking to @ndeloof on gitter he gave me a hint: 

- kubernetes configmaps (when they are used as a basis for a mount) do create some symlinks in the filesystem 
- CasC is following the symlinks if im correct. 
- this will then cause CasC to read files more than once: 

``` 
$ ls -lha /var/jenkins_casc/casc_configs/
drwxr-xr-x    2 root     root        4.0K Oct 29 16:29 ..2018_10_29_16_29_08.094515936
lrwxrwxrwx    1 root     root          31 Oct 29 16:29 ..data -> ..2018_10_29_16_29_08.094515936
lrwxrwxrwx    1 root     root          16 Oct 15 16:43 auth.yaml -> ..data/auth.yaml
lrwxrwxrwx    1 root     root          19 Oct 15 16:43 jenkins.yaml -> ..data/jenkins.yaml
lrwxrwxrwx    1 root     root          16 Oct 15 16:43 jobs.yaml -> ..data/jobs.yaml
lrwxrwxrwx    1 root     root          25 Oct 15 16:43 pod-templates.yaml -> ..data/pod-templates.yaml
lrwxrwxrwx    1 root     root          19 Oct 15 16:43 secrets.yaml -> ..data/secrets.yaml
lrwxrwxrwx    1 root     root          24 Oct 15 16:43 smtp-secrets.yaml -> ..data/smtp-secrets.yaml

# where the env vars are set to: 
- name: CASC_JENKINS_CONFIG
   value: /var/jenkins_casc/casc_configs
```

**Comment by ndeloof** [comment]
right, if you set `/var/jenkins_casc/casc_configs/` as config source, the scanner will find all *.yaml files there and as a result will detect duplicates as this includes same target file following symlinks.

A simple option would be for us to **only** consider files in directory, but not in subdirectories. Another option would be to detect symlink and resolve to target, so we don't consider duplicate files for a single target.
Last option I have in mind would be for CASC_JENKINS_CONFIG to support ant-style patterns so you can use `/var/jenkins_casc/casc_configs/*.yaml`. This would be a compatibility breaking change but an acceptable one imho.

**Comment by ewelinawilkosz** [comment]
@ndeloof I would vote for skipping subdirectories. Or at least that was an expected behavior for me - so I can put my file wherever, without worrying what's deeper in the file structure
But I'd like to hear more voices

**Comment by HerrmannHinz** [comment]
how about: 

**SCENARIO A**: 

- introduce ant-style pattern 

**SCENARIO B**: 

- don't scan directories and do recursive scanning but
- introduce the option to provide multiple file locations 

**SCENARIO C**: 
- don't scan directories and do recursive scanning but...
- introduce the option to provide multiple file locations 
- + ant-style pattern

**Comment by ndeloof** [comment]
Those scenarios make perfect sense, we are mostly looking for a short term fix as k8s integration is broken

adding support for Ant-style pattern could come later
I also think we should revisit this part of JCasC to make file source a SPI, so one can plug alternate parsers like suggested on #593

**Comment by HerrmannHinz** [comment]
yeah ant pattern is not that important. i'd also say it can come later. 

the option to pass in multiple locations would kick ass and also solve some use cases. 

this is my current directory layout - fyi: 

``` 
├── auth.yaml
├── jenkins.yaml
├── jobs.yaml
├── pod-templates.yaml
├── role_strategies
│   ├── OW-APPS-ABC.yaml
│   ├── OW-APPS-CDE.yaml
│   ├── OW-APPS-XYZ.yaml
│   ├── OW-APPS-123.yaml
│   ├── ...
│   ├── _role_strategy_00_roles.yaml
│   └── ow-xp-wp.yaml
├── secrets.yaml
└── smtp-secrets.yaml
```

configmap i create from those: 

``` 
kubectl -n jenkins-${CURRENT_SCOPE} create configmap jenkins-casc-config \
  --from-file=deploy/manifests/jenkins/${CURRENT_SCOPE}/casc/ \
  --from-file=deploy/manifests/jenkins/${CURRENT_SCOPE}/casc/role_strategies/ \
  --dry-run -o yaml | kubectl replace -f -
``` 

helm mounts: 

``` 
  volumes:
  - name: casc-config
    configMap:
      name: jenkins-casc-config
  mounts:
  - name: casc-config
    mountPath: /var/jenkins_casc/casc_configs
    readOnly: true
``` 

just to give you an idea on how me/we work with casc atm...

**Comment by casz** [comment]
This should be fixed in recent release @HerrmannHinz 
Feel free to reopen
