### ISSUE TITLE
JNLP agent configuration demo leads to NPE

### ISSUE THREAD

**Issue by andreyakostov** [jenkinsci/configuration-as-code-plugin#662]
- [x] Jenkins version: 2.138.3
- [x] Plugin version: 1.3
- [x] OS: Windows

The [build agents demo](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/demos/build_agents/README.md) has the following example for configuring a JNLP agent:

```yaml
jenkins:
  (...)
  nodes:
    - permanent:
        labelString: "linux docker test"
        mode: NORMAL
        name: "utility-node"
        remoteFS: "/home/user1"
        launcher:
          jnlp:
```

Note that 'jnlp:' has no child elements. This leads to a NullPointerException in io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71):

```
java.lang.NullPointerException: while trying to invoke the method io.jenkins.plugins.casc.model.CNode.clone() of a null object returned from java.util.Map$Entry.getValue()
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:43)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:9)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:641)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doReplace(ConfigurationAsCode.java:171)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
```

**Comment by nthienan** [comment]
I experienced the same issue. 
Jenkins version: 2.169
Plugin version: 1.8
OS: Docker container
```yaml
jenkins:
  nodes:
  - permanent:
    name: "external-slave"
    numExecutors: 1
    launcher:
      jnlp:
        tunnel: "jenkins-slave.openshift.com:50000"
        workDirSettings:
          disabled: false
          failIfWorkDirIsMissing: false
          internalDir: "remoting"
```

**Comment by casz** [comment]
The NPE is pretty clear! I had hoped someone would have fixed it already :sweat_smile:

**Comment by andreyakostov** [comment]
Hello @casz, I thought it is pretty straightforward as well and added a null check that avoids this particular issue. But then I saw #666 and in both cases the root cause is some error in the YAML file. In the case with build agents, IMO the demo is incomplete, specifically the `jnlp` configuration. When creating a brand new permanent agent with just a name and remote root directory (both are mandatory), saving it and exporting the configuration, the agent part looks like this:

```yaml
jenkins:
  (...)
  nodes:
  - permanent:
      launcher:
        jnlp:
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      name: "662-test"
      numExecutors: 1
      remoteFS: "/var/jenkins"
```

So the NPE is hiding an error/missing configuration in the YAML file. What do you think?

**Comment by casz** [comment]
it's still straight forward, don't call clone on a null object 😄

**Comment by andreyakostov** [comment]
In the demo, it is trying to clone `jnlp`'s value. Yes, not calling `clone` solves the NPE. But still the user would not know that his configuration is incomplete. So my idea is: is there a valid scenario where a property in the configuration does not have value and if so, is there a way to differentiate where there's an error in the config or it is expected. If there's always a value, then straightforward it is. :) It's just that I'm still a CasC noob.

**Comment by casz** [comment]
There is no way to differentiate so it is a moot point. Null is null whether it is caused by user, plugin constructor or databound constructor/setter
