### ISSUE TITLE
Improve NPE diagnosability when passing misformatted globalNodeProperties

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#666]
I Hit a barely diagnosable NPE in the plugin when a broken config YAML is passed

- [x] Jenkins version: 2.138.3, in Jenkinsfile Runner
- [x] Plugin version: 1.3
- [x] OS: Docker, standard Jenkins image

```yaml
jenkins:
  mode: NORMAL
  numExecutors: 1
  labelString: "linux"
  scmCheckoutRetryCount: 0
  myViewsTabBar: "standard"
  viewsTabBar: "standard"

  globalNodeProperties:
    - envVars:
      env:
      - key: JFR_LOCAL_WORKSPACE
        value: /workspace
      - key: PIPELINE_SKIP_WINDOWS
        value: true

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
```

```
  13.117 [id=1]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Executing main/1) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:43)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:9)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:641)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1103)
	at jenkins.model.Jenkins.<init>(Jenkins.java:907)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at io.jenkins.jenkinsfile.runner.JenkinsEmbedder.newHudson(JenkinsEmbedder.java:334)
	at io.jenkins.jenkinsfile.runner.JenkinsEmbedder.before(JenkinsEmbedder.java:199)
	at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerRule.before(JenkinsfileRunnerRule.java:76)
	at io.jenkins.jenkinsfile.runner.JenkinsfileRunnerRule$1.evaluate(JenkinsfileRunnerRule.java:113)
	at io.jenkins.jenkinsfile.runner.App.run(App.java:32)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.run(Bootstrap.java:166)
	at io.jenkins.jenkinsfile.runner.bootstrap.Bootstrap.main(Bootstrap.java:68)
```

**Comment by timja** [comment]
That NullPointer was fixed awhile ago, you now get:
```
java.lang.AssertionError: Unexpected exception 

	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:38)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:551)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No hudson.slaves.NodeProperty implementation found for env
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:153)
	at io.vavr.control.Option.orElse(Option.java:302)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:152)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:80)
	at io.vavr.Tuple2.apply(Tuple2.java:239)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:79)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:88)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:51)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:666)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:628)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:666)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:650)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:549)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:524)
	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:35)
	... 5 more

```

Closing as the error message is better, feel free to re-open / provide a PR if you think the error message could be better
