### ISSUE TITLE
Jenkins failed to start after upgrading plugins

### ISSUE THREAD

**Issue by CondormanFr** [jenkinsci/configuration-as-code-plugin#668]
- Jenkins [ 2.138.3] 
- CasC plugin [ 1.3 ] 
- Operating system [ Linux Docker] 

I was able to start my jenkins instance with all customization in my jcasc file. That's really great.
My plugins are installed via a plugin.txt file while building my docker image.

All work well until i decide to update or add a plugin thru the GUI. 
Jenkins didn't restart and make an error :  

```
Dec 02, 2018 11:03:03 PM jenkins.model.Jenkins cleanUp
jenkins-test         | INFO: Jenkins stopped
jenkins-test         | Dec 02, 2018 11:03:03 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins-test         | SEVERE: Failed ConfigurationAsCode.init
jenkins-test         | java.lang.Error: java.lang.reflect.InvocationTargetException
jenkins-test         |  at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins-test         |  at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins-test         |  at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins-test         |  at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
jenkins-test         |  at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins-test         |  at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins-test         |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins-test         |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins-test         |  at java.lang.Thread.run(Thread.java:748)
jenkins-test         | Caused by: java.lang.reflect.InvocationTargetException
jenkins-test         |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins-test         |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins-test         |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins-test         |  at java.lang.reflect.Method.invoke(Method.java:498)
jenkins-test         |  at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins-test         |  ... 8 more
jenkins-test         | Caused by: java.lang.AssertionError: Category not found. It seems the class jenkins.model.GlobalConfigurationCategory$Unclassified is not annotated with @Extension and so not registered
jenkins-test         |  at jenkins.model.GlobalConfigurationCategory.get(GlobalConfigurationCategory.java:47)
jenkins-test         |  at hudson.model.Descriptor.getCategory(Descriptor.java:826)
jenkins-test         |  at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$0(GlobalConfigurationCategoryConfigurator.java:74)
jenkins-test         |  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
jenkins-test         |  at java.util.Iterator.forEachRemaining(Iterator.java:116)
jenkins-test         |  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
jenkins-test         |  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
jenkins-test         |  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
jenkins-test         |  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
jenkins-test         |  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
jenkins-test         |  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
jenkins-test         |  at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:79)
jenkins-test         |  at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:286)
jenkins-test         |  at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:262)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$configureWith$6(ConfigurationAsCode.java:649)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:620)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:649)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
jenkins-test         |  at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
jenkins-test         |  ... 13 more
 Dec 02, 2018 11:03:03 PM hudson.util.BootFailure publish
jenkins-test         | SEVERE: Failed to initialize Jenkins

```
I didn't success to start jenkins again ...

**Comment by ewelinawilkosz** [comment]
would it be possible for you to share your plugins.txt and which plugin you updated/added via GUI?

**Comment by CondormanFr** [comment]
My plugin.txt
[plugins.txt](https://github.com/jenkinsci/configuration-as-code-plugin/files/2638714/plugins.txt)

I try to update **Maven Integration plugin**  from 3.1.2 to 3.2  but it occurs on any plugin i try to update by this way.

**Comment by CondormanFr** [comment]
In the error log, this line 
`java.lang.AssertionError: Category not found. It seems the class jenkins.model.GlobalConfigurationCategory$Unclassified is not annotated with @Extension and so not registered`

What does it mean with @Extension ?
My jenkins.yaml seems to be well found and has not been changed before the restart of jenkins

**Comment by jonbrohauge** [comment]
I get errors almost every time I try to restart a Jenkins instance. Using Docker, I just update the relevant stuff and build a new image. Throw out the "deprecated" instance and spin up the updated one. The trick is to keep the container stateless, i.e. do not save anything important inside the running instance. This process also hinders me (and everyone else) from doing customized upgrades (forking/splitting) and thus keeps all our instances in sync.

**Comment by casz** [comment]
Closing due to inactivity, feel free to reopen if it remains an issue.
