### ISSUE TITLE
Can't configure nodejs tool installation

### ISSUE THREAD

**Issue by kshcherban** [jenkinsci/configuration-as-code-plugin#701]
When i try to submit following configuration i get a NullPointerException.
```
tool:
  nodejs:
    installations:
      - name: "nodejs-6.9.4"
        properties:
          - installSource:
            installers:
              - nodeJSInstaller:
                id: "NodeJS 6.9.4"
                npmPackagesRefreshHours: 72
                force32Bit: false
                npmPackages: ""

```

- [ /] Jenkins version:  2.150.1 
- [ /] Plugin version: 1.4, both `configuration-as-code` and `configuration-as-code-support`
- [ /] OS: jenkins in docker, debian jessie

Stacktrace
```
java.lang.NullPointerException
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:43)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:9)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:43)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:9)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:43)
	at io.jenkins.plugins.casc.model.Sequence.clone(Sequence.java:9)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:11)
	at io.jenkins.plugins.casc.model.Mapping.lambda$clone$0(Mapping.java:71)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.jenkins.plugins.casc.model.Mapping.clone(Mapping.java:71)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:641)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
	at io.jenkins.plugins.casc.ConfigurationAsCode.doReload(ConfigurationAsCode.java:154)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:537)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:789)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:458)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:52)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:92)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fdarul** [comment]
Hello
With this configuration, I've got this error:
 ```
 nodejs:
    defaultProperties:
    - installSource:
        installers:
        - nodeJSInstaller:
            npmPackagesRefreshHours: 72
    installations:
    - name: "nodejs"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "11.6.0"
              npmPackagesRefreshHours: 72
```
I'have also try with id: 6.9.4 with the same result ...


```
io.jenkins.plugins.casc.ConfiguratorException: home is required to configure class jenkins.plugins.nodejs.tools.NodeJSInstallation
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:112)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:73)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:264)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:97)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:341)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:284)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:349)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:284)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:657)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:620)
Caused: io.jenkins.plugins.casc.ConfiguratorException: tool: error configuring 'tool' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:626)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:657)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:642)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1117)
	at jenkins.model.Jenkins.<init>(Jenkins.java:921)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

- Jenkins version: 2.150.1
- Plugin version: 1.4, both configuration-as-code and configuration-as-code-support
- OS: jenkins in aws ec2, ubuntu

**Comment by ewelinawilkosz** [comment]
the only difference I see, and it may be copy-pasting result, is that @kshcherban has a configuration with one less indentation under `installations`:

```
      - installSource:
        installers:
```
vs.
```
     - installSource:
         installers:
```

can you check with his exact configuration and let us know if the issue is still there/the same?

**Comment by fdarul** [comment]
- installSource:
        installers:
sent the java.lang.NullPointerException

The following setting, with sonarqube work:  

```
sonarRunnerInstallation:
    installations:
    - name: sonarqube
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "3.3.0.1492"
```

**Comment by kshcherban** [comment]
Seems that `NullPointerException` related to not existing `id` of NodeJs version.
Here's my working configuration
```
tool:
  nodejs:
    defaultProperties:
    - installSource:
        installers:
        - nodeJSInstaller:
            npmPackagesRefreshHours: 72
    installations:
    - name: "nodejs-6.9.4"
      home: /usr/local/bin
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "6.9.4"
              npmPackagesRefreshHours: 72
    - name: "nodejs-10.5.0"
      home: /usr/local/bin
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "10.5.0"
              npmPackagesRefreshHours: 72
```

**Comment by fdarul** [comment]
I does not set the "home" property. It works great now; 
Thank you very much.

**Comment by 0lexandra** [comment]
Hello, I've met the same issue. 
Did you manage to run this configuration without setting 'home'?
If you set nodejs installation manually in Jenkis' interface there is no input for "home"and I'd like it to stay this way after using CasC plugin. Any ideas how to achieve this?

**Comment by kshcherban** [comment]
@0lexandra home is visible in UI after all
![jenkins-nodejs-1](https://user-images.githubusercontent.com/2072958/51382469-2e824d80-1b17-11e9-863f-cdaed7604ced.png)

**Comment by 0lexandra** [comment]
@kshcherban that's right! However it isn't visible if you leave home path blank in yaml file and that is what I needed :) I just don't want to specify home path, but without setting home in yaml file I got same error fdarul did. After setting home to empty string it works exactly how I need. 
Thank you for your help!

**Comment by mimatn** [comment]
For future visitors: when @0lexandra talks about adding the "home" property, she refers to the "installations" node, like this:

```
          nodejs:
            installations:
            - name: "Node 11.14"
              home: ""
              properties:
              - installSource:
                  installers:
                  - nodeJSinstaller:
                      id: "11.14.0"
                      npmPackagesRefreshHours: 72
```

Just in case you want to save a few hours of retries...

**Comment by Ilhicas** [comment]
I can confirm this occurs with
Plugin versions
nodejs:1.2.9
configuration-as-code:1.14
configuration-as-code-support:1.14

This yaml config was exported from UI with JCASC for the tool Nodejs and is not working

```
  nodejs:
    defaultProperties:
    - installSource:
        installers:
        - nodeJSInstaller:
            npmPackagesRefreshHours: 72
    installations:
    - name: "nodejs"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "11.14.0"
              npmPackagesRefreshHours: 72
```
when actually using as suggested by @mimatn works:

```
tool:
#This tool can't be installed against alpine OS
  nodejs:
    defaultProperties:
    - installSource:
        installers:
        - nodeJSInstaller:
            npmPackagesRefreshHours: 72
    installations:
    - name: "nodejs"
      home: ""
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "11.14.0"
              npmPackagesRefreshHours: 72
```

And the UI doesn't show any references to home dir

![image](https://user-images.githubusercontent.com/14908129/57783427-005bf580-7726-11e9-8130-c08d11b3a48d.png)

However the plugin forces a home on its constructor

https://github.com/jenkinsci/nodejs-plugin/blob/2d459b1507a763ef14303b3c7b727863ffd974f2/src/main/java/jenkins/plugins/nodejs/tools/NodeJSInstallation.java#L70

**Comment by casz** [comment]
I ask that you create an issue with the component `nodejs-plugin` on https://issues.jenkins-ci.org/ or submit a pull request to the plugin

**Comment by mimatn** [comment]
Done: https://issues.jenkins-ci.org/browse/JENKINS-57508

This issue can stay close because it's not a CasC plugin issue. Thank you very much.

**Comment by nfalco79** [comment]
@casz  why should be an issue of NodeJS plugin? NodeJSInstallation extends the hudson.tools.ToolInstallation exctly like hudson.tasks.Maven.MavenInstallation and hudson.model.JDK does. Futhermode NodeJS has never supported CasC plugin

**Comment by casz** [comment]
most likely solved by #925

**Comment by casz** [comment]
However, the issue with the required home attribute is something related to nodejs plugin

**Comment by nfalco79** [comment]
no, the constructor is exactly the same of JDK and MavenInstall.
Could you explain to me the differences?
[MavenInstall constructor](https://github.com/jenkinsci/jenkins/blob/71cd2b968087867a974b2c59824429792724a0c0/core/src/main/java/hudson/tasks/Maven.java#L516)
[NodeJSInstallation constructor](https://github.com/jenkinsci/nodejs-plugin/blob/2d459b1507a763ef14303b3c7b727863ffd974f2/src/main/java/jenkins/plugins/nodejs/tools/NodeJSInstallation.java#L70)
[JDK constructor](https://github.com/jenkinsci/jenkins/blob/71cd2b968087867a974b2c59824429792724a0c0/core/src/main/java/hudson/model/JDK.java#L88)

**Comment by casz** [comment]
the difference you have marked your things `NonNull`

**Comment by nfalco79** [comment]
Ok I got it, I didn't see references to Nonnull in this plugin in previos search.
But since there is a long diatribe on JSR305 specification [(just an example)](https://blog.codefx.org/java/jsr-305-java-9/#comment-3582702088) that was never released (actual status dormient) then re-distributition seems violates Oracle license so I never would have thought they was used by someone outside code analisys purpose.
Other reason is that I have could used one of other [available Nonnull annotations](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use) that seems not be covered. So why javax.annotation.Nonnull yes and edu.umd.cs.findbugs.annotations.NonNull no?

**Comment by casz** [comment]
Whether you use `Nonnull` or FindBugs' `NonNull` does not matter since JCasC will respect both due to https://github.com/spotbugs/spotbugs/blob/master/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/NonNull.java#L39 and https://github.com/jenkinsci/configuration-as-code-plugin/blob/1547698cc3a324c08fadf5d43147c019d13f4865/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L112

We cannot use `NonNull.class` as it is not retained for reflective access
