### ISSUE TITLE
Impossible to create a "Secret file" credentials

### ISSUE THREAD

**Issue by yogeek** [jenkinsci/configuration-as-code-plugin#702]
I have configured different kind of credentials (usernamePassword, aws, basicSSHUserPrivateKey) without problem but I cannot manage to configure a "secret file" kind in CasC. Did anyone have a working example please ? Here is what I tested and the corresponding error :

```
credentials:
  system:
    domainCredentials:
      - credentials:

          - file:
              scope: GLOBAL
              id: "secretFile"
              fileName: "secretFile"
              description: "My secret file"
              secretBytes: <secretBytes_retrieved_from_credentials_xml_of_a_previous_jenkins_instance>
```
Error :
```
Caused by: io.jenkins.plugins.casc.ConfiguratorException: credentials: error configuring 'credentials' with class io.jenkins.plugins.casc.support.credentials.CredentialsRootConfigurator configurator
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:626)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:657)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:642)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
jenkins_1  |     ... 13 more
jenkins_1  | Caused by: io.jenkins.plugins.casc.ConfiguratorException: file is required to configure class org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:114)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:75)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:253)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:81)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:96)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:43)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:124)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:75)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:253)
jenkins_1  |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:99)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:330)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:338)
jenkins_1  |     at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:273)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:657)
jenkins_1  |     at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:620)
jenkins_1  |     ... 18 more
```

Why does it need an attribute called file whereas I provided all the fields mentionned in the CasC reference documention for a Secret File ?

Looking at the code, it seems that [this constructor](https://github.com/jenkinsci/plain-credentials-plugin/blob/master/src/main/java/org/jenkinsci/plugins/plaincredentials/impl/FileCredentialsImpl.java#L128) needs a file but it is [this one](https://github.com/jenkinsci/plain-credentials-plugin/blob/master/src/main/java/org/jenkinsci/plugins/plaincredentials/impl/FileCredentialsImpl.java#L167) that corresponds to the CasC documentation. 

But in the first constructor, file param is optional (` @CheckForNull FileItem file`)" so I do not understand : why the error message indicates that it is required ?

**Comment by Springjunky** [comment]
some tryouts ....

          - file:
              scope: GLOBAL
              id: secret_file_id
              description: secret_file_id with dummy filename
              fileName: "dummy" 
              secretBytes: "{2LV43xh8/O8HFGGdu0bns0swAeMl+PGf7zVhZ/cPLMQ=}"

seemed to be working ..

**Comment by dgarzon** [comment]
@yogeek can you make sure you are using `plain-credentials` version `1.5`? The fix for file credentials was introduced in that version. Hope this helps!

**Comment by yogeek** [comment]
@dgarzon thank you ! Indeed my jenkins instance still had the 1.4 version, once I updated `plain-credentials`to 1.5, the secret files were correctly imported into the credentials store :+1: 
Great, now I can manage all my config with CasC :smile: 
@Springjunky thank you for your help too !
