### ISSUE TITLE
packer config fails with "Cannot find configurator for type class net.sf.json.JSONObject"

### ISSUE THREAD

**Issue by der-eismann** [jenkinsci/configuration-as-code-plugin#714]
- [x] Jenkins version: 2.150.2
- [x] Plugin version: 1.4
- [x] OS: Docker container

I wanted to configure my packer installation, but apparently it's not possible (yet) to pass JSON arguments. This is the part of my jenkins.yaml:
```
  packerInstallation:
    installations:
    - name: packer
      home: ""
      params: ""
      templateMode: {}
      properties:
      - installSource:
          installers:
          - packerInstaller:
              id: "1.3.3-linux-amd64"
```

The start of the container then fails with the following error:
```
Jan 25, 2019 11:50:07 AM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class biz.neustar.jenkins.plugins.packer.PackerInstallation.name = packer
Jan 25, 2019 11:50:07 AM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class biz.neustar.jenkins.plugins.packer.PackerInstallation.home = 
Jan 25, 2019 11:50:07 AM io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator tryConstructor
INFO: Setting class biz.neustar.jenkins.plugins.packer.PackerInstallation.params = 
Jan 25, 2019 11:50:07 AM io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry internalLookup
WARNING: Configuration-as-Code can't handle type class net.sf.json.JSONObject
Jan 25, 2019 11:50:07 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: tool: error configuring 'tool' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:626)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:657)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:642)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:545)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Cannot find configurator for type class net.sf.json.JSONObject
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:97)
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:93)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
	at io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry.lookupOrFail(DefaultConfiguratorRegistry.java:70)
	at io.jenkins.plugins.casc.ConfigurationContext.lookupOrFail(ConfigurationContext.java:71)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:129)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:73)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:264)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:97)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:341)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:284)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:349)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:284)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:657)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:620)
	... 18 more
```

If I completely remove the `templateMode` key the startup also fails:
```
io.jenkins.plugins.casc.ConfiguratorException: packerInstallation: Failed to construct instance of class biz.neustar.jenkins.plugins.packer.PackerInstallation.
 Constructor: public biz.neustar.jenkins.plugins.packer.PackerInstallation(java.lang.String,java.lang.String,java.lang.String,net.sf.json.JSONObject,java.util.List,java.util.List).
 Arguments: [java.lang.String, java.lang.String, java.lang.String, null, null, java.util.ArrayList]
```
Is there a workaround for this?

**Comment by phaze-** [comment]
Can this be reopened? I'm running into the same problem.  Is this something that needs to be fixed in the packer plugin?

**Comment by casz** [comment]
If you need to pass a JSON string you can use YAML literal style

```
  packerInstallation:
    installations:
    - name: packer
      home: ""
      params: ""
      templateMode: |-
      {
         "your": "json"
      }
      properties:
      - installSource:
          installers:
          - packerInstaller:
              id: "1.3.3-linux-amd64"
```

**Comment by casz** [comment]
But this seems like an issue with PackerInstallation having a JSONObject on their data binding.

**Comment by casz** [comment]
Actually, they don't even use the JSONObject in anything beyond the constructor...
