### ISSUE TITLE
Endpoint previously used is now inaccessible: CasC blocking logging into Jenkins.

### ISSUE THREAD

**Issue by guice** [jenkinsci/configuration-as-code-plugin#723]
- [Jenkins ver. 2.138.2] Jenkins version
- [1.4] Plugin version
- [LInux] OS

Two questions:

1) How do I get back into Jenkins? 
2) How do I stop CasC from reading the CasC source on _every_ restart?

**Issue**

I had previously setup a Jenkins instance with the CasC plugin using a URL to the configuration yml. In recent events, that URL is now inaccessible. I recently updated Jenkins plugins, which prompted a restart. Now, I'm unable to get into Jenkins. 

The primary screen shows CasC trying to connect to the previous configuration URL, which is now inaccessible: 
```
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at io.jenkins.plugins.casc.yaml.YamlSource.lambda$static$0(YamlSource.java:48)
	at io.jenkins.plugins.casc.yaml.YamlSource.read(YamlSource.java:39)
	at io.jenkins.plugins.casc.yaml.YamlUtils.merge(YamlUtils.java:33)
Caused: io.jenkins.plugins.casc.ConfiguratorException: Failed to read YamlSource: (our now private URL to YAML)
```
Going directly to [jenkins]/configuration-as-code even fails.

Where is this configuration information stored? How do I remove it? Why isn't it within Jenkin's server configs (we have a second Jenkins instance that _can_ connect, and I see no options on removing this URL -- I don't want Jenkins to reload CasC every time because it breaks the project tab groupings).

**Comment by guice** [comment]
Even attempting to restart via Jenkins-CLI is failing: 
```
jenkins_master/5f617f8e-5e39-4a48:/var/vcap/store/jenkins_master# /var/vcap/packages/java/bin/java -jar jenkins-cli.jar -s https://[jenkins url]/ reboot
java.io.IOException: Server returned HTTP response code: 500 for URL: https://[jenkins url]/cli?remoting=false
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:101)
	at hudson.cli.CLI.plainHttpConnection(CLI.java:652)
	at hudson.cli.CLI._main(CLI.java:612)
	at hudson.cli.CLI.main(CLI.java:426)
jenkins_master/5f617f8e-5e39-4a48:/var/vcap/store/jenkins_master# 
```

**Comment by timja** [comment]
It's stored in `${JENKINS_HOME/io.jenkins.plugins.casc.CasCGlobalConfig.xml`
All plugin config goes into its own xml file, unless its core jenkins functionality which goes into `config.xml`

**Comment by timja** [comment]
Closing since no response, you can always get back into jenkins by following this documentation:
https://jenkins.io/doc/book/system-administration/security/#disabling-security

**Comment by yakhyadabo** [comment]
> Even attempting to restart via Jenkins-CLI is failing:
> 
> ```
> jenkins_master/5f617f8e-5e39-4a48:/var/vcap/store/jenkins_master# /var/vcap/packages/java/bin/java -jar jenkins-cli.jar -s https://[jenkins url]/ reboot
> java.io.IOException: Server returned HTTP response code: 500 for URL: https://[jenkins url]/cli?remoting=false
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> 	at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:101)
> 	at hudson.cli.CLI.plainHttpConnection(CLI.java:652)
> 	at hudson.cli.CLI._main(CLI.java:612)
> 	at hudson.cli.CLI.main(CLI.java:426)
> jenkins_master/5f617f8e-5e39-4a48:/var/vcap/store/jenkins_master# 
> ```

I'm having the same issue. 
How did you sorted it out ?
