### ISSUE TITLE
Invalid configuration elements for type class io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfigurator$UserWithPassword

### ISSUE THREAD

**Issue by Tohaker** [jenkinsci/configuration-as-code-plugin#918]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version 2.164.3

- [x] Plugin version 1.19

- [ ] OS

### Description

This block of YAML was previously working, simply giving me another username to login as.
```
JCasC:
    enabled: true
    PluginVersion: 1.5
    SupportPluginVersion: 1.5
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our Jenkins server.  This Jenkins is configured and managed 'as code'.
          securityRealm:
            local:
              users:
              - userWithPassword:
                  id: milesbardon
                  password: {{ .Values.password }}
```
Where `password` is stored in a separate `secrets.yaml` file.

Now after adding a Kubernetes secret credential
```
cred-config: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - string:
                    scope: GLOBAL
                    id: "ssh-key"
                    secret: sshkey
```
I get the following error after doing `helm upgrade` and neither the credential nor the username is applied.
```
WARNING: Unexpected exception occurred while performing reload-jcasc-configuration command.
io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:634)
        at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:666)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:650)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:549)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:277)
        at io.jenkins.plugins.casc.cli.ReloadJCascConfigurationCommand.run(ReloadJCascConfigurationCommand.java:29)
        at hudson.cli.CLICommand.main(CLICommand.java:283)
        at org.jenkinsci.main.modules.sshd.CLICommandAdapter$1.run(CLICommandAdapter.java:37)
        at org.jenkinsci.main.modules.sshd.AsynchronousCommand$1.run(AsynchronousCommand.java:112)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class io.jenkins.plugins.casc.core.HudsonPrivateSecurityRealmConfigurator$UserWithPassword : userWithPassword.
Available attributes : id, password
        at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:378)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:367)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:277)
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:80)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:346)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:277)
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:80)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:219)
        at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:219)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$2(HeteroDescribableConfigurator.java:82)
        at io.vavr.control.Option.map(Option.java:373)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:82)
        at io.vavr.Tuple2.apply(Tuple2.java:239)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:79)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:88)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:51)
        at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
        at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
        at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:666)
        at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:628)
        ... 9 more
```

**Comment by Tohaker** [comment]
For additional information, this is running on Minikube with Kubernetes v1.14.

**Comment by casz** [comment]
your `userWithPassword` seems wrong
```
https://github.com/jenkinsci/configuration-as-code-plugin/blob/727c976d137461f146b301f302d1552ca81de75e/plugin/src/test/resources/io/jenkins/plugins/casc/admin.yml
```

**Comment by Tohaker** [comment]
Thank you, the documentation on the release says to use `userWithPassword` but I couldn't find this recorded anywhere else. All working now!

**Comment by casz** [comment]
Not sure what documentation you are referring to 🤔 a link so we can fix it.

**Comment by Tohaker** [comment]
https://<jenkins_url>/configuration-as-code/reference was what I was referring to, but I have now realised I misread it: `users --- list of UserWithPassword` which is where I got the key `UserWithPassword` from. Thanks for your help!
