### ISSUE TITLE
JCasC plugin build fails on Windows

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/configuration-as-code-plugin#926]
JCasC plugin build on Windows fails with the following error:

```
C:\Users\Oleg\Documents\jenkins\plugins\configuration-as-code-plugin\plugin\target\tmp\junit7904209860056174939\jenkins_5.yaml: A required privilege is not held by the client.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at io.jenkins.plugins.casc.ConfigurationAsCodeTest.init_test_from_accepted_sources(ConfigurationAsCodeTest.java:57)
```

Likely the Symlink-related test should be skipped on Windows.

### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] OS: Windows

**Comment by sladyn98** [comment]
@timja This seems like a good first issue.

**Comment by oleg-nenashev** [comment]
Feel free to take it, thanks!

**Comment by timja** [comment]
It's probably a matter of adding:
```
assumeFalse(Functions.isWindows());
```
to the test,
Or
catching that specific exception and if it occurs do the assume false.

It appears on windows you either need to run as admin or modify privileges to allow your user to create symlinks:
https://stackoverflow.com/a/24353758/4951015
