### ISSUE TITLE
Perforce plugin: JCasC cannot export configuration

### ISSUE THREAD

**Issue by courteouselk** [jenkinsci/configuration-as-code-plugin#934]
[jenkins-jira]: https://issues.jenkins-ci.org/browse/JENKINS-58249
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md
[plugin]: https://github.com/jenkinsci/p4-plugin

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [x] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [x] Link to [Jenkins JIRA issue][jenkins-jira]

- [x] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to [plugin's GitHub repository][plugin]

- [x] Link to Plugin Compatibility Tracker #809

### Description

If P4 credentials are configured, then JCasC fails to export Jenkins configuration with an error:

```
FAILED TO EXPORT com.cloudbees.plugins.credentials.domains.DomainCredentials#credentials: java.lang.IllegalArgumentException: argument type mismatch
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:255)
  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:224)
  at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:224)
  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:103)
  at io.vavr.control.Option.map(Option.java:373)
  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:103)
  at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:51)
  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)
  at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:264)
  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:194)
  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:76)
  at com.cloudbees.plugins.credentials.casc.SystemCredentialsProviderConfigurator.describe(SystemCredentialsProviderConfigurator.java:48)
  at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:198)
  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:90)
  at com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator.describe(CredentialsRootConfigurator.java:52)
```

**Comment by casz** [comment]
@courteouselk please follow the checklist... this needs to be reported on Jira.

**Comment by courteouselk** [comment]
It is reported on Jira, link is provided in the issue descpription as per the template.

https://issues.jenkins-ci.org/browse/JENKINS-58249

**Comment by casz** [comment]
Not obvious when pretty linking with writing [JENKINS-58249](https://issues.jenkins-ci.org/browse/JENKINS-58249) 😅
