### ISSUE TITLE
Can't handle command install source for tools

### ISSUE THREAD

**Issue by lanwen** [jenkinsci/configuration-as-code-plugin#97]
I'm trying to setup custom tool with:

```
tool:
  customtool:
    installations:
      - name: github-release
        home: ""
        properties:
          - installSource:
            - command:
                toolHome: ./bin/linux/amd64
                command: >
                  curl -o linux-amd64-github-release.tar.bz2 -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
                  tar -xvjf linux-amd64-github-release.tar.bz2
```

but on my installation it gets NPE :) `org/jenkinsci/plugins/casc/DataBoundConfigurator.java:75`
If I check configurator for null with 

```java
 if (lookup == null) {
                            throw new IllegalStateException(
                                    String.format("Can't find configurator for %s to configure %s for parameter %s", pt, value, parameters[i])
                            );
                        }
```

it says 

```java
Caused by: java.lang.IllegalStateException: Can't find configurator for interface java.util.List to configure [{installSource=[{command={toolHome=./bin/linux/amd64, command=curl -o linux-amd64-github-release.tar.bz2 -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 tar -xvjf linux-amd64-github-release.tar.bz2
}}]}] for parameter java.util.List arg2
        at org.jenkinsci.plugins.casc.DataBoundConfigurator.configure(DataBoundConfigurator.java:78)
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:168)
        at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:45)
        at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:12)
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:173)
        at org.jenkinsci.plugins.casc.GlobalConfigurationCategoryConfigurator.configure(GlobalConfigurationCategoryConfigurator.java:45)
```

tried to reproduce and debug with tests, but got only

```java
Caused by: java.lang.IllegalStateException: Can't handle java.util.List<? extends hudson.tools.ToolProperty<?>>
        at org.jenkinsci.plugins.casc.Configurator.lookup(Configurator.java:87)
        at org.jenkinsci.plugins.casc.DataBoundConfigurator.configure(DataBoundConfigurator.java:74)
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:168)
        at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:45)
        at org.jenkinsci.plugins.casc.DescriptorConfigurator.configure(DescriptorConfigurator.java:12)
        at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:173)
        at org.jenkinsci.plugins.casc.GlobalConfigurationCategoryConfigurator.configure(GlobalConfigurationCategoryConfigurator.java:45)

```

I understand that this is a very early stage, but maybe a workaround exists?

**Comment by oleg-nenashev** [comment]
Just to be clear, are you trying to define https://github.com/jenkinsci/custom-tools-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomTool.java ?

**Comment by ndeloof** [comment]
seems we fail to detect attribute type from constructor parameter `List<? extends ToolProperty<?>>`

**Comment by ndeloof** [comment]
[CustomTool](https://github.com/jenkinsci/custom-tools-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/customtools/CustomTool.java#L94) constructor use erased type `List` for properties, so we can't introspect the actual type to be configured here.

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/custom-tools-plugin/pull/31
