### ISSUE TITLE
SonarQube plugin stops working with JCasC 1.24

### ISSUE THREAD

**Issue by svenstaro** [jenkinsci/configuration-as-code-plugin#982]
[jenkins-jira]: https://issues.jenkins-ci.org
[dashboard]: https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=18341
[contributing]: ../blob/master/docs/CONTRIBUTING.md
[compatibility]: ../blob/master/docs/COMPATIBILITY.md

### Your checklist for this issue

🚨 Please review the [guidelines for contributing][contributing] to this repository.
💡 To better understand plugin compatibility issues, you can [read more here][compatibility]

- [x] Create an issue on [issues.jenkins-ci.org][jenkins-jira], set the component to the plugin you are reporting it against

- [x] Before creating an issue on [Jenkins JIRA][jenkins-jira], check for [an existing one via dashboard][dashboard]

- [x] Link to [Jenkins JIRA issue](https://issues.jenkins-ci.org/browse/JENKINS-58854)

- [x] Ensure [Jenkins JIRA issue][jenkins-jira] has the label `jcasc-compatibility`

- [x] Link to plugin's [GitHub repository](https://github.com/SonarSource/sonar-scanner-jenkins)

### Description

The most recent version of JCasC that works with SonarQube is 1.23. Anything after that results in

```
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: unclassified: error configuring 'unclassified' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:652)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:684)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:668)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:567)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:280)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:272)
	... 13 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: triggers is required to configure class hudson.plugins.sonar.SonarInstallation
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:134)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:268)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:684)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:646)
	... 18 more
```
I'm doing this:
```
sonarglobalconfiguration:
  buildWrapperEnabled: true
  installations:
    - name: "SonarQube 1"
      serverUrl: "http://example.com/sonar1"
      serverAuthenticationToken: "asdasd"
    - name: "SonarQube 2"
      serverUrl: "https://example.com/sonar2"
      serverAuthenticationToken: "fvcxvffsadfasdd"
```

**Comment by svenstaro** [comment]
I think this might be related: https://github.com/jenkinsci/configuration-as-code-plugin/pull/950

**Comment by casz** [comment]
If you read the stacktrace it says: triggers is required to configure class hudson.plugins.sonar.SonarInstallation

**Comment by casz** [comment]
you should report this issue on Jenkins Jira so the right maintainer can fix the issue:

They should change this massive DataBoundConstructor
https://github.com/SonarSource/sonar-scanner-jenkins/blob/master/src/main/java/hudson/plugins/sonar/SonarInstallation.java#L83-L101
To only have mandatory fields there and then use DataBoundSetter for any additional parameters like Triggers

wink @henryju

**Comment by casz** [comment]
SonarGlobalConfiguration definitely needs some love as well:
I see a lot of this: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#descriptors-global-configuration

This is an issue
https://github.com/SonarSource/sonar-scanner-jenkins/blob/b2f16ac18319f86be7742efb21970ec7b6d955c8/src/main/java/hudson/plugins/sonar/SonarGlobalConfiguration.java#L129-L136

and so is https://github.com/SonarSource/sonar-scanner-jenkins/blob/b2f16ac18319f86be7742efb21970ec7b6d955c8/src/main/resources/hudson/plugins/sonar/SonarGlobalConfiguration/config.jelly
https://github.com/SonarSource/sonar-scanner-jenkins/blob/master/src/main/resources/hudson/plugins/sonar/SonarGlobalConfiguration/config.jelly

They are all using syntax like this
```
<f:entry title="${%MojoVersion}" description="${%MojoVersionDescr}">
  <f:textbox name="sonar.mojoVersion" value="${inst.getMojoVersion()}"/>
</f:entry>
```

Should be like this
```
<f:entry title="${%MojoVersion}" field="mojoVersion" description="${%MojoVersionDescr}">
  <f:textbox />
</f:entry>
```

**Comment by svenstaro** [comment]
I did report it in the Jenkins Jira she's linked the issue above.

**Comment by timja** [comment]
This is unrelated to the configuration-as-code plugin, closing this, would be good if you could add the jenkins jira link so that other people who find this issue can go to that one instead

**Comment by svenstaro** [comment]
As I said, that link is in the checklist.

**Comment by timja** [comment]
Didn't see it before, I've edited to make it clearer

**Comment by henryju** [comment]
I created a ticket here: https://jira.sonarsource.com/browse/SONARJNKNS-307
But it will probably be low priority for us in the coming weeks, so please feel free to provide a PR in https://github.com/SonarSource/sonar-scanner-jenkins with the fix if you know it.

**Comment by casz** [comment]
It's not a small fix 😬
