### ISSUE TITLE
[JENKINS-56774] - Failed to export authorizeproject.GlobalQueueItemAuthenticator

### ISSUE THREAD

**Issue by henrywang** [jenkinsci/configuration-as-code-plugin#983]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description
Cannot export configuration when configuring `Run as the specified user` on `Manage Jenkins » Configure Global Security` and Adding `Project default Build Authorization`
If I change `Run as specified user` to the other strategies, like system, anonymous, and user who triggered build, the export works perfectly.
The Jenkins master uses LDAP authentication with Role-Based Strategy.
* Jenkins version: 2.176.2
* Plugin `Authorize Project` version: 1.3.0
* OS: CentOS 7

Log:
```yaml
queueItemAuthenticator:
    authenticators:
    - global:
        strategy: |-
          FAILED TO EXPORT
          org.jenkinsci.plugins.authorizeproject.GlobalQueueItemAuthenticator#strategy: io.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'useApitoken' from org.jenkinsci.plugins.authorizeproject.strategy.SpecificUsersAuthorizationStrategy@68656cee
            at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:262)
            at io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:180)
            at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:250)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:283)
            at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:283)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
            at io.vavr.control.Option.map(Option.java:373)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
            at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:202)
            at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:274)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$convertToNode$de0cd4f8$1(HeteroDescribableConfigurator.java:283)
            at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.convertToNode(HeteroDescribableConfigurator.java:283)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$describe$5(HeteroDescribableConfigurator.java:107)
            at io.vavr.control.Option.map(Option.java:373)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:107)
            at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:55)
            at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:198)
            at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:161)
            at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:106)
            at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$3(GlobalConfigurationCategoryConfigurator.java:99)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
            at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
            at java.util.Iterator.forEachRemaining(Iterator.java:116)
            at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
            at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
            at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
            at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
            at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
            at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:99)
            at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:30)
```

**Comment by oleg-nenashev** [comment]
The plugin is not compatible with JCasC. See https://issues.jenkins-ci.org/browse/JENKINS-56774

**Comment by henrywang** [comment]
Thanks @oleg-nenashev !
Form my understanding, the Jenkins works with the following configuration, but failed on `export`. Is this correct?
```yaml
    security: 
      queueItemAuthenticator: 
        authenticators: 
        - global: 
            strategy: 
              specificUsersAuthorizationStrategy: 
                userid: service-user
```
